/* 由 fetch_hf.py 自動產生，請勿手動編輯 */
window.DAILY_MODELS = {
 "schema_version": 1,
 "generator": "fetch_hf.py 1.0.0",
 "snapshot_date": "2026-10-08",
 "generated_at": "2026-10-08T02:41:29+00:00",
 "generated_at_local": "2026-10-08 02:41",
 "source": {
  "name": "Hugging Face Hub API",
  "endpoint": "https://huggingface.co/api/models?sort=trendingScore&limit=60",
  "enrichment": null
 },
 "previous_snapshot": "2026-10-07",
 "method": {
  "weights": {
   "momentum": 0.35,
   "velocity": 0.25,
   "recency": 0.15,
   "originality": 0.15,
   "rarity": 0.1
  },
  "recency_half_life_days": 14.0,
  "originality": {
   "original": 1.0,
   "finetune": 0.45,
   "derived": 0.4,
   "merge": 0.35,
   "adapter": 0.35,
   "quantized": 0.0
  },
  "pick_rules": "排除量化轉檔與移除安全對齊版本；依分數貪婪挑選，同作者 ≤2、同任務 ≤3，不足時放寬"
 },
 "stats": {
  "fetched": 60,
  "models": 60,
  "picks": 12,
  "derivatives": {
   "adapter": 6,
   "finetune": 11,
   "original": 20,
   "quantized": 23
  },
  "quantized_hidden_by_default": 23,
  "task_counts": {
   "圖文理解（VLM）": 9,
   "文字分類": 5,
   "圖生影片": 3,
   "語音辨識（ASR）": 3,
   "未標註任務": 3,
   "圖文生影片": 2,
   "影片轉換": 2,
   "文字生成": 2,
   "特徵萃取 / 嵌入": 1,
   "語音合成（TTS）": 1,
   "文生圖": 1,
   "圖生圖 / 影像編輯": 1,
   "詞元標註 / NER": 1,
   "文字重排序": 1,
   "遮罩生成": 1,
   "other": 1
  },
  "group_counts": {
   "語言": 10,
   "多模態": 9,
   "影像 / 影音生成": 9,
   "語音 / 音訊": 4,
   "其他": 4,
   "電腦視覺": 1
  },
  "elapsed_sec": 0.32
 },
 "picks": [
  "Cloudflare/clef",
  "convaiinnovations/laya",
  "autotrust/GEV-26B-Decide",
  "autotrust/JEV-27B-VL",
  "canberkkkkkk/ema-lightning",
  "Qwen/Qwen3.8-27B",
  "Qwen/Qwen-Image-2.1",
  "google/embeddinggemma-2",
  "Lightricks/LTX-2.5",
  "MiniMaxAI/MiniMax-H3",
  "Cactus-Compute/whistle",
  "Contrastive-LM/CLM-v0.1-8B"
 ],
 "models": [
  {
   "id": "autotrust/JEV-27B-VL",
   "author": "autotrust",
   "author_fullname": null,
   "author_followers": null,
   "name": "JEV-27B-VL",
   "url": "https://huggingface.co/autotrust/JEV-27B-VL",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 2051,
   "downloads": 1529210,
   "trending_score": 1696.0,
   "created_at": "2026-09-30T05:02:23.000Z",
   "last_modified": null,
   "age_days": 7.9,
   "like_velocity": 259.5,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2512.16899"
   ],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5",
    "jev",
    "system-one",
    "system-two",
    "typed-decisions",
    "decision-model"
   ],
   "rank_trending": 1,
   "score_breakdown": {
    "momentum": 1.0,
    "velocity": 0.966,
    "recency": 0.569,
    "originality": 0.35,
    "rarity": 0.757
   },
   "score": 80.5,
   "rank_prev": 2,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🔥 平均每天 +260 讚",
    "📄 附論文 arXiv:2512.16899",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 LoRA 掛載於 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": 4
  },
  {
   "id": "Cloudflare/clef",
   "author": "Cloudflare",
   "author_fullname": null,
   "author_followers": null,
   "name": "clef",
   "url": "https://huggingface.co/Cloudflare/clef",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 1828,
   "downloads": 9513,
   "trending_score": 1633.0,
   "created_at": "2026-09-30T21:15:35.000Z",
   "last_modified": null,
   "age_days": 7.23,
   "like_velocity": 253.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5",
    "clef",
    "cloudflare",
    "systemone",
    "decision-model",
    "qwen3.8"
   ],
   "rank_trending": 2,
   "score_breakdown": {
    "momentum": 0.983,
    "velocity": 0.949,
    "recency": 0.597,
    "originality": 0.45,
    "rarity": 0.757
   },
   "score": 81.4,
   "rank_prev": 1,
   "is_new_entry": false,
   "rank_change": -1,
   "reasons": [
    "🔥 平均每天 +253 讚",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": 1
  },
  {
   "id": "autotrust/GEV-26B-Decide",
   "author": "autotrust",
   "author_fullname": null,
   "author_followers": null,
   "name": "GEV-26B-Decide",
   "url": "https://huggingface.co/autotrust/GEV-26B-Decide",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 1365,
   "downloads": 895867,
   "trending_score": 1146.0,
   "created_at": "2026-10-02T04:20:21.000Z",
   "last_modified": null,
   "age_days": 5.93,
   "like_velocity": 230.1,
   "params_b": 26.0,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "google/gemma-4-26B-A4B-it",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gemma4",
    "image-text-to-text",
    "system-one",
    "system-two",
    "adaptive-thinking",
    "typed-decisions"
   ],
   "rank_trending": 3,
   "score_breakdown": {
    "momentum": 0.966,
    "velocity": 0.932,
    "recency": 0.655,
    "originality": 0.35,
    "rarity": 0.865
   },
   "score": 80.8,
   "rank_prev": 5,
   "is_new_entry": false,
   "rank_change": 2,
   "reasons": [
    "⏱️ 6 天前才發布",
    "🔥 平均每天 +230 讚",
    "🧩 MoE 混合專家架構",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 LoRA 掛載於 google/gemma-4-26B-A4B-it"
   ],
   "pick_rank": 3
  },
  {
   "id": "google/embeddinggemma-2",
   "author": "google",
   "author_fullname": null,
   "author_followers": null,
   "name": "embeddinggemma-2",
   "url": "https://huggingface.co/google/embeddinggemma-2",
   "pipeline_tag": "feature-extraction",
   "task_zh": "特徵萃取 / 嵌入",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 978,
   "downloads": 7562,
   "trending_score": 953.0,
   "created_at": "2026-09-14T14:53:42.000Z",
   "last_modified": null,
   "age_days": 23.49,
   "like_velocity": 41.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "embedding_gemma2",
    "embedding",
    "sentence-transformers",
    "multimodal-embedding",
    "multimodal",
    "vision"
   ],
   "rank_trending": 4,
   "score_breakdown": {
    "momentum": 0.949,
    "velocity": 0.551,
    "recency": 0.187,
    "originality": 1.0,
    "rarity": 0.973
   },
   "score": 74.5,
   "rank_prev": 6,
   "is_new_entry": false,
   "rank_change": 2,
   "reasons": [
    "🧭 今日榜單少見的任務：特徵萃取 / 嵌入",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 8
  },
  {
   "id": "Aleph-Alpha/Kolibri-1",
   "author": "Aleph-Alpha",
   "author_fullname": null,
   "author_followers": null,
   "name": "Kolibri-1",
   "url": "https://huggingface.co/Aleph-Alpha/Kolibri-1",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "vllm",
   "likes": 784,
   "downloads": 5775,
   "trending_score": 726.0,
   "created_at": "2026-10-02T05:54:02.000Z",
   "last_modified": null,
   "age_days": 5.87,
   "like_velocity": 133.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2512.11614",
    "2601.17858"
   ],
   "languages": [
    "de",
    "en"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Aleph-Alpha/Kolibri-1-BF16",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "kolibri1",
    "reasoning",
    "moe",
    "fp8"
   ],
   "rank_trending": 5,
   "score_breakdown": {
    "momentum": 0.932,
    "velocity": 0.864,
    "recency": 0.658,
    "originality": 0.0,
    "rarity": 0.946
   },
   "score": 73.6,
   "rank_prev": 3,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "⏱️ 6 天前才發布",
    "🔥 平均每天 +134 讚",
    "🧭 今日榜單少見的任務：文字生成",
    "🧩 MoE 混合專家架構",
    "📄 附論文 arXiv:2512.11614"
   ],
   "pick_rank": null
  },
  {
   "id": "abenzerps/Qwen-Image-2.1-Uncensored-GGUF",
   "author": "abenzerps",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1-Uncensored-GGUF",
   "url": "https://huggingface.co/abenzerps/Qwen-Image-2.1-Uncensored-GGUF",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "gguf",
   "likes": 3581,
   "downloads": 1820627,
   "trending_score": 683.0,
   "created_at": "2026-09-20T15:51:13.000Z",
   "last_modified": null,
   "age_days": 17.45,
   "like_velocity": 205.2,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen",
    "image-generation",
    "comfyui",
    "comfyui-gguf"
   ],
   "rank_trending": 6,
   "score_breakdown": {
    "momentum": 0.915,
    "velocity": 0.915,
    "recency": 0.288,
    "originality": 0.0,
    "rarity": 0.973
   },
   "score": 69.0,
   "rank_prev": 4,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "🔥 平均每天 +205 讚",
    "🧭 今日榜單少見的任務：文生圖",
    "🔗 量化轉檔自 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "Cloudflare/clef-flash",
   "author": "Cloudflare",
   "author_fullname": null,
   "author_followers": null,
   "name": "clef-flash",
   "url": "https://huggingface.co/Cloudflare/clef-flash",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 662,
   "downloads": 15722,
   "trending_score": 598.0,
   "created_at": "2026-09-30T21:15:36.000Z",
   "last_modified": null,
   "age_days": 7.23,
   "like_velocity": 91.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3.5-9B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5",
    "clef",
    "cloudflare",
    "systemone",
    "decision-model",
    "qwen3.5"
   ],
   "rank_trending": 7,
   "score_breakdown": {
    "momentum": 0.898,
    "velocity": 0.797,
    "recency": 0.597,
    "originality": 0.45,
    "rarity": 0.757
   },
   "score": 74.6,
   "rank_prev": 7,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🔥 平均每天 +92 讚",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 Qwen/Qwen3.5-9B"
   ],
   "pick_rank": null
  },
  {
   "id": "Venastine-Research/Xing4.0-29B-A4B-GGUF",
   "author": "Venastine-Research",
   "author_fullname": null,
   "author_followers": null,
   "name": "Xing4.0-29B-A4B-GGUF",
   "url": "https://huggingface.co/Venastine-Research/Xing4.0-29B-A4B-GGUF",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 634,
   "downloads": 33633,
   "trending_score": 586.0,
   "created_at": "2026-09-17T18:37:31.000Z",
   "last_modified": null,
   "age_days": 20.34,
   "like_velocity": 31.2,
   "params_b": 29.0,
   "active_params_b": 4.0,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2512.24157",
    "2507.18013"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "XingChen-AGI/Xing4.0-29B-A4B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "xing4_0"
   ],
   "rank_trending": 8,
   "score_breakdown": {
    "momentum": 0.881,
    "velocity": 0.441,
    "recency": 0.234,
    "originality": 0.0,
    "rarity": 0.946
   },
   "score": 54.8,
   "rank_prev": 8,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🧭 今日榜單少見的任務：文字生成",
    "🧩 MoE 混合專家架構（啟用 4B）",
    "📄 附論文 arXiv:2512.24157",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 XingChen-AGI/Xing4.0-29B-A4B"
   ],
   "pick_rank": null
  },
  {
   "id": "Lightricks/LTX-2.5",
   "author": "Lightricks",
   "author_fullname": null,
   "author_followers": null,
   "name": "LTX-2.5",
   "url": "https://huggingface.co/Lightricks/LTX-2.5",
   "pipeline_tag": "image-to-video",
   "task_zh": "圖生影片",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusion-single-file",
   "likes": 6810,
   "downloads": 1674291,
   "trending_score": 479.0,
   "created_at": "2026-07-23T07:55:24.000Z",
   "last_modified": null,
   "age_days": 76.78,
   "like_velocity": 88.7,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2601.03233"
   ],
   "languages": [
    "en",
    "de",
    "es",
    "fr",
    "ja",
    "ko",
    "zh",
    "it"
   ],
   "n_languages": 9,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "text-to-video",
    "video-to-video",
    "image-text-to-video",
    "audio-to-video",
    "text-to-audio",
    "video-to-audio"
   ],
   "rank_trending": 9,
   "score_breakdown": {
    "momentum": 0.864,
    "velocity": 0.78,
    "recency": 0.004,
    "originality": 1.0,
    "rarity": 0.919
   },
   "score": 74.0,
   "rank_prev": 10,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "📄 附論文 arXiv:2601.03233"
   ],
   "pick_rank": 9
  },
  {
   "id": "jialinyyzz/humanizer",
   "author": "jialinyyzz",
   "author_fullname": null,
   "author_followers": null,
   "name": "humanizer",
   "url": "https://huggingface.co/jialinyyzz/humanizer",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "gguf",
   "likes": 477,
   "downloads": 19483,
   "trending_score": 442.0,
   "created_at": "2026-09-11T05:00:16.000Z",
   "last_modified": null,
   "age_days": 26.9,
   "like_velocity": 17.7,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "google/gemma-4-12B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gemma4_unified",
    "image-text-to-text",
    "humanizer",
    "transformers",
    "text-rewriting",
    "rewriting"
   ],
   "rank_trending": 10,
   "score_breakdown": {
    "momentum": 0.847,
    "velocity": 0.22,
    "recency": 0.146,
    "originality": 0.0,
    "rarity": 0.946
   },
   "score": 46.8,
   "rank_prev": 11,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🧭 今日榜單少見的任務：文字生成",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 google/gemma-4-12B"
   ],
   "pick_rank": null
  },
  {
   "id": "convaiinnovations/laya",
   "author": "convaiinnovations",
   "author_fullname": null,
   "author_followers": null,
   "name": "laya",
   "url": "https://huggingface.co/convaiinnovations/laya",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 5346,
   "downloads": 28497,
   "trending_score": 434.0,
   "created_at": "2026-09-18T05:05:55.000Z",
   "last_modified": null,
   "age_days": 19.9,
   "like_velocity": 268.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "laya",
    "system-one",
    "calibrated-decisions",
    "rlcd",
    "classification",
    "routing"
   ],
   "rank_trending": 11,
   "score_breakdown": {
    "momentum": 0.831,
    "velocity": 0.983,
    "recency": 0.241,
    "originality": 1.0,
    "rarity": 0.865
   },
   "score": 80.9,
   "rank_prev": 9,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "🔥 平均每天 +269 讚",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 2
  },
  {
   "id": "Qwen/Qwen3.8-27B",
   "author": "Qwen",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B",
   "url": "https://huggingface.co/Qwen/Qwen3.8-27B",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 17216,
   "downloads": 6758993,
   "trending_score": 340.0,
   "created_at": "2026-08-05T08:22:59.000Z",
   "last_modified": null,
   "age_days": 63.76,
   "like_velocity": 270.0,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5"
   ],
   "rank_trending": 12,
   "score_breakdown": {
    "momentum": 0.814,
    "velocity": 1.0,
    "recency": 0.011,
    "originality": 1.0,
    "rarity": 0.757
   },
   "score": 76.2,
   "rank_prev": 12,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🔥 平均每天 +270 讚",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 6
  },
  {
   "id": "canberkkkkkk/ema-lightning",
   "author": "canberkkkkkk",
   "author_fullname": null,
   "author_followers": null,
   "name": "ema-lightning",
   "url": "https://huggingface.co/canberkkkkkk/ema-lightning",
   "pipeline_tag": "text-to-speech",
   "task_zh": "語音合成（TTS）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": null,
   "likes": 273,
   "downloads": 2724,
   "trending_score": 251.0,
   "created_at": "2026-10-01T14:18:49.000Z",
   "last_modified": null,
   "age_days": 6.52,
   "like_velocity": 41.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2405.14867"
   ],
   "languages": [
    "tr"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "ema-lightning",
    "tts",
    "turkish",
    "speech-synthesis",
    "flow-matching"
   ],
   "rank_trending": 13,
   "score_breakdown": {
    "momentum": 0.797,
    "velocity": 0.576,
    "recency": 0.628,
    "originality": 1.0,
    "rarity": 0.973
   },
   "score": 76.4,
   "rank_prev": 40,
   "is_new_entry": false,
   "rank_change": 27,
   "reasons": [
    "📈 排名上升 27 名",
    "⏱️ 7 天前才發布",
    "🧭 今日榜單少見的任務：語音合成（TTS）",
    "📄 附論文 arXiv:2405.14867",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 5
  },
  {
   "id": "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
   "author": "ISTA-DASLab",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
   "url": "https://huggingface.co/ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 699,
   "downloads": 3080123,
   "trending_score": 239.0,
   "created_at": "2026-09-07T09:41:37.000Z",
   "last_modified": null,
   "age_days": 30.71,
   "like_velocity": 22.8,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-Flash-Next",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gsq",
    "rco",
    "quantization",
    "mixed-precision",
    "ist-daslab",
    "moe"
   ],
   "rank_trending": 14,
   "score_breakdown": {
    "momentum": 0.78,
    "velocity": 0.288,
    "recency": 0.112,
    "originality": 0.0,
    "rarity": 0.757
   },
   "score": 43.7,
   "rank_prev": 14,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🧩 MoE 混合專家架構",
    "📄 附論文 arXiv:2604.18556",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-Flash-Next"
   ],
   "pick_rank": null
  },
  {
   "id": "Qwen/Qwen-Image-2.1",
   "author": "Qwen",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1",
   "url": "https://huggingface.co/Qwen/Qwen-Image-2.1",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 3099,
   "downloads": 109298,
   "trending_score": 229.0,
   "created_at": "2026-09-14T03:47:26.000Z",
   "last_modified": null,
   "age_days": 23.95,
   "like_velocity": 129.4,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen",
    "image-generation",
    "image-editing",
    "rgba"
   ],
   "rank_trending": 15,
   "score_breakdown": {
    "momentum": 0.763,
    "velocity": 0.847,
    "recency": 0.181,
    "originality": 1.0,
    "rarity": 0.973
   },
   "score": 75.3,
   "rank_prev": 13,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "🔥 平均每天 +129 讚",
    "🧭 今日榜單少見的任務：文生圖"
   ],
   "pick_rank": 7
  },
  {
   "id": "Infatoshi/GLM-5.3-UNCENSORED-EXL3-3.0bpw",
   "author": "Infatoshi",
   "author_fullname": null,
   "author_followers": null,
   "name": "GLM-5.3-UNCENSORED-EXL3-3.0bpw",
   "url": "https://huggingface.co/Infatoshi/GLM-5.3-UNCENSORED-EXL3-3.0bpw",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "exllamav3",
   "likes": 292,
   "downloads": 1903,
   "trending_score": 224.0,
   "created_at": "2026-10-01T03:42:00.000Z",
   "last_modified": null,
   "age_days": 6.96,
   "like_velocity": 42.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "dealignai/GLM-5.3-UNCENSORED-FP8",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "glm_moe_dsa",
    "exl3",
    "glm",
    "moe",
    "uncensored"
   ],
   "rank_trending": 16,
   "score_breakdown": {
    "momentum": 0.746,
    "velocity": 0.593,
    "recency": 0.608,
    "originality": 0.0,
    "rarity": 0.946
   },
   "score": 59.5,
   "rank_prev": 16,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "⏱️ 7 天前才發布",
    "🧭 今日榜單少見的任務：文字生成",
    "🧩 MoE 混合專家架構",
    "✅ 寬鬆授權（mit）",
    "🔗 量化轉檔自 dealignai/GLM-5.3-UNCENSORED-FP8"
   ],
   "pick_rank": null
  },
  {
   "id": "TaichuAI/ZDTaichu5.0-9B",
   "author": "TaichuAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "ZDTaichu5.0-9B",
   "url": "https://huggingface.co/TaichuAI/ZDTaichu5.0-9B",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": null,
   "likes": 2908,
   "downloads": 12970,
   "trending_score": 199.0,
   "created_at": "2026-09-04T02:55:48.000Z",
   "last_modified": null,
   "age_days": 33.99,
   "like_velocity": 85.6,
   "params_b": 9.0,
   "active_params_b": null,
   "is_moe": false,
   "license": null,
   "permissive_license": false,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "zdtaichu5_0",
    "multimodal",
    "vision-language-model",
    "spatial-reasoning",
    "agent",
    "video-understanding"
   ],
   "rank_trending": 17,
   "score_breakdown": {
    "momentum": 0.729,
    "velocity": 0.746,
    "recency": 0.088,
    "originality": 1.0,
    "rarity": 0.757
   },
   "score": 68.0,
   "rank_prev": 17,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [],
   "pick_rank": null
  },
  {
   "id": "orcarouter/OrcaSAQ-2-Cyber-27B-Uncensored-GGUF",
   "author": "orcarouter",
   "author_fullname": null,
   "author_followers": null,
   "name": "OrcaSAQ-2-Cyber-27B-Uncensored-GGUF",
   "url": "https://huggingface.co/orcarouter/OrcaSAQ-2-Cyber-27B-Uncensored-GGUF",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "llama.cpp",
   "likes": 462,
   "downloads": 19030,
   "trending_score": 191.0,
   "created_at": "2026-09-26T03:37:50.000Z",
   "last_modified": null,
   "age_days": 11.96,
   "like_velocity": 38.6,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "orcarouter/Qwen3.8-27B-Uncensored",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "qwen",
    "qwen3.8",
    "qwen3_5",
    "orcasaq2",
    "quantization"
   ],
   "rank_trending": 18,
   "score_breakdown": {
    "momentum": 0.712,
    "velocity": 0.525,
    "recency": 0.426,
    "originality": 0.0,
    "rarity": 0.946
   },
   "score": 53.9,
   "rank_prev": 18,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🧭 今日榜單少見的任務：文字生成",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 orcarouter/Qwen3.8-27B-Uncensored",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "Qwen/Qwen3.8-Flash-Next",
   "author": "Qwen",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next",
   "url": "https://huggingface.co/Qwen/Qwen3.8-Flash-Next",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 6021,
   "downloads": 1609433,
   "trending_score": 175.0,
   "created_at": "2026-08-24T08:24:59.000Z",
   "last_modified": null,
   "age_days": 44.76,
   "like_velocity": 134.5,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen4_exp"
   ],
   "rank_trending": 19,
   "score_breakdown": {
    "momentum": 0.695,
    "velocity": 0.881,
    "recency": 0.041,
    "originality": 1.0,
    "rarity": 0.757
   },
   "score": 69.5,
   "rank_prev": 20,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🔥 平均每天 +134 讚"
   ],
   "pick_rank": null
  },
  {
   "id": "Alissonerdx/BFS-Best-Face-Swap",
   "author": "Alissonerdx",
   "author_fullname": null,
   "author_followers": null,
   "name": "BFS-Best-Face-Swap",
   "url": "https://huggingface.co/Alissonerdx/BFS-Best-Face-Swap",
   "pipeline_tag": "image-to-image",
   "task_zh": "圖生圖 / 影像編輯",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 1298,
   "downloads": 238952,
   "trending_score": 173.0,
   "created_at": "2025-11-07T09:50:28.000Z",
   "last_modified": null,
   "age_days": 334.7,
   "like_velocity": 3.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "lora",
    "qwen-image",
    "qwen-image-2.1",
    "qwen-image-edit",
    "face-swap",
    "head-swap"
   ],
   "rank_trending": 20,
   "score_breakdown": {
    "momentum": 0.678,
    "velocity": 0.0,
    "recency": 0.0,
    "originality": 0.35,
    "rarity": 0.973
   },
   "score": 38.7,
   "rank_prev": 24,
   "is_new_entry": false,
   "rank_change": 4,
   "reasons": [
    "🧭 今日榜單少見的任務：圖生圖 / 影像編輯",
    "✅ 寬鬆授權（mit）",
    "🔗 LoRA 掛載於 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "unsloth/embeddinggemma-2-GGUF",
   "author": "unsloth",
   "author_fullname": null,
   "author_followers": null,
   "name": "embeddinggemma-2-GGUF",
   "url": "https://huggingface.co/unsloth/embeddinggemma-2-GGUF",
   "pipeline_tag": "feature-extraction",
   "task_zh": "特徵萃取 / 嵌入",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": null,
   "likes": 174,
   "downloads": 11470,
   "trending_score": 172.0,
   "created_at": "2026-10-06T10:58:50.000Z",
   "last_modified": null,
   "age_days": 1.65,
   "like_velocity": 105.2,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "google/embeddinggemma-2",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "embedding",
    "multimodal-embedding",
    "multimodal",
    "vision",
    "audio"
   ],
   "rank_trending": 21,
   "score_breakdown": {
    "momentum": 0.661,
    "velocity": 0.814,
    "recency": 0.889,
    "originality": 0.0,
    "rarity": 0.973
   },
   "score": 66.5,
   "rank_prev": 47,
   "is_new_entry": false,
   "rank_change": 26,
   "reasons": [
    "📈 排名上升 26 名",
    "⏱️ 2 天前才發布",
    "🔥 平均每天 +105 讚",
    "🧭 今日榜單少見的任務：特徵萃取 / 嵌入",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": null
  },
  {
   "id": "deepseek-ai/DeepSeek-V4.1-Flash",
   "author": "deepseek-ai",
   "author_fullname": null,
   "author_followers": null,
   "name": "DeepSeek-V4.1-Flash",
   "url": "https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 4234,
   "downloads": 1255513,
   "trending_score": 165.0,
   "created_at": "2026-09-10T02:17:58.000Z",
   "last_modified": null,
   "age_days": 28.02,
   "like_velocity": 151.1,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "deepseek_v41",
    "text-generation",
    "8-bit",
    "fp8"
   ],
   "rank_trending": 22,
   "score_breakdown": {
    "momentum": 0.644,
    "velocity": 0.898,
    "recency": 0.135,
    "originality": 1.0,
    "rarity": 0.757
   },
   "score": 69.6,
   "rank_prev": 21,
   "is_new_entry": false,
   "rank_change": -1,
   "reasons": [
    "🔥 平均每天 +151 讚",
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": null
  },
  {
   "id": "prism-ml/Ternary-Bonsai-2-27B-gguf",
   "author": "prism-ml",
   "author_fullname": null,
   "author_followers": null,
   "name": "Ternary-Bonsai-2-27B-gguf",
   "url": "https://huggingface.co/prism-ml/Ternary-Bonsai-2-27B-gguf",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "llama.cpp",
   "likes": 2530,
   "downloads": 4271466,
   "trending_score": 159.0,
   "created_at": "2026-09-16T23:40:56.000Z",
   "last_modified": null,
   "age_days": 21.13,
   "like_velocity": 119.8,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "gguf",
    "ternary",
    "2-bit",
    "llama-cpp",
    "cuda",
    "metal"
   ],
   "rank_trending": 23,
   "score_breakdown": {
    "momentum": 0.627,
    "velocity": 0.831,
    "recency": 0.221,
    "originality": 0.0,
    "rarity": 0.946
   },
   "score": 55.5,
   "rank_prev": 22,
   "is_new_entry": false,
   "rank_change": -1,
   "reasons": [
    "🔥 平均每天 +120 讚",
    "🧭 今日榜單少見的任務：文字生成",
    "📱 強調裝置端推論",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NEO-CODER-MAX-MTP-GGUF",
   "author": "DavidAU",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NEO-CODER-MAX-MTP-GGUF",
   "url": "https://huggingface.co/DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NEO-CODER-MAX-MTP-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": null,
   "likes": 1550,
   "downloads": 2088541,
   "trending_score": 158.0,
   "created_at": "2026-09-01T07:01:09.000Z",
   "last_modified": null,
   "age_days": 36.82,
   "like_velocity": 42.1,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NM-DAU",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "unsloth",
    "fine tune",
    "heretic",
    "uncensored",
    "abliterated"
   ],
   "rank_trending": 24,
   "score_breakdown": {
    "momentum": 0.61,
    "velocity": 0.61,
    "recency": 0.072,
    "originality": 0.0,
    "rarity": 0.757
   },
   "score": 45.3,
   "rank_prev": 26,
   "is_new_entry": false,
   "rank_change": 2,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NM-DAU",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "autotrust/GEV-26B-Decide-NVFP4",
   "author": "autotrust",
   "author_fullname": null,
   "author_followers": null,
   "name": "GEV-26B-Decide-NVFP4",
   "url": "https://huggingface.co/autotrust/GEV-26B-Decide-NVFP4",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 162,
   "downloads": 14957,
   "trending_score": 146.0,
   "created_at": "2026-10-05T01:31:09.000Z",
   "last_modified": null,
   "age_days": 3.05,
   "like_velocity": 53.1,
   "params_b": 26.0,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "autotrust/GEV-26B-Decide",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gemma4",
    "image-text-to-text",
    "system-one",
    "system-two",
    "adaptive-thinking",
    "typed-decisions"
   ],
   "rank_trending": 25,
   "score_breakdown": {
    "momentum": 0.593,
    "velocity": 0.695,
    "recency": 0.804,
    "originality": 0.0,
    "rarity": 0.865
   },
   "score": 58.8,
   "rank_prev": 32,
   "is_new_entry": false,
   "rank_change": 7,
   "reasons": [
    "📈 排名上升 7 名",
    "⏱️ 3 天前才發布",
    "🧩 MoE 混合專家架構",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 autotrust/GEV-26B-Decide"
   ],
   "pick_rank": null
  },
  {
   "id": "Cactus-Compute/whistle",
   "author": "Cactus-Compute",
   "author_fullname": null,
   "author_followers": null,
   "name": "whistle",
   "url": "https://huggingface.co/Cactus-Compute/whistle",
   "pipeline_tag": "automatic-speech-recognition",
   "task_zh": "語音辨識（ASR）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": "cactus-needle",
   "likes": 147,
   "downloads": 2249,
   "trending_score": 145.0,
   "created_at": "2026-09-30T17:13:26.000Z",
   "last_modified": null,
   "age_days": 7.39,
   "like_velocity": 19.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "de",
    "fr",
    "es",
    "it",
    "nl",
    "pl"
   ],
   "n_languages": 7,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "whistle",
    "speech-recognition",
    "speech-to-text",
    "on-device",
    "edge",
    "quantization"
   ],
   "rank_trending": 26,
   "score_breakdown": {
    "momentum": 0.576,
    "velocity": 0.237,
    "recency": 0.59,
    "originality": 1.0,
    "rarity": 0.919
   },
   "score": 59.1,
   "rank_prev": 33,
   "is_new_entry": false,
   "rank_change": 7,
   "reasons": [
    "📈 排名上升 7 名",
    "📱 強調裝置端推論",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 11
  },
  {
   "id": "Viggle/Qwen-Image-2.1-viggle-turbo",
   "author": "Viggle",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1-viggle-turbo",
   "url": "https://huggingface.co/Viggle/Qwen-Image-2.1-viggle-turbo",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 663,
   "downloads": 326801,
   "trending_score": 144.0,
   "created_at": "2026-09-22T04:14:56.000Z",
   "last_modified": null,
   "age_days": 15.94,
   "like_velocity": 41.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "lora",
    "image-to-image",
    "image-editing",
    "distillation",
    "turbo"
   ],
   "rank_trending": 27,
   "score_breakdown": {
    "momentum": 0.559,
    "velocity": 0.551,
    "recency": 0.32,
    "originality": 0.0,
    "rarity": 0.973
   },
   "score": 47.9,
   "rank_prev": 25,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "🧭 今日榜單少見的任務：文生圖",
    "🔗 量化轉檔自 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-Coder-GGUF",
   "author": "ISTA-DASLab",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next-GSQ-RCO-Coder-GGUF",
   "url": "https://huggingface.co/ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-Coder-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 344,
   "downloads": 553685,
   "trending_score": 140.0,
   "created_at": "2026-09-26T09:42:51.000Z",
   "last_modified": null,
   "age_days": 11.71,
   "like_velocity": 29.4,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-Flash-Next",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gsq",
    "rco",
    "quantization",
    "pruning",
    "expert-pruning",
    "mixed-precision"
   ],
   "rank_trending": 28,
   "score_breakdown": {
    "momentum": 0.542,
    "velocity": 0.424,
    "recency": 0.433,
    "originality": 0.0,
    "rarity": 0.757
   },
   "score": 43.6,
   "rank_prev": 30,
   "is_new_entry": false,
   "rank_change": 2,
   "reasons": [
    "🧩 MoE 混合專家架構",
    "📄 附論文 arXiv:2604.18556",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-Flash-Next"
   ],
   "pick_rank": null
  },
  {
   "id": "ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF",
   "author": "ISTA-DASLab",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-GSQ-RCO-GGUF",
   "url": "https://huggingface.co/ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 2041,
   "downloads": 1546030,
   "trending_score": 139.0,
   "created_at": "2026-08-28T18:38:03.000Z",
   "last_modified": null,
   "age_days": 40.34,
   "like_velocity": 50.6,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gsq",
    "rco",
    "quantization",
    "mixed-precision",
    "ist-daslab",
    "multimodal"
   ],
   "rank_trending": 29,
   "score_breakdown": {
    "momentum": 0.525,
    "velocity": 0.678,
    "recency": 0.056,
    "originality": 0.0,
    "rarity": 0.757
   },
   "score": 43.7,
   "rank_prev": 23,
   "is_new_entry": false,
   "rank_change": -6,
   "reasons": [
    "📄 附論文 arXiv:2604.18556",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "orcarouter/Qwen3.8-Flash-Next-Uncensored-GGUF",
   "author": "orcarouter",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next-Uncensored-GGUF",
   "url": "https://huggingface.co/orcarouter/Qwen3.8-Flash-Next-Uncensored-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 647,
   "downloads": 431147,
   "trending_score": 135.0,
   "created_at": "2026-08-26T11:15:13.000Z",
   "last_modified": null,
   "age_days": 42.64,
   "like_velocity": 15.2,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-Flash-Next",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "abliterated",
    "uncensored",
    "qwen",
    "qwen3.8",
    "qwen4",
    "flash-next"
   ],
   "rank_trending": 30,
   "score_breakdown": {
    "momentum": 0.508,
    "velocity": 0.186,
    "recency": 0.048,
    "originality": 0.0,
    "rarity": 0.757
   },
   "score": 30.7,
   "rank_prev": 34,
   "is_new_entry": false,
   "rank_change": 4,
   "reasons": [
    "🧩 MoE 混合專家架構",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-Flash-Next",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "FermionResearch/Phonon-2",
   "author": "FermionResearch",
   "author_fullname": null,
   "author_followers": null,
   "name": "Phonon-2",
   "url": "https://huggingface.co/FermionResearch/Phonon-2",
   "pipeline_tag": "automatic-speech-recognition",
   "task_zh": "語音辨識（ASR）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": "mlx",
   "likes": 271,
   "downloads": 3750,
   "trending_score": 133.0,
   "created_at": "2026-09-28T11:48:47.000Z",
   "last_modified": null,
   "age_days": 9.62,
   "like_velocity": 28.2,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "cc-by-4.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "nvidia/parakeet-tdt-0.6b-v3",
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "parakeet_tdt_five_value",
    "apple-silicon",
    "speech-to-text",
    "asr",
    "stt",
    "low-bit"
   ],
   "rank_trending": 31,
   "score_breakdown": {
    "momentum": 0.492,
    "velocity": 0.407,
    "recency": 0.503,
    "originality": 0.0,
    "rarity": 0.919
   },
   "score": 44.1,
   "rank_prev": 15,
   "is_new_entry": false,
   "rank_change": -16,
   "reasons": [
    "📱 強調裝置端推論",
    "✅ 寬鬆授權（cc-by-4.0）",
    "🔗 量化轉檔自 nvidia/parakeet-tdt-0.6b-v3"
   ],
   "pick_rank": null
  },
  {
   "id": "MiniMaxAI/MiniMax-H3",
   "author": "MiniMaxAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiniMax-H3",
   "url": "https://huggingface.co/MiniMaxAI/MiniMax-H3",
   "pipeline_tag": "image-text-to-video",
   "task_zh": "圖文生影片",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "minimax-h3",
   "likes": 5973,
   "downloads": 3613449,
   "trending_score": 128.0,
   "created_at": "2026-07-28T10:45:18.000Z",
   "last_modified": null,
   "age_days": 71.66,
   "like_velocity": 83.3,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "diffusers",
    "text-to-video",
    "image-to-video",
    "video-to-video",
    "text-to-audio-video",
    "image-to-audio-video"
   ],
   "rank_trending": 32,
   "score_breakdown": {
    "momentum": 0.475,
    "velocity": 0.729,
    "recency": 0.006,
    "originality": 1.0,
    "rarity": 0.946
   },
   "score": 59.4,
   "rank_prev": 38,
   "is_new_entry": false,
   "rank_change": 6,
   "reasons": [
    "📈 排名上升 6 名",
    "🧭 今日榜單少見的任務：圖文生影片"
   ],
   "pick_rank": 10
  },
  {
   "id": "SC117/Qwen3.8-Flash-Next-GSQ-RCO-abliterated-GGUF",
   "author": "SC117",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next-GSQ-RCO-abliterated-GGUF",
   "url": "https://huggingface.co/SC117/Qwen3.8-Flash-Next-GSQ-RCO-abliterated-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 137,
   "downloads": 500723,
   "trending_score": 127.0,
   "created_at": "2026-10-02T03:42:33.000Z",
   "last_modified": null,
   "age_days": 5.96,
   "like_velocity": 23.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "llama-cpp",
    "abliterated",
    "uncensored",
    "quantization",
    "tensor-transplant",
    "gsq"
   ],
   "rank_trending": 33,
   "score_breakdown": {
    "momentum": 0.458,
    "velocity": 0.314,
    "recency": 0.653,
    "originality": 0.0,
    "rarity": 0.757
   },
   "score": 41.2,
   "rank_prev": 41,
   "is_new_entry": false,
   "rank_change": 8,
   "reasons": [
    "📈 排名上升 8 名",
    "⏱️ 6 天前才發布",
    "🧩 MoE 混合專家架構",
    "📄 附論文 arXiv:2604.18556",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": null
  },
  {
   "id": "pablodawson/MiniMax-H3-360-Orbit-LoRA",
   "author": "pablodawson",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiniMax-H3-360-Orbit-LoRA",
   "url": "https://huggingface.co/pablodawson/MiniMax-H3-360-Orbit-LoRA",
   "pipeline_tag": "image-text-to-video",
   "task_zh": "圖文生影片",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "minimax-h3",
   "likes": 254,
   "downloads": 10119,
   "trending_score": 126.0,
   "created_at": "2026-09-27T04:05:33.000Z",
   "last_modified": null,
   "age_days": 10.94,
   "like_velocity": 23.2,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "MiniMaxAI/MiniMax-H3",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "lora",
    "image-to-video",
    "first-last-frame",
    "flf2v",
    "camera-control",
    "orbit"
   ],
   "rank_trending": 34,
   "score_breakdown": {
    "momentum": 0.441,
    "velocity": 0.339,
    "recency": 0.458,
    "originality": 0.35,
    "rarity": 0.946
   },
   "score": 45.5,
   "rank_prev": 28,
   "is_new_entry": false,
   "rank_change": -6,
   "reasons": [
    "🧭 今日榜單少見的任務：圖文生影片",
    "🔗 LoRA 掛載於 MiniMaxAI/MiniMax-H3"
   ],
   "pick_rank": null
  },
  {
   "id": "nvidia/Nemotron-3-Diarization",
   "author": "nvidia",
   "author_fullname": null,
   "author_followers": null,
   "name": "Nemotron-3-Diarization",
   "url": "https://huggingface.co/nvidia/Nemotron-3-Diarization",
   "pipeline_tag": "voice-activity-detection",
   "task_zh": "語音活動偵測",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": "nemo",
   "likes": 742,
   "downloads": 62252,
   "trending_score": 125.0,
   "created_at": "2026-09-01T13:16:57.000Z",
   "last_modified": null,
   "age_days": 36.56,
   "like_velocity": 20.3,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "openmdw-1.1",
   "permissive_license": false,
   "arxiv": [
    "2409.06656",
    "2507.18446",
    "2605.15442"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "nemotron3_diarization",
    "audio-frame-classification",
    "speaker-diarization",
    "streaming-sortformer",
    "speaker-tagging"
   ],
   "rank_trending": 35,
   "score_breakdown": {
    "momentum": 0.424,
    "velocity": 0.254,
    "recency": 0.073,
    "originality": 0.0,
    "rarity": 1.0
   },
   "score": 32.3,
   "rank_prev": 27,
   "is_new_entry": false,
   "rank_change": -8,
   "reasons": [
    "🧭 今日榜單少見的任務：語音活動偵測",
    "📄 附論文 arXiv:2409.06656"
   ],
   "pick_rank": null
  },
  {
   "id": "microsoft/FrogNano-4B-2609",
   "author": "microsoft",
   "author_fullname": null,
   "author_followers": null,
   "name": "FrogNano-4B-2609",
   "url": "https://huggingface.co/microsoft/FrogNano-4B-2609",
   "pipeline_tag": null,
   "task_zh": "未標註任務",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": null,
   "likes": 125,
   "downloads": 874,
   "trending_score": 123.0,
   "created_at": "2026-09-17T00:13:57.000Z",
   "last_modified": null,
   "age_days": 21.1,
   "like_velocity": 5.9,
   "params_b": 4.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5"
   ],
   "rank_trending": 36,
   "score_breakdown": {
    "momentum": 0.407,
    "velocity": 0.034,
    "recency": 0.222,
    "originality": 1.0,
    "rarity": 0.3
   },
   "score": 36.4,
   "rank_prev": 39,
   "is_new_entry": false,
   "rank_change": 3,
   "reasons": [
    "🪶 僅 4B 參數，適合筆電／裝置端",
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": null
  },
  {
   "id": "akatz-ai/MiniMax-H3-Character-Swap-LoRA",
   "author": "akatz-ai",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiniMax-H3-Character-Swap-LoRA",
   "url": "https://huggingface.co/akatz-ai/MiniMax-H3-Character-Swap-LoRA",
   "pipeline_tag": "video-to-video",
   "task_zh": "影片轉換",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusion-single-file",
   "likes": 356,
   "downloads": 23458,
   "trending_score": 122.0,
   "created_at": "2026-09-25T08:14:15.000Z",
   "last_modified": null,
   "age_days": 12.77,
   "like_velocity": 27.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Comfy-Org/MiniMax-H3",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "minimax-h3",
    "lora",
    "character-swap",
    "video-editing",
    "ref2va",
    "comfyui"
   ],
   "rank_trending": 37,
   "score_breakdown": {
    "momentum": 0.39,
    "velocity": 0.39,
    "recency": 0.402,
    "originality": 0.35,
    "rarity": 0.946
   },
   "score": 44.1,
   "rank_prev": 31,
   "is_new_entry": false,
   "rank_change": -6,
   "reasons": [
    "🧭 今日榜單少見的任務：影片轉換",
    "🔗 LoRA 掛載於 Comfy-Org/MiniMax-H3"
   ],
   "pick_rank": null
  },
  {
   "id": "unsloth/Qwen3.8-27B-GGUF",
   "author": "unsloth",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-GGUF",
   "url": "https://huggingface.co/unsloth/Qwen3.8-27B-GGUF",
   "pipeline_tag": null,
   "task_zh": "未標註任務",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": null,
   "likes": 4926,
   "downloads": 6553039,
   "trending_score": 121.0,
   "created_at": "2026-08-13T08:28:40.000Z",
   "last_modified": null,
   "age_days": 55.76,
   "like_velocity": 88.3,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "qwen3_5",
    "unsloth",
    "imatrix"
   ],
   "rank_trending": 38,
   "score_breakdown": {
    "momentum": 0.373,
    "velocity": 0.763,
    "recency": 0.019,
    "originality": 0.0,
    "rarity": 0.3
   },
   "score": 35.4,
   "rank_prev": 35,
   "is_new_entry": false,
   "rank_change": -3,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "fastino/GLiNER2.5-Decide",
   "author": "fastino",
   "author_fullname": null,
   "author_followers": null,
   "name": "GLiNER2.5-Decide",
   "url": "https://huggingface.co/fastino/GLiNER2.5-Decide",
   "pipeline_tag": "token-classification",
   "task_zh": "詞元標註 / NER",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "gliner2",
   "likes": 390,
   "downloads": 72491,
   "trending_score": 114.0,
   "created_at": "2026-09-23T14:56:12.000Z",
   "last_modified": null,
   "age_days": 14.49,
   "like_velocity": 26.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2507.18546"
   ],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "fastino/gliner2-large-v1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "extractor",
    "Text classification",
    "Intent classification",
    "Sentiment Analysis",
    "Topic classification",
    "Named Entity Recognition"
   ],
   "rank_trending": 39,
   "score_breakdown": {
    "momentum": 0.356,
    "velocity": 0.364,
    "recency": 0.355,
    "originality": 0.45,
    "rarity": 0.973
   },
   "score": 43.4,
   "rank_prev": 37,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "🧭 今日榜單少見的任務：詞元標註 / NER",
    "📄 附論文 arXiv:2507.18546",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 fastino/gliner2-large-v1"
   ],
   "pick_rank": null
  },
  {
   "id": "FrancisRing/Prism",
   "author": "FrancisRing",
   "author_fullname": null,
   "author_followers": null,
   "name": "Prism",
   "url": "https://huggingface.co/FrancisRing/Prism",
   "pipeline_tag": "image-to-video",
   "task_zh": "圖生影片",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 114,
   "downloads": 0,
   "trending_score": 113.0,
   "created_at": "2026-09-24T09:58:12.000Z",
   "last_modified": null,
   "age_days": 13.7,
   "like_velocity": 8.3,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [
    "2610.05416"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "video-generation",
    "video diffusion transformer",
    "joint-video-audio-generation",
    "sparse-attention",
    "high-resolution"
   ],
   "rank_trending": 40,
   "score_breakdown": {
    "momentum": 0.339,
    "velocity": 0.051,
    "recency": 0.376,
    "originality": 1.0,
    "rarity": 0.919
   },
   "score": 43.0,
   "rank_prev": 48,
   "is_new_entry": false,
   "rank_change": 8,
   "reasons": [
    "📈 排名上升 8 名",
    "📄 附論文 arXiv:2610.05416",
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": null
  },
  {
   "id": "SupersonicLabs/Julia-1",
   "author": "SupersonicLabs",
   "author_fullname": null,
   "author_followers": null,
   "name": "Julia-1",
   "url": "https://huggingface.co/SupersonicLabs/Julia-1",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "pytorch",
   "likes": 465,
   "downloads": 4388,
   "trending_score": 109.0,
   "created_at": "2026-09-23T15:29:46.000Z",
   "last_modified": null,
   "age_days": 14.47,
   "like_velocity": 32.1,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "jhu-clsp/mmBERT-small",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "decision-model",
    "multilingual",
    "routing"
   ],
   "rank_trending": 41,
   "score_breakdown": {
    "momentum": 0.322,
    "velocity": 0.475,
    "recency": 0.356,
    "originality": 0.45,
    "rarity": 0.865
   },
   "score": 43.9,
   "rank_prev": 36,
   "is_new_entry": false,
   "rank_change": -5,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 jhu-clsp/mmBERT-small"
   ],
   "pick_rank": null
  },
  {
   "id": "Contrastive-LM/CLM-v0.1-8B",
   "author": "Contrastive-LM",
   "author_fullname": null,
   "author_followers": null,
   "name": "CLM-v0.1-8B",
   "url": "https://huggingface.co/Contrastive-LM/CLM-v0.1-8B",
   "pipeline_tag": "text-ranking",
   "task_zh": "文字重排序",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "contrastive-lm",
   "likes": 746,
   "downloads": 4041,
   "trending_score": 107.0,
   "created_at": "2026-09-21T20:09:04.000Z",
   "last_modified": null,
   "age_days": 16.27,
   "like_velocity": 45.8,
   "params_b": 8.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3-8B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "clm",
    "contrastive-learning",
    "verifier",
    "reranker",
    "agents"
   ],
   "rank_trending": 42,
   "score_breakdown": {
    "momentum": 0.305,
    "velocity": 0.644,
    "recency": 0.313,
    "originality": 0.45,
    "rarity": 0.973
   },
   "score": 48.0,
   "rank_prev": 29,
   "is_new_entry": false,
   "rank_change": -13,
   "reasons": [
    "🧭 今日榜單少見的任務：文字重排序",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 Qwen/Qwen3-8B"
   ],
   "pick_rank": 12
  },
  {
   "id": "facebook/sam3",
   "author": "facebook",
   "author_fullname": null,
   "author_followers": null,
   "name": "sam3",
   "url": "https://huggingface.co/facebook/sam3",
   "pipeline_tag": "mask-generation",
   "task_zh": "遮罩生成",
   "task_group": "vision",
   "task_group_zh": "電腦視覺",
   "library": "transformers",
   "likes": 3861,
   "downloads": 2174262,
   "trending_score": 106.0,
   "created_at": "2025-11-07T05:17:48.000Z",
   "last_modified": null,
   "age_days": 334.89,
   "like_velocity": 11.5,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "sam3_video",
    "feature-extraction",
    "sam3"
   ],
   "rank_trending": 43,
   "score_breakdown": {
    "momentum": 0.288,
    "velocity": 0.102,
    "recency": 0.0,
    "originality": 1.0,
    "rarity": 0.973
   },
   "score": 37.4,
   "rank_prev": 46,
   "is_new_entry": false,
   "rank_change": 3,
   "reasons": [
    "🧭 今日榜單少見的任務：遮罩生成"
   ],
   "pick_rank": null
  },
  {
   "id": "pyannote/speaker-diarization-community-1",
   "author": "pyannote",
   "author_fullname": null,
   "author_followers": null,
   "name": "speaker-diarization-community-1",
   "url": "https://huggingface.co/pyannote/speaker-diarization-community-1",
   "pipeline_tag": "automatic-speech-recognition",
   "task_zh": "語音辨識（ASR）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": "pyannote-audio",
   "likes": 2614,
   "downloads": 5554891,
   "trending_score": 105.0,
   "created_at": "2025-04-15T21:31:35.000Z",
   "last_modified": null,
   "age_days": 540.22,
   "like_velocity": 4.8,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "cc-by-4.0",
   "permissive_license": true,
   "arxiv": [
    "2104.03603",
    "2111.14448",
    "2012.01477"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "pyannote",
    "pyannote-audio-pipeline",
    "audio",
    "voice",
    "speech",
    "speaker"
   ],
   "rank_trending": 44,
   "score_breakdown": {
    "momentum": 0.263,
    "velocity": 0.017,
    "recency": 0.0,
    "originality": 1.0,
    "rarity": 0.919
   },
   "score": 33.8,
   "rank_prev": 43,
   "is_new_entry": false,
   "rank_change": -1,
   "reasons": [
    "📄 附論文 arXiv:2104.03603",
    "✅ 寬鬆授權（cc-by-4.0）"
   ],
   "pick_rank": null
  },
  {
   "id": "ukisai/Swift-1.5-Qwen3.8-27B-GSQ-RCO-GGUF",
   "author": "ukisai",
   "author_fullname": null,
   "author_followers": null,
   "name": "Swift-1.5-Qwen3.8-27B-GSQ-RCO-GGUF",
   "url": "https://huggingface.co/ukisai/Swift-1.5-Qwen3.8-27B-GSQ-RCO-GGUF",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "gguf",
   "likes": 294,
   "downloads": 559452,
   "trending_score": 105.0,
   "created_at": "2026-09-24T13:13:45.000Z",
   "last_modified": null,
   "age_days": 13.56,
   "like_velocity": 21.7,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "ukisai/Swift-1.5-Qwen3.8-27b",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "llama.cpp",
    "qwen3_8",
    "gsq",
    "rco",
    "reasoning",
    "efficient-thinking"
   ],
   "rank_trending": 45,
   "score_breakdown": {
    "momentum": 0.263,
    "velocity": 0.271,
    "recency": 0.38,
    "originality": 0.0,
    "rarity": 0.946
   },
   "score": 31.1,
   "rank_prev": 45,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🧭 今日榜單少見的任務：文字生成",
    "📄 附論文 arXiv:2604.18556",
    "🔗 量化轉檔自 ukisai/Swift-1.5-Qwen3.8-27b"
   ],
   "pick_rank": null
  },
  {
   "id": "Lightricks/LTX-2.5-22b-IC-LoRA-Alpha-Gen",
   "author": "Lightricks",
   "author_fullname": null,
   "author_followers": null,
   "name": "LTX-2.5-22b-IC-LoRA-Alpha-Gen",
   "url": "https://huggingface.co/Lightricks/LTX-2.5-22b-IC-LoRA-Alpha-Gen",
   "pipeline_tag": "video-to-video",
   "task_zh": "影片轉換",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "ltx",
   "likes": 118,
   "downloads": 5255,
   "trending_score": 97.0,
   "created_at": "2026-09-28T20:01:47.000Z",
   "last_modified": null,
   "age_days": 9.28,
   "like_velocity": 12.7,
   "params_b": 22.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Lightricks/LTX-2.5",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "alpha-matte",
    "matting",
    "background-removal",
    "ic-lora",
    "ltx-2.5",
    "vfx"
   ],
   "rank_trending": 46,
   "score_breakdown": {
    "momentum": 0.229,
    "velocity": 0.153,
    "recency": 0.515,
    "originality": 0.35,
    "rarity": 0.946
   },
   "score": 34.3,
   "rank_prev": 53,
   "is_new_entry": false,
   "rank_change": 7,
   "reasons": [
    "📈 排名上升 7 名",
    "🧭 今日榜單少見的任務：影片轉換",
    "🔗 LoRA 掛載於 Lightricks/LTX-2.5"
   ],
   "pick_rank": null
  },
  {
   "id": "perplexity-ai/pplx-decider-v1-27b",
   "author": "perplexity-ai",
   "author_fullname": null,
   "author_followers": null,
   "name": "pplx-decider-v1-27b",
   "url": "https://huggingface.co/perplexity-ai/pplx-decider-v1-27b",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "pytorch",
   "likes": 103,
   "downloads": 1657,
   "trending_score": 97.0,
   "created_at": "2026-10-01T21:24:11.000Z",
   "last_modified": null,
   "age_days": 6.22,
   "like_velocity": 16.6,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5",
    "classification",
    "multimodal",
    "custom-code"
   ],
   "rank_trending": 47,
   "score_breakdown": {
    "momentum": 0.229,
    "velocity": 0.203,
    "recency": 0.641,
    "originality": 0.45,
    "rarity": 0.865
   },
   "score": 38.1,
   "rank_prev": 54,
   "is_new_entry": false,
   "rank_change": 7,
   "reasons": [
    "📈 排名上升 7 名",
    "⏱️ 6 天前才發布",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "audnai/penclaw-GLM-5.3-abliterated",
   "author": "audnai",
   "author_fullname": null,
   "author_followers": null,
   "name": "penclaw-GLM-5.3-abliterated",
   "url": "https://huggingface.co/audnai/penclaw-GLM-5.3-abliterated",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 341,
   "downloads": 1738,
   "trending_score": 96.0,
   "created_at": "2026-09-01T17:52:24.000Z",
   "last_modified": null,
   "age_days": 36.37,
   "like_velocity": 9.4,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "glm_moe_dsa",
    "abliterated",
    "uncensored",
    "warlock",
    "audn",
    "GLM-5.3"
   ],
   "rank_trending": 48,
   "score_breakdown": {
    "momentum": 0.186,
    "velocity": 0.085,
    "recency": 0.074,
    "originality": 1.0,
    "rarity": 0.946
   },
   "score": 34.2,
   "rank_prev": 42,
   "is_new_entry": false,
   "rank_change": -6,
   "reasons": [
    "🧭 今日榜單少見的任務：文字生成",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "autotrust/JEV-9B",
   "author": "autotrust",
   "author_fullname": null,
   "author_followers": null,
   "name": "JEV-9B",
   "url": "https://huggingface.co/autotrust/JEV-9B",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 136,
   "downloads": 320128,
   "trending_score": 96.0,
   "created_at": "2026-09-23T12:08:52.000Z",
   "last_modified": null,
   "age_days": 14.61,
   "like_velocity": 9.3,
   "params_b": 9.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3.5-9B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5_text",
    "text-generation",
    "system-one",
    "system-two",
    "blocks-of-experts",
    "typed-decisions"
   ],
   "rank_trending": 49,
   "score_breakdown": {
    "momentum": 0.186,
    "velocity": 0.068,
    "recency": 0.352,
    "originality": 0.45,
    "rarity": 0.865
   },
   "score": 28.9,
   "rank_prev": 50,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 Qwen/Qwen3.5-9B"
   ],
   "pick_rank": null
  },
  {
   "id": "LiquidAI/d1-3B",
   "author": "LiquidAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "d1-3B",
   "url": "https://huggingface.co/LiquidAI/d1-3B",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 96,
   "downloads": 15,
   "trending_score": 96.0,
   "created_at": "2026-10-05T09:55:28.000Z",
   "last_modified": null,
   "age_days": 2.7,
   "like_velocity": 35.6,
   "params_b": 3.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2511.23404"
   ],
   "languages": [
    "ar",
    "zh",
    "en",
    "fr",
    "de",
    "hi",
    "id",
    "it"
   ],
   "n_languages": 16,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "LiquidAI/LFM2.5-VL-3B",
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "lfm2_vl",
    "liquid",
    "lfm2.5",
    "edge",
    "decision",
    "classification"
   ],
   "rank_trending": 50,
   "score_breakdown": {
    "momentum": 0.186,
    "velocity": 0.508,
    "recency": 0.825,
    "originality": 0.45,
    "rarity": 0.757
   },
   "score": 45.9,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 3 天前才發布",
    "🪶 僅 3B 參數，適合筆電／裝置端",
    "📄 附論文 arXiv:2511.23404",
    "🌏 支援 16 種語言"
   ],
   "pick_rank": null
  },
  {
   "id": "JonathanColetti/Qwen3.8-27B-Uncensored-GGUF",
   "author": "JonathanColetti",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-Uncensored-GGUF",
   "url": "https://huggingface.co/JonathanColetti/Qwen3.8-27B-Uncensored-GGUF",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "llama.cpp",
   "likes": 1481,
   "downloads": 2308814,
   "trending_score": 95.0,
   "created_at": "2026-08-14T03:43:36.000Z",
   "last_modified": null,
   "age_days": 54.96,
   "like_velocity": 26.9,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "uncensored",
    "qwen3.8",
    "mtp",
    "speculative-decoding",
    "imatrix"
   ],
   "rank_trending": 51,
   "score_breakdown": {
    "momentum": 0.153,
    "velocity": 0.364,
    "recency": 0.02,
    "originality": 0.0,
    "rarity": 0.946
   },
   "score": 24.2,
   "rank_prev": 49,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "🧭 今日榜單少見的任務：文字生成",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "huihui-ai/Huihui-Qwen3.8-27B-abliterated-GGUF",
   "author": "huihui-ai",
   "author_fullname": null,
   "author_followers": null,
   "name": "Huihui-Qwen3.8-27B-abliterated-GGUF",
   "url": "https://huggingface.co/huihui-ai/Huihui-Qwen3.8-27B-abliterated-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 1209,
   "downloads": 2115658,
   "trending_score": 90.0,
   "created_at": "2026-08-16T13:18:55.000Z",
   "last_modified": null,
   "age_days": 52.56,
   "like_velocity": 23.0,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": true,
   "on_device": true,
   "tags": [
    "gguf",
    "abliterated",
    "uncensored",
    "huihui",
    "qwen3",
    "unsloth"
   ],
   "rank_trending": 52,
   "score_breakdown": {
    "momentum": 0.136,
    "velocity": 0.314,
    "recency": 0.023,
    "originality": 0.0,
    "rarity": 0.757
   },
   "score": 20.5,
   "rank_prev": 52,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "📱 強調裝置端推論",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "zai-org/GLM-5.3",
   "author": "zai-org",
   "author_fullname": null,
   "author_followers": null,
   "name": "GLM-5.3",
   "url": "https://huggingface.co/zai-org/GLM-5.3",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 2132,
   "downloads": 1507787,
   "trending_score": 89.0,
   "created_at": "2026-08-25T06:42:50.000Z",
   "last_modified": null,
   "age_days": 43.83,
   "like_velocity": 48.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2602.15763"
   ],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "glm_moe_dsa",
    "fp8"
   ],
   "rank_trending": 53,
   "score_breakdown": {
    "momentum": 0.119,
    "velocity": 0.661,
    "recency": 0.044,
    "originality": 1.0,
    "rarity": 0.946
   },
   "score": 45.8,
   "rank_prev": 44,
   "is_new_entry": false,
   "rank_change": -9,
   "reasons": [
    "🧭 今日榜單少見的任務：文字生成",
    "📄 附論文 arXiv:2602.15763"
   ],
   "pick_rank": null
  },
  {
   "id": "HauhauCS/Qwen3.8-27B-Uncensored-HauhauCS-Aggressive-MTP-GGUF",
   "author": "HauhauCS",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-Uncensored-HauhauCS-Aggressive-MTP-GGUF",
   "url": "https://huggingface.co/HauhauCS/Qwen3.8-27B-Uncensored-HauhauCS-Aggressive-MTP-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": null,
   "likes": 1674,
   "downloads": 2062093,
   "trending_score": 88.0,
   "created_at": "2026-08-17T15:15:19.000Z",
   "last_modified": null,
   "age_days": 51.48,
   "like_velocity": 32.5,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "uncensored",
    "qwen3.8",
    "multimodal",
    "vision",
    "mtp"
   ],
   "rank_trending": 54,
   "score_breakdown": {
    "momentum": 0.093,
    "velocity": 0.492,
    "recency": 0.025,
    "originality": 0.0,
    "rarity": 0.757
   },
   "score": 23.5,
   "rank_prev": 57,
   "is_new_entry": false,
   "rank_change": 3,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "zai-org/GLM-5.3-Flash",
   "author": "zai-org",
   "author_fullname": null,
   "author_followers": null,
   "name": "GLM-5.3-Flash",
   "url": "https://huggingface.co/zai-org/GLM-5.3-Flash",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 2743,
   "downloads": 6160780,
   "trending_score": 88.0,
   "created_at": "2026-08-25T06:43:14.000Z",
   "last_modified": null,
   "age_days": 43.83,
   "like_velocity": 62.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [
    "2602.15763"
   ],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "glm5_next",
    "fp8"
   ],
   "rank_trending": 55,
   "score_breakdown": {
    "momentum": 0.093,
    "velocity": 0.712,
    "recency": 0.044,
    "originality": 1.0,
    "rarity": 0.757
   },
   "score": 44.3,
   "rank_prev": 51,
   "is_new_entry": false,
   "rank_change": -4,
   "reasons": [
    "📄 附論文 arXiv:2602.15763",
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": null
  },
  {
   "id": "speach1sdef178/MiniMax-H3-X2-Detail-VAE",
   "author": "speach1sdef178",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiniMax-H3-X2-Detail-VAE",
   "url": "https://huggingface.co/speach1sdef178/MiniMax-H3-X2-Detail-VAE",
   "pipeline_tag": "image-to-video",
   "task_zh": "圖生影片",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "minimax-h3",
   "likes": 87,
   "downloads": 12760,
   "trending_score": 85.0,
   "created_at": "2026-09-30T19:59:27.000Z",
   "last_modified": null,
   "age_days": 7.28,
   "like_velocity": 12.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "MiniMaxAI/MiniMax-H3",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "minimax",
    "comfyui",
    "vae",
    "video-vae",
    "video-generation",
    "x2-upscaling"
   ],
   "rank_trending": 56,
   "score_breakdown": {
    "momentum": 0.068,
    "velocity": 0.127,
    "recency": 0.595,
    "originality": 0.45,
    "rarity": 0.919
   },
   "score": 30.4,
   "rank_prev": 60,
   "is_new_entry": false,
   "rank_change": 4,
   "reasons": [
    "🔗 微調自 MiniMaxAI/MiniMax-H3"
   ],
   "pick_rank": null
  },
  {
   "id": "Comfy-Org/MiniMax-H3",
   "author": "Comfy-Org",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiniMax-H3",
   "url": "https://huggingface.co/Comfy-Org/MiniMax-H3",
   "pipeline_tag": null,
   "task_zh": "未標註任務",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": "diffusion-single-file",
   "likes": 2167,
   "downloads": 23394103,
   "trending_score": 83.0,
   "created_at": "2026-07-30T22:36:12.000Z",
   "last_modified": null,
   "age_days": 69.17,
   "like_velocity": 31.3,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "MiniMaxAI/MiniMax-H3",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "comfyui"
   ],
   "rank_trending": 57,
   "score_breakdown": {
    "momentum": 0.051,
    "velocity": 0.458,
    "recency": 0.007,
    "originality": 0.45,
    "rarity": 0.3
   },
   "score": 23.1,
   "rank_prev": 58,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🔗 微調自 MiniMaxAI/MiniMax-H3"
   ],
   "pick_rank": null
  },
  {
   "id": "Comfy-Org/Qwen-Image-2.1",
   "author": "Comfy-Org",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1",
   "url": "https://huggingface.co/Comfy-Org/Qwen-Image-2.1",
   "pipeline_tag": null,
   "task_zh": "未標註任務",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": "diffusion-single-file",
   "likes": 978,
   "downloads": 7197052,
   "trending_score": 82.0,
   "created_at": "2026-09-15T19:41:09.000Z",
   "last_modified": null,
   "age_days": 22.29,
   "like_velocity": 43.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "comfyui"
   ],
   "rank_trending": 58,
   "score_breakdown": {
    "momentum": 0.025,
    "velocity": 0.627,
    "recency": 0.203,
    "originality": 0.45,
    "rarity": 0.3
   },
   "score": 29.4,
   "rank_prev": 59,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🔗 微調自 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "shhivv/taiga-s1",
   "author": "shhivv",
   "author_fullname": null,
   "author_followers": null,
   "name": "taiga-s1",
   "url": "https://huggingface.co/shhivv/taiga-s1",
   "pipeline_tag": "other",
   "task_zh": "other",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": "pytorch",
   "likes": 127,
   "downloads": 505,
   "trending_score": 82.0,
   "created_at": "2026-09-27T13:34:07.000Z",
   "last_modified": null,
   "age_days": 10.55,
   "like_velocity": 12.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [
    "2305.16843",
    "2405.20671"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "cad",
    "freecad",
    "agent",
    "imitation-learning",
    "length-generalization"
   ],
   "rank_trending": 59,
   "score_breakdown": {
    "momentum": 0.025,
    "velocity": 0.127,
    "recency": 0.471,
    "originality": 1.0,
    "rarity": 0.973
   },
   "score": 35.9,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "🧭 今日榜單少見的任務：other",
    "📄 附論文 arXiv:2305.16843",
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": null
  },
  {
   "id": "moondream/parakeet-redux",
   "author": "moondream",
   "author_fullname": null,
   "author_followers": null,
   "name": "parakeet-redux",
   "url": "https://huggingface.co/moondream/parakeet-redux",
   "pipeline_tag": "automatic-speech-recognition",
   "task_zh": "語音辨識（ASR）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": null,
   "likes": 254,
   "downloads": 12689,
   "trending_score": 79.0,
   "created_at": "2026-09-18T11:02:15.000Z",
   "last_modified": null,
   "age_days": 19.65,
   "like_velocity": 12.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "cc-by-4.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "de",
    "fr",
    "es",
    "it",
    "pt",
    "ru",
    "uk"
   ],
   "n_languages": 25,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "parakeet_tdt",
    "ternary",
    "parakeet",
    "tdt",
    "speech-recognition",
    "cpu"
   ],
   "rank_trending": 60,
   "score_breakdown": {
    "momentum": 0.0,
    "velocity": 0.169,
    "recency": 0.246,
    "originality": 1.0,
    "rarity": 0.919
   },
   "score": 32.1,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "📱 強調裝置端推論",
    "🌏 支援 25 種語言",
    "✅ 寬鬆授權（cc-by-4.0）"
   ],
   "pick_rank": null
  }
 ]
};
