/* 由 fetch_hf.py 自動產生，請勿手動編輯 */
window.DAILY_MODELS = {
 "schema_version": 1,
 "generator": "fetch_hf.py 1.0.0",
 "snapshot_date": "2026-09-29",
 "generated_at": "2026-09-29T05:47:16+00:00",
 "generated_at_local": "2026-09-29 05:47",
 "source": {
  "name": "Hugging Face Hub API",
  "endpoint": "https://huggingface.co/api/models?sort=trendingScore&limit=60",
  "enrichment": null
 },
 "previous_snapshot": "2026-09-28",
 "method": {
  "weights": {
   "momentum": 0.35,
   "velocity": 0.25,
   "recency": 0.15,
   "originality": 0.15,
   "rarity": 0.1
  },
  "recency_half_life_days": 14.0,
  "originality": {
   "original": 1.0,
   "finetune": 0.45,
   "derived": 0.4,
   "merge": 0.35,
   "adapter": 0.35,
   "quantized": 0.0
  },
  "pick_rules": "排除量化轉檔與移除安全對齊版本；依分數貪婪挑選，同作者 ≤2、同任務 ≤3，不足時放寬"
 },
 "stats": {
  "fetched": 60,
  "models": 60,
  "picks": 12,
  "derivatives": {
   "original": 23,
   "quantized": 19,
   "finetune": 12,
   "adapter": 6
  },
  "quantized_hidden_by_default": 19,
  "task_counts": {
   "圖文理解（VLM）": 8,
   "文字生成": 7,
   "文字分類": 5,
   "語音辨識（ASR）": 4,
   "文生圖": 4,
   "圖生影片": 2,
   "未標註任務": 2,
   "文字重排序": 1,
   "詞元標註 / NER": 1,
   "圖生圖 / 影像編輯": 1,
   "影片轉換": 1,
   "圖文生影片": 1,
   "遮罩生成": 1,
   "機器人": 1,
   "零樣本文字分類": 1,
   "image-text-to-image": 1
  },
  "group_counts": {
   "語言": 15,
   "影像 / 影音生成": 9,
   "多模態": 8,
   "語音 / 音訊": 4,
   "其他": 3,
   "電腦視覺": 1,
   "決策 / 科學": 1
  },
  "elapsed_sec": 0.14
 },
 "picks": [
  "convaiinnovations/laya",
  "Edge0/Audio8-ASR-Infinite",
  "Qwen/Qwen-Image-2.1",
  "XingChen-AGI/Xing4.0-29B-A4B",
  "XiaomiMiMo/MiMo-V2.6-Pro-RL",
  "Qwen/Qwen3.8-27B",
  "TaichuAI/ZDTaichu5.0-9B",
  "Contrastive-LM/CLM-v0.1-8B",
  "XiaomiMiMo/MiMo-V2.6-Flash-RL",
  "Lightricks/LTX-2.5",
  "deepseek-ai/DeepSeek-V4.1-Flash",
  "Viggle/Qwen-Image-2.1-viggle-turbo"
 ],
 "models": [
  {
   "id": "convaiinnovations/laya",
   "author": "convaiinnovations",
   "author_fullname": null,
   "author_followers": null,
   "name": "laya",
   "url": "https://huggingface.co/convaiinnovations/laya",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 4352,
   "downloads": 0,
   "trending_score": 2227.0,
   "created_at": "2026-09-18T05:05:55.000Z",
   "last_modified": null,
   "age_days": 11.03,
   "like_velocity": 394.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "laya",
    "system-one",
    "calibrated-decisions",
    "rlcd",
    "classification",
    "routing"
   ],
   "rank_trending": 1,
   "score_breakdown": {
    "momentum": 1.0,
    "velocity": 1.0,
    "recency": 0.455,
    "originality": 1.0,
    "rarity": 0.878
   },
   "score": 90.6,
   "rank_prev": 1,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🔥 平均每天 +395 讚",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 1
  },
  {
   "id": "abenzerps/Qwen-Image-2.1-Uncensored-GGUF",
   "author": "abenzerps",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1-Uncensored-GGUF",
   "url": "https://huggingface.co/abenzerps/Qwen-Image-2.1-Uncensored-GGUF",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "gguf",
   "likes": 2296,
   "downloads": 1062921,
   "trending_score": 1321.0,
   "created_at": "2026-09-20T15:51:13.000Z",
   "last_modified": null,
   "age_days": 8.58,
   "like_velocity": 267.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen",
    "image-generation",
    "comfyui",
    "comfyui-gguf"
   ],
   "rank_trending": 2,
   "score_breakdown": {
    "momentum": 0.983,
    "velocity": 0.966,
    "recency": 0.542,
    "originality": 0.0,
    "rarity": 0.902
   },
   "score": 75.7,
   "rank_prev": 2,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🔥 平均每天 +268 讚",
    "🔗 量化轉檔自 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "Edge0/Audio8-ASR-Infinite",
   "author": "Edge0",
   "author_fullname": null,
   "author_followers": null,
   "name": "Audio8-ASR-Infinite",
   "url": "https://huggingface.co/Edge0/Audio8-ASR-Infinite",
   "pipeline_tag": "automatic-speech-recognition",
   "task_zh": "語音辨識（ASR）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": "transformers",
   "likes": 1447,
   "downloads": 19963,
   "trending_score": 1273.0,
   "created_at": "2026-09-21T15:03:21.000Z",
   "last_modified": null,
   "age_days": 7.61,
   "like_velocity": 190.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "zh",
    "en"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "audio8_asr_infinite",
    "text-generation",
    "streaming",
    "realtime",
    "speech-recognition",
    "audio"
   ],
   "rank_trending": 3,
   "score_breakdown": {
    "momentum": 0.966,
    "velocity": 0.932,
    "recency": 0.581,
    "originality": 1.0,
    "rarity": 0.902
   },
   "score": 89.9,
   "rank_prev": 4,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🔥 平均每天 +190 讚",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 2
  },
  {
   "id": "Qwen/Qwen-Image-2.1",
   "author": "Qwen",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1",
   "url": "https://huggingface.co/Qwen/Qwen-Image-2.1",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 2603,
   "downloads": 58693,
   "trending_score": 912.0,
   "created_at": "2026-09-14T03:47:26.000Z",
   "last_modified": null,
   "age_days": 15.08,
   "like_velocity": 172.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen",
    "image-generation",
    "image-editing",
    "rgba"
   ],
   "rank_trending": 4,
   "score_breakdown": {
    "momentum": 0.949,
    "velocity": 0.898,
    "recency": 0.341,
    "originality": 1.0,
    "rarity": 0.902
   },
   "score": 84.8,
   "rank_prev": 3,
   "is_new_entry": false,
   "rank_change": -1,
   "reasons": [
    "🔥 平均每天 +173 讚"
   ],
   "pick_rank": 3
  },
  {
   "id": "XingChen-AGI/TeleOCR",
   "author": "XingChen-AGI",
   "author_fullname": null,
   "author_followers": null,
   "name": "TeleOCR",
   "url": "https://huggingface.co/XingChen-AGI/TeleOCR",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 822,
   "downloads": 27904,
   "trending_score": 702.0,
   "created_at": "2026-08-14T06:15:03.000Z",
   "last_modified": null,
   "age_days": 45.98,
   "like_velocity": 17.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2608.12898"
   ],
   "languages": [
    "zh",
    "en"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen2_5_vl",
    "ocr",
    "document-parsing",
    "multimodal"
   ],
   "rank_trending": 5,
   "score_breakdown": {
    "momentum": 0.932,
    "velocity": 0.237,
    "recency": 0.037,
    "originality": 1.0,
    "rarity": 0.805
   },
   "score": 62.2,
   "rank_prev": 9,
   "is_new_entry": false,
   "rank_change": 4,
   "reasons": [
    "📄 附論文 arXiv:2608.12898",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": null
  },
  {
   "id": "XingChen-AGI/Xing4.0-29B-A4B",
   "author": "XingChen-AGI",
   "author_fullname": null,
   "author_followers": null,
   "name": "Xing4.0-29B-A4B",
   "url": "https://huggingface.co/XingChen-AGI/Xing4.0-29B-A4B",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 1802,
   "downloads": 45834,
   "trending_score": 624.0,
   "created_at": "2026-09-16T06:44:40.000Z",
   "last_modified": null,
   "age_days": 12.96,
   "like_velocity": 139.0,
   "params_b": 29.0,
   "active_params_b": 4.0,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2512.24157",
    "2507.18013"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "xing4_0"
   ],
   "rank_trending": 6,
   "score_breakdown": {
    "momentum": 0.915,
    "velocity": 0.864,
    "recency": 0.396,
    "originality": 1.0,
    "rarity": 0.829
   },
   "score": 82.9,
   "rank_prev": 5,
   "is_new_entry": false,
   "rank_change": -1,
   "reasons": [
    "🔥 平均每天 +139 讚",
    "🧩 MoE 混合專家架構（啟用 4B）",
    "📄 附論文 arXiv:2512.24157",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 4
  },
  {
   "id": "Contrastive-LM/CLM-v0.1-8B",
   "author": "Contrastive-LM",
   "author_fullname": null,
   "author_followers": null,
   "name": "CLM-v0.1-8B",
   "url": "https://huggingface.co/Contrastive-LM/CLM-v0.1-8B",
   "pipeline_tag": "text-ranking",
   "task_zh": "文字重排序",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "contrastive-lm",
   "likes": 492,
   "downloads": 1271,
   "trending_score": 485.0,
   "created_at": "2026-09-21T20:09:04.000Z",
   "last_modified": null,
   "age_days": 7.4,
   "like_velocity": 66.5,
   "params_b": 8.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3-8B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "clm",
    "contrastive-learning",
    "verifier",
    "reranker",
    "agents"
   ],
   "rank_trending": 7,
   "score_breakdown": {
    "momentum": 0.898,
    "velocity": 0.712,
    "recency": 0.589,
    "originality": 0.45,
    "rarity": 0.976
   },
   "score": 74.6,
   "rank_prev": 14,
   "is_new_entry": false,
   "rank_change": 7,
   "reasons": [
    "📈 排名上升 7 名",
    "🧭 今日榜單少見的任務：文字重排序",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 Qwen/Qwen3-8B"
   ],
   "pick_rank": 8
  },
  {
   "id": "TaichuAI/ZDTaichu5.0-9B",
   "author": "TaichuAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "ZDTaichu5.0-9B",
   "url": "https://huggingface.co/TaichuAI/ZDTaichu5.0-9B",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": null,
   "likes": 1728,
   "downloads": 11738,
   "trending_score": 475.0,
   "created_at": "2026-09-04T02:55:48.000Z",
   "last_modified": null,
   "age_days": 25.12,
   "like_velocity": 68.8,
   "params_b": 9.0,
   "active_params_b": null,
   "is_moe": false,
   "license": null,
   "permissive_license": false,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "zdtaichu5_0",
    "multimodal",
    "vision-language-model",
    "spatial-reasoning",
    "agent",
    "video-understanding"
   ],
   "rank_trending": 8,
   "score_breakdown": {
    "momentum": 0.881,
    "velocity": 0.746,
    "recency": 0.166,
    "originality": 1.0,
    "rarity": 0.805
   },
   "score": 75.0,
   "rank_prev": 12,
   "is_new_entry": false,
   "rank_change": 4,
   "reasons": [],
   "pick_rank": 7
  },
  {
   "id": "nvidia/Nemotron-3-Diarization",
   "author": "nvidia",
   "author_fullname": null,
   "author_followers": null,
   "name": "Nemotron-3-Diarization",
   "url": "https://huggingface.co/nvidia/Nemotron-3-Diarization",
   "pipeline_tag": "voice-activity-detection",
   "task_zh": "語音活動偵測",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": "nemo",
   "likes": 471,
   "downloads": 26428,
   "trending_score": 457.0,
   "created_at": "2026-09-01T13:16:57.000Z",
   "last_modified": null,
   "age_days": 27.69,
   "like_velocity": 17.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "openmdw-1.1",
   "permissive_license": false,
   "arxiv": [
    "2409.06656",
    "2507.18446",
    "2605.15442"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "nemotron3_diarization",
    "audio-frame-classification",
    "speaker-diarization",
    "streaming-sortformer",
    "speaker-tagging"
   ],
   "rank_trending": 9,
   "score_breakdown": {
    "momentum": 0.864,
    "velocity": 0.22,
    "recency": 0.138,
    "originality": 0.0,
    "rarity": 1.0
   },
   "score": 47.8,
   "rank_prev": 16,
   "is_new_entry": false,
   "rank_change": 7,
   "reasons": [
    "📈 排名上升 7 名",
    "🧭 今日榜單少見的任務：語音活動偵測",
    "📄 附論文 arXiv:2409.06656"
   ],
   "pick_rank": null
  },
  {
   "id": "prism-ml/Ternary-Bonsai-2-27B-gguf",
   "author": "prism-ml",
   "author_fullname": null,
   "author_followers": null,
   "name": "Ternary-Bonsai-2-27B-gguf",
   "url": "https://huggingface.co/prism-ml/Ternary-Bonsai-2-27B-gguf",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "llama.cpp",
   "likes": 2238,
   "downloads": 3457124,
   "trending_score": 437.0,
   "created_at": "2026-09-16T23:40:56.000Z",
   "last_modified": null,
   "age_days": 12.25,
   "like_velocity": 182.6,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "gguf",
    "ternary",
    "2-bit",
    "llama-cpp",
    "cuda",
    "metal"
   ],
   "rank_trending": 10,
   "score_breakdown": {
    "momentum": 0.847,
    "velocity": 0.915,
    "recency": 0.417,
    "originality": 0.0,
    "rarity": 0.829
   },
   "score": 67.1,
   "rank_prev": 7,
   "is_new_entry": false,
   "rank_change": -3,
   "reasons": [
    "🔥 平均每天 +183 讚",
    "📱 強調裝置端推論",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "Qwen/Qwen3.8-27B",
   "author": "Qwen",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B",
   "url": "https://huggingface.co/Qwen/Qwen3.8-27B",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 16509,
   "downloads": 6844348,
   "trending_score": 382.0,
   "created_at": "2026-08-05T08:22:59.000Z",
   "last_modified": null,
   "age_days": 54.89,
   "like_velocity": 300.8,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5"
   ],
   "rank_trending": 11,
   "score_breakdown": {
    "momentum": 0.831,
    "velocity": 0.983,
    "recency": 0.02,
    "originality": 1.0,
    "rarity": 0.805
   },
   "score": 77.0,
   "rank_prev": 15,
   "is_new_entry": false,
   "rank_change": 4,
   "reasons": [
    "🔥 平均每天 +301 讚",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 6
  },
  {
   "id": "Viggle/Qwen-Image-2.1-viggle-turbo",
   "author": "Viggle",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1-viggle-turbo",
   "url": "https://huggingface.co/Viggle/Qwen-Image-2.1-viggle-turbo",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 392,
   "downloads": 175907,
   "trending_score": 379.0,
   "created_at": "2026-09-22T04:14:56.000Z",
   "last_modified": null,
   "age_days": 7.06,
   "like_velocity": 55.5,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "lora",
    "image-to-image",
    "image-editing",
    "distillation",
    "dmd",
    "turbo"
   ],
   "rank_trending": 12,
   "score_breakdown": {
    "momentum": 0.814,
    "velocity": 0.644,
    "recency": 0.604,
    "originality": 0.35,
    "rarity": 0.902
   },
   "score": 67.9,
   "rank_prev": 18,
   "is_new_entry": false,
   "rank_change": 6,
   "reasons": [
    "📈 排名上升 6 名",
    "🔗 LoRA 掛載於 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": 12
  },
  {
   "id": "XiaomiMiMo/MiMo-V2.6-Distill-Qwen-9B",
   "author": "XiaomiMiMo",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiMo-V2.6-Distill-Qwen-9B",
   "url": "https://huggingface.co/XiaomiMiMo/MiMo-V2.6-Distill-Qwen-9B",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 554,
   "downloads": 9994,
   "trending_score": 366.0,
   "created_at": "2026-09-21T18:18:40.000Z",
   "last_modified": null,
   "age_days": 7.48,
   "like_velocity": 74.1,
   "params_b": 9.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3.5-9B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5",
    "mimo_v2",
    "agentic",
    "distillation",
    "supervised-fine-tuning",
    "code"
   ],
   "rank_trending": 13,
   "score_breakdown": {
    "momentum": 0.797,
    "velocity": 0.763,
    "recency": 0.586,
    "originality": 0.45,
    "rarity": 0.805
   },
   "score": 70.5,
   "rank_prev": 10,
   "is_new_entry": false,
   "rank_change": -3,
   "reasons": [
    "✅ 寬鬆授權（mit）",
    "🔗 微調自 Qwen/Qwen3.5-9B"
   ],
   "pick_rank": null
  },
  {
   "id": "XiaomiMiMo/MiMo-V2.6-Pro-RL",
   "author": "XiaomiMiMo",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiMo-V2.6-Pro-RL",
   "url": "https://huggingface.co/XiaomiMiMo/MiMo-V2.6-Pro-RL",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 587,
   "downloads": 76518,
   "trending_score": 358.0,
   "created_at": "2026-09-21T15:39:33.000Z",
   "last_modified": null,
   "age_days": 7.59,
   "like_velocity": 77.4,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "mimo_v2",
    "multimodal",
    "vision-language",
    "audio",
    "agent",
    "video-understanding"
   ],
   "rank_trending": 14,
   "score_breakdown": {
    "momentum": 0.78,
    "velocity": 0.78,
    "recency": 0.582,
    "originality": 1.0,
    "rarity": 0.829
   },
   "score": 78.8,
   "rank_prev": 8,
   "is_new_entry": false,
   "rank_change": -6,
   "reasons": [
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": 5
  },
  {
   "id": "Altworld/Hemmingway-1",
   "author": "Altworld",
   "author_fullname": null,
   "author_followers": null,
   "name": "Hemmingway-1",
   "url": "https://huggingface.co/Altworld/Hemmingway-1",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 765,
   "downloads": 7478,
   "trending_score": 348.0,
   "created_at": "2026-09-20T12:10:31.000Z",
   "last_modified": null,
   "age_days": 8.73,
   "like_velocity": 87.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "cc-by-nc-4.0",
   "permissive_license": false,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5_text",
    "qwen3.8",
    "chat",
    "creative-writing",
    "altworld"
   ],
   "rank_trending": 15,
   "score_breakdown": {
    "momentum": 0.763,
    "velocity": 0.814,
    "recency": 0.536,
    "originality": 0.45,
    "rarity": 0.829
   },
   "score": 70.1,
   "rank_prev": 6,
   "is_new_entry": false,
   "rank_change": -9,
   "reasons": [
    "🔥 平均每天 +88 讚",
    "🔗 微調自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "Lightricks/LTX-2.5",
   "author": "Lightricks",
   "author_fullname": null,
   "author_followers": null,
   "name": "LTX-2.5",
   "url": "https://huggingface.co/Lightricks/LTX-2.5",
   "pipeline_tag": "image-to-video",
   "task_zh": "圖生影片",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusion-single-file",
   "likes": 5450,
   "downloads": 1595377,
   "trending_score": 342.0,
   "created_at": "2026-07-23T07:55:24.000Z",
   "last_modified": null,
   "age_days": 67.91,
   "like_velocity": 80.3,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2601.03233"
   ],
   "languages": [
    "en",
    "de",
    "es",
    "fr",
    "ja",
    "ko",
    "zh",
    "it"
   ],
   "n_languages": 9,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "text-to-video",
    "video-to-video",
    "image-text-to-video",
    "audio-to-video",
    "text-to-audio",
    "video-to-audio"
   ],
   "rank_trending": 16,
   "score_breakdown": {
    "momentum": 0.746,
    "velocity": 0.797,
    "recency": 0.008,
    "originality": 1.0,
    "rarity": 0.951
   },
   "score": 70.6,
   "rank_prev": 17,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🔥 平均每天 +80 讚",
    "🧭 今日榜單少見的任務：圖生影片",
    "📄 附論文 arXiv:2601.03233"
   ],
   "pick_rank": 10
  },
  {
   "id": "Comfy-Org/Qwen-Image-2.1",
   "author": "Comfy-Org",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1",
   "url": "https://huggingface.co/Comfy-Org/Qwen-Image-2.1",
   "pipeline_tag": null,
   "task_zh": "未標註任務",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": "diffusion-single-file",
   "likes": 831,
   "downloads": 4351753,
   "trending_score": 325.0,
   "created_at": "2026-09-15T19:41:09.000Z",
   "last_modified": null,
   "age_days": 13.42,
   "like_velocity": 61.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "comfyui"
   ],
   "rank_trending": 17,
   "score_breakdown": {
    "momentum": 0.72,
    "velocity": 0.695,
    "recency": 0.383,
    "originality": 0.45,
    "rarity": 0.3
   },
   "score": 58.1,
   "rank_prev": 13,
   "is_new_entry": false,
   "rank_change": -4,
   "reasons": [
    "🔗 微調自 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "inclusionAI/Ming-Image-0.1-Design",
   "author": "inclusionAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "Ming-Image-0.1-Design",
   "url": "https://huggingface.co/inclusionAI/Ming-Image-0.1-Design",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "custom",
   "likes": 330,
   "downloads": 0,
   "trending_score": 325.0,
   "created_at": "2026-09-17T07:17:31.000Z",
   "last_modified": null,
   "age_days": 11.94,
   "like_velocity": 27.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "diffusers",
    "image-generation",
    "graphic-design",
    "text-rendering",
    "rgba"
   ],
   "rank_trending": 18,
   "score_breakdown": {
    "momentum": 0.72,
    "velocity": 0.356,
    "recency": 0.426,
    "originality": 1.0,
    "rarity": 0.902
   },
   "score": 64.5,
   "rank_prev": 19,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": null
  },
  {
   "id": "akhilaaa3/Jev-Omni",
   "author": "akhilaaa3",
   "author_fullname": null,
   "author_followers": null,
   "name": "Jev-Omni",
   "url": "https://huggingface.co/akhilaaa3/Jev-Omni",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 299,
   "downloads": 577,
   "trending_score": 290.0,
   "created_at": "2026-09-20T21:43:20.000Z",
   "last_modified": null,
   "age_days": 8.34,
   "like_velocity": 35.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "google/gemma-4-12B-it",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gemma4_unified",
    "image-text-to-text",
    "multimodal",
    "merged"
   ],
   "rank_trending": 19,
   "score_breakdown": {
    "momentum": 0.695,
    "velocity": 0.475,
    "recency": 0.551,
    "originality": 0.45,
    "rarity": 0.878
   },
   "score": 60.0,
   "rank_prev": 22,
   "is_new_entry": false,
   "rank_change": 3,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 google/gemma-4-12B-it"
   ],
   "pick_rank": null
  },
  {
   "id": "pottokao/Qwen-Image-2.1-Text-Encoder-Heretic-GGUF",
   "author": "pottokao",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1-Text-Encoder-Heretic-GGUF",
   "url": "https://huggingface.co/pottokao/Qwen-Image-2.1-Text-Encoder-Heretic-GGUF",
   "pipeline_tag": null,
   "task_zh": "未標註任務",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": null,
   "likes": 316,
   "downloads": 158806,
   "trending_score": 281.0,
   "created_at": "2026-09-20T17:08:40.000Z",
   "last_modified": null,
   "age_days": 8.53,
   "like_velocity": 37.1,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "pottokao/Qwen-Image-2.1-Text-Encoder-Heretic",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "quantized",
    "fp8",
    "comfyui",
    "qwen-image",
    "abliterated"
   ],
   "rank_trending": 20,
   "score_breakdown": {
    "momentum": 0.669,
    "velocity": 0.492,
    "recency": 0.544,
    "originality": 0.0,
    "rarity": 0.3
   },
   "score": 46.9,
   "rank_prev": 20,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 pottokao/Qwen-Image-2.1-Text-Encoder-Heretic",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "unsloth/Qwen-Image-2.1-GGUF",
   "author": "unsloth",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1-GGUF",
   "url": "https://huggingface.co/unsloth/Qwen-Image-2.1-GGUF",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": null,
   "likes": 290,
   "downloads": 220231,
   "trending_score": 281.0,
   "created_at": "2026-09-21T13:04:48.000Z",
   "last_modified": null,
   "age_days": 7.7,
   "like_velocity": 37.7,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "quantized",
    "unsloth",
    "qwen",
    "image-generation"
   ],
   "rank_trending": 21,
   "score_breakdown": {
    "momentum": 0.669,
    "velocity": 0.508,
    "recency": 0.577,
    "originality": 0.0,
    "rarity": 0.902
   },
   "score": 53.8,
   "rank_prev": 24,
   "is_new_entry": false,
   "rank_change": 3,
   "reasons": [
    "🔗 量化轉檔自 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "XiaomiMiMo/MiMo-V2.6-Flash-RL",
   "author": "XiaomiMiMo",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiMo-V2.6-Flash-RL",
   "url": "https://huggingface.co/XiaomiMiMo/MiMo-V2.6-Flash-RL",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 513,
   "downloads": 28842,
   "trending_score": 272.0,
   "created_at": "2026-09-21T15:39:51.000Z",
   "last_modified": null,
   "age_days": 7.59,
   "like_velocity": 67.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "mimo_v2",
    "multimodal",
    "vision-language",
    "audio",
    "agent",
    "video-understanding"
   ],
   "rank_trending": 22,
   "score_breakdown": {
    "momentum": 0.644,
    "velocity": 0.729,
    "recency": 0.582,
    "originality": 1.0,
    "rarity": 0.829
   },
   "score": 72.8,
   "rank_prev": 11,
   "is_new_entry": false,
   "rank_change": -11,
   "reasons": [
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": 9
  },
  {
   "id": "SupersonicLabs/Julia-1",
   "author": "SupersonicLabs",
   "author_fullname": null,
   "author_followers": null,
   "name": "Julia-1",
   "url": "https://huggingface.co/SupersonicLabs/Julia-1",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "pytorch",
   "likes": 268,
   "downloads": 1006,
   "trending_score": 261.0,
   "created_at": "2026-09-23T15:29:46.000Z",
   "last_modified": null,
   "age_days": 5.6,
   "like_velocity": 47.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "jhu-clsp/mmBERT-small",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "decision-model",
    "multilingual",
    "routing"
   ],
   "rank_trending": 23,
   "score_breakdown": {
    "momentum": 0.627,
    "velocity": 0.61,
    "recency": 0.67,
    "originality": 0.45,
    "rarity": 0.878
   },
   "score": 62.8,
   "rank_prev": 31,
   "is_new_entry": false,
   "rank_change": 8,
   "reasons": [
    "📈 排名上升 8 名",
    "⏱️ 6 天前才發布",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 jhu-clsp/mmBERT-small"
   ],
   "pick_rank": null
  },
  {
   "id": "apple/LensVLM-9B",
   "author": "apple",
   "author_fullname": null,
   "author_followers": null,
   "name": "LensVLM-9B",
   "url": "https://huggingface.co/apple/LensVLM-9B",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 262,
   "downloads": 1840,
   "trending_score": 258.0,
   "created_at": "2026-09-21T18:18:20.000Z",
   "last_modified": null,
   "age_days": 7.48,
   "like_velocity": 35.0,
   "params_b": 9.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apple-amlr",
   "permissive_license": false,
   "arxiv": [
    "2605.07019"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3.5-9B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5",
    "vision-language-model",
    "long-context",
    "visual-text-compression"
   ],
   "rank_trending": 24,
   "score_breakdown": {
    "momentum": 0.61,
    "velocity": 0.441,
    "recency": 0.586,
    "originality": 0.45,
    "rarity": 0.805
   },
   "score": 56.0,
   "rank_prev": 27,
   "is_new_entry": false,
   "rank_change": 3,
   "reasons": [
    "📄 附論文 arXiv:2605.07019",
    "🔗 微調自 Qwen/Qwen3.5-9B"
   ],
   "pick_rank": null
  },
  {
   "id": "ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF",
   "author": "ISTA-DASLab",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-GSQ-RCO-GGUF",
   "url": "https://huggingface.co/ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 1814,
   "downloads": 1655818,
   "trending_score": 242.0,
   "created_at": "2026-08-28T18:38:03.000Z",
   "last_modified": null,
   "age_days": 31.46,
   "like_velocity": 57.7,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gsq",
    "rco",
    "quantization",
    "mixed-precision",
    "ist-daslab",
    "multimodal"
   ],
   "rank_trending": 25,
   "score_breakdown": {
    "momentum": 0.593,
    "velocity": 0.661,
    "recency": 0.106,
    "originality": 0.0,
    "rarity": 0.805
   },
   "score": 46.9,
   "rank_prev": 25,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "📄 附論文 arXiv:2604.18556",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "fastino/GLiNER2.5-Decide",
   "author": "fastino",
   "author_fullname": null,
   "author_followers": null,
   "name": "GLiNER2.5-Decide",
   "url": "https://huggingface.co/fastino/GLiNER2.5-Decide",
   "pipeline_tag": "token-classification",
   "task_zh": "詞元標註 / NER",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "gliner2",
   "likes": 233,
   "downloads": 24250,
   "trending_score": 231.0,
   "created_at": "2026-09-23T14:56:12.000Z",
   "last_modified": null,
   "age_days": 5.62,
   "like_velocity": 41.5,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2507.18546"
   ],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "fastino/gliner2-large-v1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "extractor",
    "Text classification",
    "Intent classification",
    "Sentiment Analysis",
    "Topic classification",
    "Named Entity Recognition"
   ],
   "rank_trending": 26,
   "score_breakdown": {
    "momentum": 0.576,
    "velocity": 0.559,
    "recency": 0.669,
    "originality": 0.45,
    "rarity": 0.976
   },
   "score": 60.7,
   "rank_prev": 30,
   "is_new_entry": false,
   "rank_change": 4,
   "reasons": [
    "⏱️ 6 天前才發布",
    "🧭 今日榜單少見的任務：詞元標註 / NER",
    "📄 附論文 arXiv:2507.18546",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 fastino/gliner2-large-v1"
   ],
   "pick_rank": null
  },
  {
   "id": "deepseek-ai/DeepSeek-V4.1-Flash",
   "author": "deepseek-ai",
   "author_fullname": null,
   "author_followers": null,
   "name": "DeepSeek-V4.1-Flash",
   "url": "https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 3873,
   "downloads": 668537,
   "trending_score": 209.0,
   "created_at": "2026-09-10T02:17:58.000Z",
   "last_modified": null,
   "age_days": 19.15,
   "like_velocity": 202.3,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "deepseek_v41",
    "text-generation",
    "8-bit",
    "fp8"
   ],
   "rank_trending": 27,
   "score_breakdown": {
    "momentum": 0.559,
    "velocity": 0.949,
    "recency": 0.255,
    "originality": 1.0,
    "rarity": 0.805
   },
   "score": 70.2,
   "rank_prev": 28,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🔥 平均每天 +202 讚",
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": 11
  },
  {
   "id": "netease-youdao/Confucius4-R2T2",
   "author": "netease-youdao",
   "author_fullname": null,
   "author_followers": null,
   "name": "Confucius4-R2T2",
   "url": "https://huggingface.co/netease-youdao/Confucius4-R2T2",
   "pipeline_tag": "automatic-speech-recognition",
   "task_zh": "語音辨識（ASR）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": null,
   "likes": 448,
   "downloads": 9336,
   "trending_score": 199.0,
   "created_at": "2026-09-10T12:16:21.000Z",
   "last_modified": null,
   "age_days": 18.73,
   "like_velocity": 23.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3-ASR-1.7B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_asr",
    "confucius4",
    "r2t2",
    "asr",
    "streaming",
    "real-time"
   ],
   "rank_trending": 28,
   "score_breakdown": {
    "momentum": 0.542,
    "velocity": 0.339,
    "recency": 0.262,
    "originality": 0.45,
    "rarity": 0.902
   },
   "score": 47.2,
   "rank_prev": 26,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "🔗 微調自 Qwen/Qwen3-ASR-1.7B"
   ],
   "pick_rank": null
  },
  {
   "id": "orcarouter/OrcaSAQ-2-27B",
   "author": "orcarouter",
   "author_fullname": null,
   "author_followers": null,
   "name": "OrcaSAQ-2-27B",
   "url": "https://huggingface.co/orcarouter/OrcaSAQ-2-27B",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "vllm",
   "likes": 196,
   "downloads": 1663,
   "trending_score": 195.0,
   "created_at": "2026-09-24T03:44:51.000Z",
   "last_modified": null,
   "age_days": 5.09,
   "like_velocity": 38.5,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5",
    "qwen",
    "qwen3.8",
    "orcasaq2",
    "quantization",
    "mixed-precision"
   ],
   "rank_trending": 29,
   "score_breakdown": {
    "momentum": 0.525,
    "velocity": 0.542,
    "recency": 0.695,
    "originality": 0.0,
    "rarity": 0.829
   },
   "score": 50.7,
   "rank_prev": 36,
   "is_new_entry": false,
   "rank_change": 7,
   "reasons": [
    "📈 排名上升 7 名",
    "⏱️ 5 天前才發布",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "AlexWortega/openjev",
   "author": "AlexWortega",
   "author_fullname": null,
   "author_followers": null,
   "name": "openjev",
   "url": "https://huggingface.co/AlexWortega/openjev",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 621,
   "downloads": 0,
   "trending_score": 183.0,
   "created_at": "2026-09-16T18:25:10.000Z",
   "last_modified": null,
   "age_days": 12.47,
   "like_velocity": 49.8,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3.5-4B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "nli",
    "cross-encoder",
    "qwen3.5",
    "reranker",
    "image-text-to-text"
   ],
   "rank_trending": 30,
   "score_breakdown": {
    "momentum": 0.508,
    "velocity": 0.627,
    "recency": 0.41,
    "originality": 0.45,
    "rarity": 0.878
   },
   "score": 55.2,
   "rank_prev": 23,
   "is_new_entry": false,
   "rank_change": -7,
   "reasons": [
    "✅ 寬鬆授權（mit）",
    "🔗 微調自 Qwen/Qwen3.5-4B"
   ],
   "pick_rank": null
  },
  {
   "id": "convaiinnovations/laya-multilingual",
   "author": "convaiinnovations",
   "author_fullname": null,
   "author_followers": null,
   "name": "laya-multilingual",
   "url": "https://huggingface.co/convaiinnovations/laya-multilingual",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 322,
   "downloads": 0,
   "trending_score": 177.0,
   "created_at": "2026-09-19T03:23:34.000Z",
   "last_modified": null,
   "age_days": 10.1,
   "like_velocity": 31.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "de",
    "fr",
    "es",
    "pt",
    "it",
    "nl",
    "sv"
   ],
   "n_languages": 50,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "laya",
    "multilingual",
    "mmbert",
    "system-one",
    "calibrated-decisions",
    "rlcd"
   ],
   "rank_trending": 31,
   "score_breakdown": {
    "momentum": 0.492,
    "velocity": 0.407,
    "recency": 0.486,
    "originality": 1.0,
    "rarity": 0.878
   },
   "score": 58.4,
   "rank_prev": 29,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "🌏 支援 50 種語言",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": null
  },
  {
   "id": "DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NEO-CODER-MAX-MTP-GGUF",
   "author": "DavidAU",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NEO-CODER-MAX-MTP-GGUF",
   "url": "https://huggingface.co/DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NEO-CODER-MAX-MTP-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": null,
   "likes": 1254,
   "downloads": 1683597,
   "trending_score": 174.0,
   "created_at": "2026-09-01T07:01:09.000Z",
   "last_modified": null,
   "age_days": 27.95,
   "like_velocity": 44.9,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NM-DAU",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "unsloth",
    "fine tune",
    "heretic",
    "uncensored",
    "abliterated"
   ],
   "rank_trending": 32,
   "score_breakdown": {
    "momentum": 0.475,
    "velocity": 0.593,
    "recency": 0.136,
    "originality": 0.0,
    "rarity": 0.805
   },
   "score": 41.5,
   "rank_prev": 34,
   "is_new_entry": false,
   "rank_change": 2,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NM-DAU",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "Qwen/Qwen3.8-Flash-Next",
   "author": "Qwen",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next",
   "url": "https://huggingface.co/Qwen/Qwen3.8-Flash-Next",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 5760,
   "downloads": 1237824,
   "trending_score": 168.0,
   "created_at": "2026-08-24T08:24:59.000Z",
   "last_modified": null,
   "age_days": 35.89,
   "like_velocity": 160.5,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen4_exp"
   ],
   "rank_trending": 33,
   "score_breakdown": {
    "momentum": 0.458,
    "velocity": 0.881,
    "recency": 0.077,
    "originality": 1.0,
    "rarity": 0.805
   },
   "score": 62.3,
   "rank_prev": 32,
   "is_new_entry": false,
   "rank_change": -1,
   "reasons": [
    "🔥 平均每天 +160 讚"
   ],
   "pick_rank": null
  },
  {
   "id": "unsloth/Qwen3.8-27B-GGUF",
   "author": "unsloth",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-GGUF",
   "url": "https://huggingface.co/unsloth/Qwen3.8-27B-GGUF",
   "pipeline_tag": null,
   "task_zh": "未標註任務",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": null,
   "likes": 4704,
   "downloads": 6538700,
   "trending_score": 166.0,
   "created_at": "2026-08-13T08:28:40.000Z",
   "last_modified": null,
   "age_days": 46.89,
   "like_velocity": 100.3,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "qwen3_5",
    "unsloth",
    "imatrix"
   ],
   "rank_trending": 34,
   "score_breakdown": {
    "momentum": 0.441,
    "velocity": 0.847,
    "recency": 0.035,
    "originality": 0.0,
    "rarity": 0.3
   },
   "score": 40.1,
   "rank_prev": 33,
   "is_new_entry": false,
   "rank_change": -1,
   "reasons": [
    "🔥 平均每天 +100 讚",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
   "author": "ISTA-DASLab",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
   "url": "https://huggingface.co/ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 366,
   "downloads": 503144,
   "trending_score": 143.0,
   "created_at": "2026-09-07T09:41:37.000Z",
   "last_modified": null,
   "age_days": 21.84,
   "like_velocity": 16.8,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-Flash-Next",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gsq",
    "rco",
    "quantization",
    "mixed-precision",
    "ist-daslab",
    "moe"
   ],
   "rank_trending": 35,
   "score_breakdown": {
    "momentum": 0.424,
    "velocity": 0.203,
    "recency": 0.21,
    "originality": 0.0,
    "rarity": 0.805
   },
   "score": 31.1,
   "rank_prev": 40,
   "is_new_entry": false,
   "rank_change": 5,
   "reasons": [
    "📈 排名上升 5 名",
    "🧩 MoE 混合專家架構",
    "📄 附論文 arXiv:2604.18556",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-Flash-Next"
   ],
   "pick_rank": null
  },
  {
   "id": "Alissonerdx/BFS-Best-Face-Swap",
   "author": "Alissonerdx",
   "author_fullname": null,
   "author_followers": null,
   "name": "BFS-Best-Face-Swap",
   "url": "https://huggingface.co/Alissonerdx/BFS-Best-Face-Swap",
   "pipeline_tag": "image-to-image",
   "task_zh": "圖生圖 / 影像編輯",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 1017,
   "downloads": 150020,
   "trending_score": 133.0,
   "created_at": "2025-11-07T09:50:28.000Z",
   "last_modified": null,
   "age_days": 325.83,
   "like_velocity": 3.1,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "lora",
    "qwen-image",
    "qwen-image-2.1",
    "qwen-image-edit",
    "face-swap",
    "head-swap"
   ],
   "rank_trending": 36,
   "score_breakdown": {
    "momentum": 0.398,
    "velocity": 0.0,
    "recency": 0.0,
    "originality": 0.35,
    "rarity": 0.976
   },
   "score": 28.9,
   "rank_prev": 58,
   "is_new_entry": false,
   "rank_change": 22,
   "reasons": [
    "📈 排名上升 22 名",
    "🧭 今日榜單少見的任務：圖生圖 / 影像編輯",
    "✅ 寬鬆授權（mit）",
    "🔗 LoRA 掛載於 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "ukisai/Swift-1.5-Qwen3.8-27B-GSQ-RCO-GGUF",
   "author": "ukisai",
   "author_fullname": null,
   "author_followers": null,
   "name": "Swift-1.5-Qwen3.8-27B-GSQ-RCO-GGUF",
   "url": "https://huggingface.co/ukisai/Swift-1.5-Qwen3.8-27B-GSQ-RCO-GGUF",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "gguf",
   "likes": 140,
   "downloads": 58021,
   "trending_score": 133.0,
   "created_at": "2026-09-24T13:13:45.000Z",
   "last_modified": null,
   "age_days": 4.69,
   "like_velocity": 29.9,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "ukisai/Swift-1.5-Qwen3.8-27b",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "llama.cpp",
    "qwen3_8",
    "gsq",
    "rco",
    "reasoning",
    "efficient-thinking"
   ],
   "rank_trending": 37,
   "score_breakdown": {
    "momentum": 0.398,
    "velocity": 0.39,
    "recency": 0.715,
    "originality": 0.0,
    "rarity": 0.829
   },
   "score": 42.7,
   "rank_prev": 42,
   "is_new_entry": false,
   "rank_change": 5,
   "reasons": [
    "📈 排名上升 5 名",
    "⏱️ 5 天前才發布",
    "📄 附論文 arXiv:2604.18556",
    "🔗 量化轉檔自 ukisai/Swift-1.5-Qwen3.8-27b"
   ],
   "pick_rank": null
  },
  {
   "id": "yandex/AliceAI-Foundation-80B-A3B-Base",
   "author": "yandex",
   "author_fullname": null,
   "author_followers": null,
   "name": "AliceAI-Foundation-80B-A3B-Base",
   "url": "https://huggingface.co/yandex/AliceAI-Foundation-80B-A3B-Base",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 357,
   "downloads": 3650,
   "trending_score": 129.0,
   "created_at": "2026-09-12T10:32:07.000Z",
   "last_modified": null,
   "age_days": 16.8,
   "like_velocity": 21.2,
   "params_b": 80.0,
   "active_params_b": 3.0,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "ru",
    "en"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "alice_ai",
    "mixture-of-experts",
    "vllm"
   ],
   "rank_trending": 38,
   "score_breakdown": {
    "momentum": 0.364,
    "velocity": 0.322,
    "recency": 0.301,
    "originality": 1.0,
    "rarity": 0.829
   },
   "score": 48.6,
   "rank_prev": 21,
   "is_new_entry": false,
   "rank_change": -17,
   "reasons": [
    "🧩 MoE 混合專家架構（啟用 3B）",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": null
  },
  {
   "id": "akatz-ai/MiniMax-H3-Character-Swap-LoRA",
   "author": "akatz-ai",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiniMax-H3-Character-Swap-LoRA",
   "url": "https://huggingface.co/akatz-ai/MiniMax-H3-Character-Swap-LoRA",
   "pipeline_tag": "video-to-video",
   "task_zh": "影片轉換",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusion-single-file",
   "likes": 133,
   "downloads": 3436,
   "trending_score": 129.0,
   "created_at": "2026-09-25T08:14:15.000Z",
   "last_modified": null,
   "age_days": 3.9,
   "like_velocity": 34.1,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Comfy-Org/MiniMax-H3",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "minimax-h3",
    "lora",
    "character-swap",
    "video-editing",
    "ref2va",
    "comfyui"
   ],
   "rank_trending": 39,
   "score_breakdown": {
    "momentum": 0.364,
    "velocity": 0.424,
    "recency": 0.757,
    "originality": 0.35,
    "rarity": 0.976
   },
   "score": 49.7,
   "rank_prev": 55,
   "is_new_entry": false,
   "rank_change": 16,
   "reasons": [
    "📈 排名上升 16 名",
    "⏱️ 4 天前才發布",
    "🧭 今日榜單少見的任務：影片轉換",
    "🔗 LoRA 掛載於 Comfy-Org/MiniMax-H3"
   ],
   "pick_rank": null
  },
  {
   "id": "orcarouter/OrcaSAQ-2-Cyber-27B-Uncensored-GGUF",
   "author": "orcarouter",
   "author_fullname": null,
   "author_followers": null,
   "name": "OrcaSAQ-2-Cyber-27B-Uncensored-GGUF",
   "url": "https://huggingface.co/orcarouter/OrcaSAQ-2-Cyber-27B-Uncensored-GGUF",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "llama.cpp",
   "likes": 135,
   "downloads": 4599,
   "trending_score": 122.0,
   "created_at": "2026-09-26T03:37:50.000Z",
   "last_modified": null,
   "age_days": 3.09,
   "like_velocity": 43.7,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "orcarouter/Qwen3.8-27B-Uncensored",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "qwen",
    "qwen3.8",
    "qwen3_5",
    "orcasaq2",
    "quantization"
   ],
   "rank_trending": 40,
   "score_breakdown": {
    "momentum": 0.339,
    "velocity": 0.576,
    "recency": 0.802,
    "originality": 0.0,
    "rarity": 0.829
   },
   "score": 46.6,
   "rank_prev": 51,
   "is_new_entry": false,
   "rank_change": 11,
   "reasons": [
    "📈 排名上升 11 名",
    "⏱️ 3 天前才發布",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 orcarouter/Qwen3.8-27B-Uncensored",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "PrunaAI/Pruna-Qwen-Image-2.1",
   "author": "PrunaAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "Pruna-Qwen-Image-2.1",
   "url": "https://huggingface.co/PrunaAI/Pruna-Qwen-Image-2.1",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 119,
   "downloads": 13262,
   "trending_score": 119.0,
   "created_at": "2026-09-23T07:30:42.000Z",
   "last_modified": null,
   "age_days": 5.93,
   "like_velocity": 20.1,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen",
    "image-generation",
    "image-editing",
    "rgba",
    "lora",
    "distilled"
   ],
   "rank_trending": 41,
   "score_breakdown": {
    "momentum": 0.322,
    "velocity": 0.288,
    "recency": 0.655,
    "originality": 0.35,
    "rarity": 0.902
   },
   "score": 42.6,
   "rank_prev": 44,
   "is_new_entry": false,
   "rank_change": 3,
   "reasons": [
    "⏱️ 6 天前才發布",
    "🔗 LoRA 掛載於 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "MiniMaxAI/MiniMax-H3",
   "author": "MiniMaxAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiniMax-H3",
   "url": "https://huggingface.co/MiniMaxAI/MiniMax-H3",
   "pipeline_tag": "image-text-to-video",
   "task_zh": "圖文生影片",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "minimax-h3",
   "likes": 5758,
   "downloads": 3627177,
   "trending_score": 118.0,
   "created_at": "2026-07-28T10:45:18.000Z",
   "last_modified": null,
   "age_days": 62.79,
   "like_velocity": 91.7,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "diffusers",
    "text-to-video",
    "image-to-video",
    "video-to-video",
    "text-to-audio-video",
    "image-to-audio-video"
   ],
   "rank_trending": 42,
   "score_breakdown": {
    "momentum": 0.297,
    "velocity": 0.831,
    "recency": 0.011,
    "originality": 1.0,
    "rarity": 0.976
   },
   "score": 56.1,
   "rank_prev": 39,
   "is_new_entry": false,
   "rank_change": -3,
   "reasons": [
    "🔥 平均每天 +92 讚",
    "🧭 今日榜單少見的任務：圖文生影片"
   ],
   "pick_rank": null
  },
  {
   "id": "HauhauCS/Qwen3.8-27B-Uncensored-HauhauCS-Aggressive-MTP-GGUF",
   "author": "HauhauCS",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-Uncensored-HauhauCS-Aggressive-MTP-GGUF",
   "url": "https://huggingface.co/HauhauCS/Qwen3.8-27B-Uncensored-HauhauCS-Aggressive-MTP-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": null,
   "likes": 1510,
   "downloads": 2057914,
   "trending_score": 118.0,
   "created_at": "2026-08-17T15:15:19.000Z",
   "last_modified": null,
   "age_days": 42.61,
   "like_velocity": 35.4,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "uncensored",
    "qwen3.8",
    "multimodal",
    "vision",
    "mtp"
   ],
   "rank_trending": 43,
   "score_breakdown": {
    "momentum": 0.297,
    "velocity": 0.458,
    "recency": 0.048,
    "originality": 0.0,
    "rarity": 0.805
   },
   "score": 30.6,
   "rank_prev": 41,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "pyannote/speaker-diarization-community-1",
   "author": "pyannote",
   "author_fullname": null,
   "author_followers": null,
   "name": "speaker-diarization-community-1",
   "url": "https://huggingface.co/pyannote/speaker-diarization-community-1",
   "pipeline_tag": "automatic-speech-recognition",
   "task_zh": "語音辨識（ASR）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": "pyannote-audio",
   "likes": 2243,
   "downloads": 5403708,
   "trending_score": 113.0,
   "created_at": "2025-04-15T21:31:35.000Z",
   "last_modified": null,
   "age_days": 531.34,
   "like_velocity": 4.2,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "cc-by-4.0",
   "permissive_license": true,
   "arxiv": [
    "2104.03603",
    "2111.14448",
    "2012.01477"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "pyannote",
    "pyannote-audio-pipeline",
    "audio",
    "voice",
    "speech",
    "speaker"
   ],
   "rank_trending": 44,
   "score_breakdown": {
    "momentum": 0.271,
    "velocity": 0.017,
    "recency": 0.0,
    "originality": 1.0,
    "rarity": 0.902
   },
   "score": 33.9,
   "rank_prev": 43,
   "is_new_entry": false,
   "rank_change": -1,
   "reasons": [
    "📄 附論文 arXiv:2104.03603",
    "✅ 寬鬆授權（cc-by-4.0）"
   ],
   "pick_rank": null
  },
  {
   "id": "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-Coder-GGUF",
   "author": "ISTA-DASLab",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next-GSQ-RCO-Coder-GGUF",
   "url": "https://huggingface.co/ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-Coder-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 109,
   "downloads": 5522,
   "trending_score": 108.0,
   "created_at": "2026-09-26T09:42:51.000Z",
   "last_modified": null,
   "age_days": 2.84,
   "like_velocity": 38.4,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-Flash-Next",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gsq",
    "rco",
    "quantization",
    "pruning",
    "expert-pruning",
    "mixed-precision"
   ],
   "rank_trending": 45,
   "score_breakdown": {
    "momentum": 0.254,
    "velocity": 0.525,
    "recency": 0.816,
    "originality": 0.0,
    "rarity": 0.805
   },
   "score": 42.3,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 3 天前才發布",
    "🧩 MoE 混合專家架構",
    "📄 附論文 arXiv:2604.18556",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": null
  },
  {
   "id": "bottlecapai/ThinkingCap-Qwen3.8-27B",
   "author": "bottlecapai",
   "author_fullname": null,
   "author_followers": null,
   "name": "ThinkingCap-Qwen3.8-27B",
   "url": "https://huggingface.co/bottlecapai/ThinkingCap-Qwen3.8-27B",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 116,
   "downloads": 706,
   "trending_score": 106.0,
   "created_at": "2026-09-23T15:56:49.000Z",
   "last_modified": null,
   "age_days": 5.58,
   "like_velocity": 20.8,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5",
    "qwen3_8",
    "token-efficient",
    "efficient-thinking"
   ],
   "rank_trending": 46,
   "score_breakdown": {
    "momentum": 0.237,
    "velocity": 0.305,
    "recency": 0.671,
    "originality": 0.45,
    "rarity": 0.805
   },
   "score": 40.8,
   "rank_prev": 48,
   "is_new_entry": false,
   "rank_change": 2,
   "reasons": [
    "⏱️ 6 天前才發布",
    "🔗 微調自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "AikidoSec/altar-1",
   "author": "AikidoSec",
   "author_fullname": null,
   "author_followers": null,
   "name": "altar-1",
   "url": "https://huggingface.co/AikidoSec/altar-1",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": null,
   "likes": 195,
   "downloads": 1764,
   "trending_score": 103.0,
   "created_at": "2026-09-07T18:50:43.000Z",
   "last_modified": null,
   "age_days": 21.46,
   "like_velocity": 9.1,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2510.13999"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "cyankiwi/GLM-5.3-AWQ-INT4",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "glm_moe_dsa",
    "glm",
    "glm-5.3",
    "moe",
    "w4a16",
    "awq"
   ],
   "rank_trending": 47,
   "score_breakdown": {
    "momentum": 0.22,
    "velocity": 0.051,
    "recency": 0.216,
    "originality": 0.0,
    "rarity": 0.829
   },
   "score": 20.5,
   "rank_prev": 35,
   "is_new_entry": false,
   "rank_change": -12,
   "reasons": [
    "🧩 MoE 混合專家架構",
    "📄 附論文 arXiv:2510.13999",
    "🔗 量化轉檔自 cyankiwi/GLM-5.3-AWQ-INT4"
   ],
   "pick_rank": null
  },
  {
   "id": "facebook/sam3",
   "author": "facebook",
   "author_fullname": null,
   "author_followers": null,
   "name": "sam3",
   "url": "https://huggingface.co/facebook/sam3",
   "pipeline_tag": "mask-generation",
   "task_zh": "遮罩生成",
   "task_group": "vision",
   "task_group_zh": "電腦視覺",
   "library": "transformers",
   "likes": 3572,
   "downloads": 2122184,
   "trending_score": 102.0,
   "created_at": "2025-11-07T05:17:48.000Z",
   "last_modified": null,
   "age_days": 326.02,
   "like_velocity": 11.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "sam3_video",
    "feature-extraction",
    "sam3"
   ],
   "rank_trending": 48,
   "score_breakdown": {
    "momentum": 0.195,
    "velocity": 0.085,
    "recency": 0.0,
    "originality": 1.0,
    "rarity": 0.976
   },
   "score": 33.7,
   "rank_prev": 49,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🧭 今日榜單少見的任務：遮罩生成"
   ],
   "pick_rank": null
  },
  {
   "id": "black-forest-labs/flux-3-action-base",
   "author": "black-forest-labs",
   "author_fullname": null,
   "author_followers": null,
   "name": "flux-3-action-base",
   "url": "https://huggingface.co/black-forest-labs/flux-3-action-base",
   "pipeline_tag": "robotics",
   "task_zh": "機器人",
   "task_group": "decision",
   "task_group_zh": "決策 / 科學",
   "library": "lerobot",
   "likes": 103,
   "downloads": 0,
   "trending_score": 102.0,
   "created_at": "2026-09-22T10:36:43.000Z",
   "last_modified": null,
   "age_days": 6.8,
   "like_velocity": 15.1,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "flux",
    "world-action-model"
   ],
   "rank_trending": 49,
   "score_breakdown": {
    "momentum": 0.195,
    "velocity": 0.153,
    "recency": 0.615,
    "originality": 1.0,
    "rarity": 0.976
   },
   "score": 44.6,
   "rank_prev": 52,
   "is_new_entry": false,
   "rank_change": 3,
   "reasons": [
    "⏱️ 7 天前才發布",
    "🧭 今日榜單少見的任務：機器人"
   ],
   "pick_rank": null
  },
  {
   "id": "bartowski/MiMo-V2.6-Distill-Qwen-9B-GGUF",
   "author": "bartowski",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiMo-V2.6-Distill-Qwen-9B-GGUF",
   "url": "https://huggingface.co/bartowski/MiMo-V2.6-Distill-Qwen-9B-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": null,
   "likes": 104,
   "downloads": 124344,
   "trending_score": 98.0,
   "created_at": "2026-09-21T22:09:46.000Z",
   "last_modified": null,
   "age_days": 7.32,
   "like_velocity": 14.2,
   "params_b": 9.0,
   "active_params_b": null,
   "is_moe": false,
   "license": null,
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "XiaomiMiMo/MiMo-V2.6-Distill-Qwen-9B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "mimo_v2",
    "agentic",
    "distillation",
    "supervised-fine-tuning",
    "code"
   ],
   "rank_trending": 50,
   "score_breakdown": {
    "momentum": 0.169,
    "velocity": 0.136,
    "recency": 0.593,
    "originality": 0.0,
    "rarity": 0.805
   },
   "score": 26.3,
   "rank_prev": 54,
   "is_new_entry": false,
   "rank_change": 4,
   "reasons": [
    "🔗 量化轉檔自 XiaomiMiMo/MiMo-V2.6-Distill-Qwen-9B"
   ],
   "pick_rank": null
  },
  {
   "id": "ukisai/Swift-1.5-Qwen3.8-27B-GGUF",
   "author": "ukisai",
   "author_fullname": null,
   "author_followers": null,
   "name": "Swift-1.5-Qwen3.8-27B-GGUF",
   "url": "https://huggingface.co/ukisai/Swift-1.5-Qwen3.8-27B-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 101,
   "downloads": 57627,
   "trending_score": 96.0,
   "created_at": "2026-09-21T21:24:24.000Z",
   "last_modified": null,
   "age_days": 7.35,
   "like_velocity": 13.7,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "ukisai/Swift-1.5-Qwen3.8-27b",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "llama.cpp",
    "qwen3_8",
    "reasoning",
    "efficient-thinking",
    "token-efficient",
    "post-training"
   ],
   "rank_trending": 51,
   "score_breakdown": {
    "momentum": 0.153,
    "velocity": 0.11,
    "recency": 0.592,
    "originality": 0.0,
    "rarity": 0.805
   },
   "score": 25.0,
   "rank_prev": 59,
   "is_new_entry": false,
   "rank_change": 8,
   "reasons": [
    "📈 排名上升 8 名",
    "🔗 量化轉檔自 ukisai/Swift-1.5-Qwen3.8-27b"
   ],
   "pick_rank": null
  },
  {
   "id": "NaiveAI/Naive-N0.5-Flash",
   "author": "NaiveAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "Naive-N0.5-Flash",
   "url": "https://huggingface.co/NaiveAI/Naive-N0.5-Flash",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": null,
   "likes": 97,
   "downloads": 605,
   "trending_score": 95.0,
   "created_at": "2026-09-27T14:14:32.000Z",
   "last_modified": null,
   "age_days": 1.65,
   "like_velocity": 58.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "naive_n05_flash",
    "moe",
    "code",
    "long-context",
    "ai-research"
   ],
   "rank_trending": 52,
   "score_breakdown": {
    "momentum": 0.136,
    "velocity": 0.678,
    "recency": 0.889,
    "originality": 1.0,
    "rarity": 0.829
   },
   "score": 58.3,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 2 天前才發布",
    "🧩 MoE 混合專家架構",
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": null
  },
  {
   "id": "interfaze-ai/lev",
   "author": "interfaze-ai",
   "author_fullname": null,
   "author_followers": null,
   "name": "lev",
   "url": "https://huggingface.co/interfaze-ai/lev",
   "pipeline_tag": "zero-shot-classification",
   "task_zh": "零樣本文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "peft",
   "likes": 93,
   "downloads": 316,
   "trending_score": 90.0,
   "created_at": "2026-09-24T06:33:36.000Z",
   "last_modified": null,
   "age_days": 4.97,
   "like_velocity": 18.7,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Qwen/Qwen3.5-4B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "lev",
    "system-one",
    "decision-model",
    "calibrated-decisions",
    "classification",
    "routing"
   ],
   "rank_trending": 53,
   "score_breakdown": {
    "momentum": 0.119,
    "velocity": 0.254,
    "recency": 0.701,
    "originality": 0.35,
    "rarity": 0.976
   },
   "score": 36.0,
   "rank_prev": 60,
   "is_new_entry": false,
   "rank_change": 7,
   "reasons": [
    "📈 排名上升 7 名",
    "⏱️ 5 天前才發布",
    "🧭 今日榜單少見的任務：零樣本文字分類",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 LoRA 掛載於 Qwen/Qwen3.5-4B"
   ],
   "pick_rank": null
  },
  {
   "id": "WarmBloodAban/Minimax-h3_Singularity",
   "author": "WarmBloodAban",
   "author_fullname": null,
   "author_followers": null,
   "name": "Minimax-h3_Singularity",
   "url": "https://huggingface.co/WarmBloodAban/Minimax-h3_Singularity",
   "pipeline_tag": "image-to-video",
   "task_zh": "圖生影片",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "minimax-h3",
   "likes": 693,
   "downloads": 452222,
   "trending_score": 88.0,
   "created_at": "2026-09-05T18:51:01.000Z",
   "last_modified": null,
   "age_days": 23.46,
   "like_velocity": 29.5,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "MiniMaxAI/MiniMax-H3",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "video-generation",
    "text-to-video",
    "video-to-video",
    "reference-to-video",
    "comfyui",
    "fine-tuned"
   ],
   "rank_trending": 54,
   "score_breakdown": {
    "momentum": 0.102,
    "velocity": 0.373,
    "recency": 0.187,
    "originality": 0.45,
    "rarity": 0.951
   },
   "score": 32.0,
   "rank_prev": 47,
   "is_new_entry": false,
   "rank_change": -7,
   "reasons": [
    "🧭 今日榜單少見的任務：圖生影片",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 MiniMaxAI/MiniMax-H3"
   ],
   "pick_rank": null
  },
  {
   "id": "Cactus-Compute/needle3",
   "author": "Cactus-Compute",
   "author_fullname": null,
   "author_followers": null,
   "name": "needle3",
   "url": "https://huggingface.co/Cactus-Compute/needle3",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "cactus-needle",
   "likes": 256,
   "downloads": 90245,
   "trending_score": 85.0,
   "created_at": "2026-09-16T06:41:36.000Z",
   "last_modified": null,
   "age_days": 12.96,
   "like_velocity": 19.7,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "needle",
    "tool-calling",
    "function-calling",
    "on-device",
    "edge",
    "quantization"
   ],
   "rank_trending": 55,
   "score_breakdown": {
    "momentum": 0.085,
    "velocity": 0.271,
    "recency": 0.396,
    "originality": 1.0,
    "rarity": 0.829
   },
   "score": 39.0,
   "rank_prev": 46,
   "is_new_entry": false,
   "rank_change": -9,
   "reasons": [
    "📱 強調裝置端推論",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": null
  },
  {
   "id": "inclusionAI/Ming-Image-0.1-Design-Layer",
   "author": "inclusionAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "Ming-Image-0.1-Design-Layer",
   "url": "https://huggingface.co/inclusionAI/Ming-Image-0.1-Design-Layer",
   "pipeline_tag": "image-text-to-image",
   "task_zh": "image-text-to-image",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": "custom",
   "likes": 84,
   "downloads": 0,
   "trending_score": 83.0,
   "created_at": "2026-09-17T11:36:00.000Z",
   "last_modified": null,
   "age_days": 11.76,
   "like_velocity": 7.1,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "diffusers",
    "layer-decomposition",
    "rgba",
    "graphic-design"
   ],
   "rank_trending": 56,
   "score_breakdown": {
    "momentum": 0.068,
    "velocity": 0.034,
    "recency": 0.432,
    "originality": 1.0,
    "rarity": 0.976
   },
   "score": 34.5,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "🧭 今日榜單少見的任務：image-text-to-image",
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": null
  },
  {
   "id": "Hikari07jp/Ternary-Bonsai-2-27B-Abliterated-GGUF",
   "author": "Hikari07jp",
   "author_fullname": null,
   "author_followers": null,
   "name": "Ternary-Bonsai-2-27B-Abliterated-GGUF",
   "url": "https://huggingface.co/Hikari07jp/Ternary-Bonsai-2-27B-Abliterated-GGUF",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "llama.cpp",
   "likes": 109,
   "downloads": 27282,
   "trending_score": 80.0,
   "created_at": "2026-09-18T10:38:41.000Z",
   "last_modified": null,
   "age_days": 10.8,
   "like_velocity": 10.1,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "prism-ml/Ternary-Bonsai-2-27B-gguf",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "ternary",
    "2-bit",
    "llama-cpp",
    "abliterated",
    "uncensored"
   ],
   "rank_trending": 57,
   "score_breakdown": {
    "momentum": 0.042,
    "velocity": 0.068,
    "recency": 0.462,
    "originality": 0.0,
    "rarity": 0.829
   },
   "score": 18.4,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 prism-ml/Ternary-Bonsai-2-27B-gguf",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "moondream/parakeet-redux",
   "author": "moondream",
   "author_fullname": null,
   "author_followers": null,
   "name": "parakeet-redux",
   "url": "https://huggingface.co/moondream/parakeet-redux",
   "pipeline_tag": "automatic-speech-recognition",
   "task_zh": "語音辨識（ASR）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": null,
   "likes": 169,
   "downloads": 6086,
   "trending_score": 80.0,
   "created_at": "2026-09-18T11:02:15.000Z",
   "last_modified": null,
   "age_days": 10.78,
   "like_velocity": 15.7,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "cc-by-4.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "de",
    "fr",
    "es",
    "it",
    "pt",
    "ru",
    "uk"
   ],
   "n_languages": 25,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "parakeet_tdt",
    "ternary",
    "parakeet",
    "tdt",
    "speech-recognition",
    "cpu"
   ],
   "rank_trending": 58,
   "score_breakdown": {
    "momentum": 0.042,
    "velocity": 0.186,
    "recency": 0.463,
    "originality": 1.0,
    "rarity": 0.902
   },
   "score": 37.1,
   "rank_prev": 37,
   "is_new_entry": false,
   "rank_change": -21,
   "reasons": [
    "📱 強調裝置端推論",
    "🌏 支援 25 種語言",
    "✅ 寬鬆授權（cc-by-4.0）"
   ],
   "pick_rank": null
  },
  {
   "id": "Alissonerdx/Minimax-H3-ComfyUI",
   "author": "Alissonerdx",
   "author_fullname": null,
   "author_followers": null,
   "name": "Minimax-H3-ComfyUI",
   "url": "https://huggingface.co/Alissonerdx/Minimax-H3-ComfyUI",
   "pipeline_tag": null,
   "task_zh": "未標註任務",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": "minimax-h3",
   "likes": 313,
   "downloads": 47938,
   "trending_score": 79.0,
   "created_at": "2026-09-06T11:22:02.000Z",
   "last_modified": null,
   "age_days": 22.77,
   "like_velocity": 13.7,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "MiniMaxAI/MiniMax-H3",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "lora",
    "video",
    "comfyui"
   ],
   "rank_trending": 59,
   "score_breakdown": {
    "momentum": 0.008,
    "velocity": 0.11,
    "recency": 0.197,
    "originality": 0.35,
    "rarity": 0.3
   },
   "score": 14.3,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 LoRA 掛載於 MiniMaxAI/MiniMax-H3"
   ],
   "pick_rank": null
  },
  {
   "id": "KasugaiSakura/Qwen-Image-2.1-Uncensored-Abenzerps-GGUF",
   "author": "KasugaiSakura",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1-Uncensored-Abenzerps-GGUF",
   "url": "https://huggingface.co/KasugaiSakura/Qwen-Image-2.1-Uncensored-Abenzerps-GGUF",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "gguf",
   "likes": 130,
   "downloads": 30012,
   "trending_score": 79.0,
   "created_at": "2026-09-20T22:11:43.000Z",
   "last_modified": null,
   "age_days": 8.32,
   "like_velocity": 15.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen",
    "image-generation",
    "comfyui",
    "comfyui-gguf"
   ],
   "rank_trending": 60,
   "score_breakdown": {
    "momentum": 0.008,
    "velocity": 0.169,
    "recency": 0.552,
    "originality": 0.0,
    "rarity": 0.902
   },
   "score": 21.8,
   "rank_prev": 45,
   "is_new_entry": false,
   "rank_change": -15,
   "reasons": [
    "🔗 量化轉檔自 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  }
 ]
};
