/* 由 fetch_hf.py 自動產生，請勿手動編輯 */
window.DAILY_MODELS = {
 "schema_version": 1,
 "generator": "fetch_hf.py 1.0.0",
 "snapshot_date": "2026-10-10",
 "generated_at": "2026-10-10T14:13:18+00:00",
 "generated_at_local": "2026-10-10 14:13",
 "source": {
  "name": "Hugging Face Hub API",
  "endpoint": "https://huggingface.co/api/models?sort=trendingScore&limit=60",
  "enrichment": null
 },
 "previous_snapshot": "2026-10-08",
 "method": {
  "weights": {
   "momentum": 0.35,
   "velocity": 0.25,
   "recency": 0.15,
   "originality": 0.15,
   "rarity": 0.1
  },
  "recency_half_life_days": 14.0,
  "originality": {
   "original": 1.0,
   "finetune": 0.45,
   "derived": 0.4,
   "merge": 0.35,
   "adapter": 0.35,
   "quantized": 0.0
  },
  "pick_rules": "排除量化轉檔與移除安全對齊版本；依分數貪婪挑選，同作者 ≤2、同任務 ≤3，不足時放寬"
 },
 "stats": {
  "fetched": 60,
  "models": 60,
  "picks": 12,
  "derivatives": {
   "original": 20,
   "finetune": 9,
   "quantized": 26,
   "adapter": 5
  },
  "quantized_hidden_by_default": 26,
  "task_counts": {
   "圖文理解（VLM）": 9,
   "文生圖": 4,
   "語音辨識（ASR）": 3,
   "文字生成": 3,
   "圖生影片": 2,
   "文字分類": 2,
   "圖生圖 / 影像編輯": 2,
   "圖文生影片": 2,
   "影片轉換": 2,
   "未標註任務": 2,
   "特徵萃取 / 嵌入": 1,
   "語音合成（TTS）": 1,
   "遮罩生成": 1
  },
  "group_counts": {
   "影像 / 影音生成": 12,
   "多模態": 9,
   "語言": 6,
   "語音 / 音訊": 4,
   "其他": 2,
   "電腦視覺": 1
  },
  "elapsed_sec": 0.24
 },
 "picks": [
  "Qwen/Qwen-Image-2.1-Turbo",
  "convaiinnovations/laya",
  "google/embeddinggemma-2",
  "Cloudflare/clef",
  "Qwen/Qwen3.8-27B",
  "Lightricks/LTX-2.5",
  "canberkkkkkk/ema-lightning",
  "Cactus-Compute/whistle",
  "Cloudflare/clef-flash",
  "MiniMaxAI/MiniMax-H3",
  "speridlabs/iris-3b",
  "FrancisRing/Prism"
 ],
 "models": [
  {
   "id": "google/embeddinggemma-2",
   "author": "google",
   "author_fullname": null,
   "author_followers": null,
   "name": "embeddinggemma-2",
   "url": "https://huggingface.co/google/embeddinggemma-2",
   "pipeline_tag": "feature-extraction",
   "task_zh": "特徵萃取 / 嵌入",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 1436,
   "downloads": 45605,
   "trending_score": 1370.0,
   "created_at": "2026-09-14T14:53:42.000Z",
   "last_modified": null,
   "age_days": 25.97,
   "like_velocity": 55.3,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "embedding_gemma2",
    "embedding",
    "sentence-transformers",
    "multimodal-embedding",
    "multimodal",
    "vision"
   ],
   "rank_trending": 1,
   "score_breakdown": {
    "momentum": 1.0,
    "velocity": 0.712,
    "recency": 0.156,
    "originality": 1.0,
    "rarity": 0.971
   },
   "score": 79.8,
   "rank_prev": 4,
   "is_new_entry": false,
   "rank_change": 3,
   "reasons": [
    "🧭 今日榜單少見的任務：特徵萃取 / 嵌入",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 3
  },
  {
   "id": "Cloudflare/clef",
   "author": "Cloudflare",
   "author_fullname": null,
   "author_followers": null,
   "name": "clef",
   "url": "https://huggingface.co/Cloudflare/clef",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 1970,
   "downloads": 13579,
   "trending_score": 886.0,
   "created_at": "2026-09-30T21:15:35.000Z",
   "last_modified": null,
   "age_days": 9.71,
   "like_velocity": 203.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5",
    "clef",
    "cloudflare",
    "systemone",
    "decision-model",
    "qwen3.8"
   ],
   "rank_trending": 2,
   "score_breakdown": {
    "momentum": 0.983,
    "velocity": 0.949,
    "recency": 0.5,
    "originality": 0.45,
    "rarity": 0.735
   },
   "score": 79.7,
   "rank_prev": 2,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🔥 平均每天 +203 讚",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": 4
  },
  {
   "id": "jialinyyzz/humanizer",
   "author": "jialinyyzz",
   "author_fullname": null,
   "author_followers": null,
   "name": "humanizer",
   "url": "https://huggingface.co/jialinyyzz/humanizer",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "gguf",
   "likes": 895,
   "downloads": 33664,
   "trending_score": 833.0,
   "created_at": "2026-09-11T05:00:16.000Z",
   "last_modified": null,
   "age_days": 29.38,
   "like_velocity": 30.5,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "google/gemma-4-12B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gemma4_unified",
    "image-text-to-text",
    "humanizer",
    "transformers",
    "text-rewriting",
    "rewriting"
   ],
   "rank_trending": 3,
   "score_breakdown": {
    "momentum": 0.966,
    "velocity": 0.508,
    "recency": 0.123,
    "originality": 0.0,
    "rarity": 0.912
   },
   "score": 57.5,
   "rank_prev": 10,
   "is_new_entry": false,
   "rank_change": 7,
   "reasons": [
    "📈 排名上升 7 名",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 google/gemma-4-12B"
   ],
   "pick_rank": null
  },
  {
   "id": "Aleph-Alpha/Kolibri-1",
   "author": "Aleph-Alpha",
   "author_fullname": null,
   "author_followers": null,
   "name": "Kolibri-1",
   "url": "https://huggingface.co/Aleph-Alpha/Kolibri-1",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "vllm",
   "likes": 853,
   "downloads": 10496,
   "trending_score": 692.0,
   "created_at": "2026-10-02T05:54:02.000Z",
   "last_modified": null,
   "age_days": 8.35,
   "like_velocity": 102.2,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2512.11614",
    "2601.17858"
   ],
   "languages": [
    "de",
    "en"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Aleph-Alpha/Kolibri-1-BF16",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "kolibri1",
    "reasoning",
    "moe",
    "fp8"
   ],
   "rank_trending": 4,
   "score_breakdown": {
    "momentum": 0.949,
    "velocity": 0.831,
    "recency": 0.551,
    "originality": 0.0,
    "rarity": 0.912
   },
   "score": 71.4,
   "rank_prev": 5,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🔥 平均每天 +102 讚",
    "🧩 MoE 混合專家架構",
    "📄 附論文 arXiv:2512.11614",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Aleph-Alpha/Kolibri-1-BF16"
   ],
   "pick_rank": null
  },
  {
   "id": "abenzerps/Qwen-Image-2.1-Uncensored-GGUF",
   "author": "abenzerps",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1-Uncensored-GGUF",
   "url": "https://huggingface.co/abenzerps/Qwen-Image-2.1-Uncensored-GGUF",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "gguf",
   "likes": 3824,
   "downloads": 2096562,
   "trending_score": 662.0,
   "created_at": "2026-09-20T15:51:13.000Z",
   "last_modified": null,
   "age_days": 19.93,
   "like_velocity": 191.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen",
    "image-generation",
    "comfyui",
    "comfyui-gguf"
   ],
   "rank_trending": 5,
   "score_breakdown": {
    "momentum": 0.932,
    "velocity": 0.932,
    "recency": 0.241,
    "originality": 0.0,
    "rarity": 0.882
   },
   "score": 68.4,
   "rank_prev": 6,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🔥 平均每天 +192 讚",
    "🔗 量化轉檔自 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "Venastine-Research/Xing4.0-29B-A4B-GGUF",
   "author": "Venastine-Research",
   "author_fullname": null,
   "author_followers": null,
   "name": "Xing4.0-29B-A4B-GGUF",
   "url": "https://huggingface.co/Venastine-Research/Xing4.0-29B-A4B-GGUF",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 678,
   "downloads": 45199,
   "trending_score": 505.0,
   "created_at": "2026-09-17T18:37:31.000Z",
   "last_modified": null,
   "age_days": 22.82,
   "like_velocity": 29.7,
   "params_b": 29.0,
   "active_params_b": 4.0,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2512.24157",
    "2507.18013"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "XingChen-AGI/Xing4.0-29B-A4B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "xing4_0"
   ],
   "rank_trending": 6,
   "score_breakdown": {
    "momentum": 0.915,
    "velocity": 0.475,
    "recency": 0.196,
    "originality": 0.0,
    "rarity": 0.912
   },
   "score": 56.0,
   "rank_prev": 8,
   "is_new_entry": false,
   "rank_change": 2,
   "reasons": [
    "🧩 MoE 混合專家架構（啟用 4B）",
    "📄 附論文 arXiv:2512.24157",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 XingChen-AGI/Xing4.0-29B-A4B"
   ],
   "pick_rank": null
  },
  {
   "id": "Lightricks/LTX-2.5",
   "author": "Lightricks",
   "author_fullname": null,
   "author_followers": null,
   "name": "LTX-2.5",
   "url": "https://huggingface.co/Lightricks/LTX-2.5",
   "pipeline_tag": "image-to-video",
   "task_zh": "圖生影片",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusion-single-file",
   "likes": 7118,
   "downloads": 1720888,
   "trending_score": 477.0,
   "created_at": "2026-07-23T07:55:24.000Z",
   "last_modified": null,
   "age_days": 79.26,
   "like_velocity": 89.8,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2601.03233"
   ],
   "languages": [
    "en",
    "de",
    "es",
    "fr",
    "ja",
    "ko",
    "zh",
    "it"
   ],
   "n_languages": 9,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "text-to-video",
    "video-to-video",
    "image-text-to-video",
    "audio-to-video",
    "text-to-audio",
    "video-to-audio"
   ],
   "rank_trending": 7,
   "score_breakdown": {
    "momentum": 0.898,
    "velocity": 0.797,
    "recency": 0.003,
    "originality": 1.0,
    "rarity": 0.941
   },
   "score": 75.8,
   "rank_prev": 9,
   "is_new_entry": false,
   "rank_change": 2,
   "reasons": [
    "🔥 平均每天 +90 讚",
    "🧭 今日榜單少見的任務：圖生影片",
    "📄 附論文 arXiv:2601.03233"
   ],
   "pick_rank": 6
  },
  {
   "id": "Qwen/Qwen-Image-2.1-Turbo",
   "author": "Qwen",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1-Turbo",
   "url": "https://huggingface.co/Qwen/Qwen-Image-2.1-Turbo",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 398,
   "downloads": 2138,
   "trending_score": 393.0,
   "created_at": "2026-10-09T04:50:01.000Z",
   "last_modified": null,
   "age_days": 1.39,
   "like_velocity": 286.1,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen",
    "image-generation",
    "image-editing"
   ],
   "rank_trending": 8,
   "score_breakdown": {
    "momentum": 0.881,
    "velocity": 1.0,
    "recency": 0.905,
    "originality": 0.45,
    "rarity": 0.882
   },
   "score": 85.0,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 1 天前才發布",
    "🔥 平均每天 +286 讚",
    "🔗 微調自 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": 1
  },
  {
   "id": "Cloudflare/clef-flash",
   "author": "Cloudflare",
   "author_fullname": null,
   "author_followers": null,
   "name": "clef-flash",
   "url": "https://huggingface.co/Cloudflare/clef-flash",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 724,
   "downloads": 20670,
   "trending_score": 344.0,
   "created_at": "2026-09-30T21:15:36.000Z",
   "last_modified": null,
   "age_days": 9.71,
   "like_velocity": 74.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3.5-9B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5",
    "clef",
    "cloudflare",
    "systemone",
    "decision-model",
    "qwen3.5"
   ],
   "rank_trending": 9,
   "score_breakdown": {
    "momentum": 0.864,
    "velocity": 0.746,
    "recency": 0.5,
    "originality": 0.45,
    "rarity": 0.735
   },
   "score": 70.5,
   "rank_prev": 7,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 Qwen/Qwen3.5-9B"
   ],
   "pick_rank": 9
  },
  {
   "id": "Qwen/Qwen3.8-27B",
   "author": "Qwen",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B",
   "url": "https://huggingface.co/Qwen/Qwen3.8-27B",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 17388,
   "downloads": 6768654,
   "trending_score": 327.0,
   "created_at": "2026-08-05T08:22:59.000Z",
   "last_modified": null,
   "age_days": 66.24,
   "like_velocity": 262.5,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5"
   ],
   "rank_trending": 10,
   "score_breakdown": {
    "momentum": 0.847,
    "velocity": 0.983,
    "recency": 0.009,
    "originality": 1.0,
    "rarity": 0.735
   },
   "score": 76.7,
   "rank_prev": 12,
   "is_new_entry": false,
   "rank_change": 2,
   "reasons": [
    "🔥 平均每天 +262 讚",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 5
  },
  {
   "id": "convaiinnovations/laya",
   "author": "convaiinnovations",
   "author_fullname": null,
   "author_followers": null,
   "name": "laya",
   "url": "https://huggingface.co/convaiinnovations/laya",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 5450,
   "downloads": 42936,
   "trending_score": 314.0,
   "created_at": "2026-09-18T05:05:55.000Z",
   "last_modified": null,
   "age_days": 22.38,
   "like_velocity": 243.5,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "laya",
    "system-one",
    "calibrated-decisions",
    "rlcd",
    "classification",
    "routing"
   ],
   "rank_trending": 11,
   "score_breakdown": {
    "momentum": 0.831,
    "velocity": 0.966,
    "recency": 0.202,
    "originality": 1.0,
    "rarity": 0.941
   },
   "score": 80.7,
   "rank_prev": 11,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🔥 平均每天 +244 讚",
    "🧭 今日榜單少見的任務：文字分類",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 2
  },
  {
   "id": "canberkkkkkk/ema-lightning",
   "author": "canberkkkkkk",
   "author_fullname": null,
   "author_followers": null,
   "name": "ema-lightning",
   "url": "https://huggingface.co/canberkkkkkk/ema-lightning",
   "pipeline_tag": "text-to-speech",
   "task_zh": "語音合成（TTS）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": null,
   "likes": 327,
   "downloads": 15710,
   "trending_score": 297.0,
   "created_at": "2026-10-01T14:18:49.000Z",
   "last_modified": null,
   "age_days": 9.0,
   "like_velocity": 36.3,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2405.14867"
   ],
   "languages": [
    "tr"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "ema-lightning",
    "tts",
    "turkish",
    "speech-synthesis",
    "flow-matching"
   ],
   "rank_trending": 12,
   "score_breakdown": {
    "momentum": 0.814,
    "velocity": 0.576,
    "recency": 0.526,
    "originality": 1.0,
    "rarity": 0.971
   },
   "score": 75.5,
   "rank_prev": 13,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🧭 今日榜單少見的任務：語音合成（TTS）",
    "📄 附論文 arXiv:2405.14867",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 7
  },
  {
   "id": "Cactus-Compute/whistle",
   "author": "Cactus-Compute",
   "author_fullname": null,
   "author_followers": null,
   "name": "whistle",
   "url": "https://huggingface.co/Cactus-Compute/whistle",
   "pipeline_tag": "automatic-speech-recognition",
   "task_zh": "語音辨識（ASR）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": "cactus-needle",
   "likes": 294,
   "downloads": 12816,
   "trending_score": 264.0,
   "created_at": "2026-09-30T17:13:26.000Z",
   "last_modified": null,
   "age_days": 9.87,
   "like_velocity": 29.8,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "de",
    "fr",
    "es",
    "it",
    "nl",
    "pl"
   ],
   "n_languages": 7,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "whistle",
    "speech-recognition",
    "speech-to-text",
    "on-device",
    "edge",
    "quantization"
   ],
   "rank_trending": 13,
   "score_breakdown": {
    "momentum": 0.797,
    "velocity": 0.492,
    "recency": 0.494,
    "originality": 1.0,
    "rarity": 0.912
   },
   "score": 71.7,
   "rank_prev": 26,
   "is_new_entry": false,
   "rank_change": 13,
   "reasons": [
    "📈 排名上升 13 名",
    "📱 強調裝置端推論",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 8
  },
  {
   "id": "LiquidAI/d1-3B",
   "author": "LiquidAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "d1-3B",
   "url": "https://huggingface.co/LiquidAI/d1-3B",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 253,
   "downloads": 9088,
   "trending_score": 250.0,
   "created_at": "2026-10-05T09:55:28.000Z",
   "last_modified": null,
   "age_days": 5.18,
   "like_velocity": 48.9,
   "params_b": 3.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2511.23404"
   ],
   "languages": [
    "ar",
    "zh",
    "en",
    "fr",
    "de",
    "hi",
    "id",
    "it"
   ],
   "n_languages": 16,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "LiquidAI/LFM2.5-VL-3B",
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "lfm2_vl",
    "liquid",
    "lfm2.5",
    "edge",
    "decision",
    "classification"
   ],
   "rank_trending": 14,
   "score_breakdown": {
    "momentum": 0.78,
    "velocity": 0.661,
    "recency": 0.691,
    "originality": 0.45,
    "rarity": 0.735
   },
   "score": 68.3,
   "rank_prev": 50,
   "is_new_entry": false,
   "rank_change": 36,
   "reasons": [
    "📈 排名上升 36 名",
    "⏱️ 5 天前才發布",
    "🪶 僅 3B 參數，適合筆電／裝置端",
    "📄 附論文 arXiv:2511.23404",
    "🌏 支援 16 種語言"
   ],
   "pick_rank": null
  },
  {
   "id": "ConwayResearch/Underdog-Saluki-27B-1.0",
   "author": "ConwayResearch",
   "author_fullname": null,
   "author_followers": null,
   "name": "Underdog-Saluki-27B-1.0",
   "url": "https://huggingface.co/ConwayResearch/Underdog-Saluki-27B-1.0",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "gguf",
   "likes": 237,
   "downloads": 59191,
   "trending_score": 232.0,
   "created_at": "2026-10-08T01:47:26.000Z",
   "last_modified": null,
   "age_days": 2.52,
   "like_velocity": 94.1,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "llama.cpp",
    "2-bit",
    "tool-calling",
    "function-calling",
    "agents",
    "qwen3.8"
   ],
   "rank_trending": 15,
   "score_breakdown": {
    "momentum": 0.763,
    "velocity": 0.814,
    "recency": 0.835,
    "originality": 0.0,
    "rarity": 0.912
   },
   "score": 68.7,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 3 天前才發布",
    "🔥 平均每天 +94 讚",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF"
   ],
   "pick_rank": null
  },
  {
   "id": "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
   "author": "ISTA-DASLab",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
   "url": "https://huggingface.co/ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 764,
   "downloads": 3922328,
   "trending_score": 229.0,
   "created_at": "2026-09-07T09:41:37.000Z",
   "last_modified": null,
   "age_days": 33.19,
   "like_velocity": 23.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-Flash-Next",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gsq",
    "rco",
    "quantization",
    "mixed-precision",
    "ist-daslab",
    "moe"
   ],
   "rank_trending": 16,
   "score_breakdown": {
    "momentum": 0.746,
    "velocity": 0.373,
    "recency": 0.093,
    "originality": 0.0,
    "rarity": 0.735
   },
   "score": 44.2,
   "rank_prev": 14,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "🧩 MoE 混合專家架構",
    "📄 附論文 arXiv:2604.18556",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-Flash-Next"
   ],
   "pick_rank": null
  },
  {
   "id": "unsloth/embeddinggemma-2-GGUF",
   "author": "unsloth",
   "author_fullname": null,
   "author_followers": null,
   "name": "embeddinggemma-2-GGUF",
   "url": "https://huggingface.co/unsloth/embeddinggemma-2-GGUF",
   "pipeline_tag": "feature-extraction",
   "task_zh": "特徵萃取 / 嵌入",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": null,
   "likes": 221,
   "downloads": 50551,
   "trending_score": 217.0,
   "created_at": "2026-10-06T10:58:50.000Z",
   "last_modified": null,
   "age_days": 4.14,
   "like_velocity": 53.4,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "google/embeddinggemma-2",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "embedding",
    "multimodal-embedding",
    "multimodal",
    "vision",
    "audio"
   ],
   "rank_trending": 17,
   "score_breakdown": {
    "momentum": 0.729,
    "velocity": 0.695,
    "recency": 0.744,
    "originality": 0.0,
    "rarity": 0.971
   },
   "score": 63.7,
   "rank_prev": 21,
   "is_new_entry": false,
   "rank_change": 4,
   "reasons": [
    "⏱️ 4 天前才發布",
    "🧭 今日榜單少見的任務：特徵萃取 / 嵌入",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 google/embeddinggemma-2"
   ],
   "pick_rank": null
  },
  {
   "id": "Qwen/Qwen-Image-2.1",
   "author": "Qwen",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1",
   "url": "https://huggingface.co/Qwen/Qwen-Image-2.1",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 3181,
   "downloads": 128839,
   "trending_score": 201.0,
   "created_at": "2026-09-14T03:47:26.000Z",
   "last_modified": null,
   "age_days": 26.43,
   "like_velocity": 120.3,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen",
    "image-generation",
    "image-editing",
    "rgba"
   ],
   "rank_trending": 18,
   "score_breakdown": {
    "momentum": 0.712,
    "velocity": 0.881,
    "recency": 0.151,
    "originality": 1.0,
    "rarity": 0.882
   },
   "score": 73.0,
   "rank_prev": 15,
   "is_new_entry": false,
   "rank_change": -3,
   "reasons": [
    "🔥 平均每天 +120 讚"
   ],
   "pick_rank": null
  },
  {
   "id": "Qwen/Qwen3.8-Flash-Next",
   "author": "Qwen",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next",
   "url": "https://huggingface.co/Qwen/Qwen3.8-Flash-Next",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 6070,
   "downloads": 1798393,
   "trending_score": 165.0,
   "created_at": "2026-08-24T08:24:59.000Z",
   "last_modified": null,
   "age_days": 47.24,
   "like_velocity": 128.5,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen4_exp"
   ],
   "rank_trending": 19,
   "score_breakdown": {
    "momentum": 0.695,
    "velocity": 0.898,
    "recency": 0.034,
    "originality": 1.0,
    "rarity": 0.735
   },
   "score": 69.6,
   "rank_prev": 19,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🔥 平均每天 +128 讚"
   ],
   "pick_rank": null
  },
  {
   "id": "DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NEO-CODER-MAX-MTP-GGUF",
   "author": "DavidAU",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NEO-CODER-MAX-MTP-GGUF",
   "url": "https://huggingface.co/DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NEO-CODER-MAX-MTP-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": null,
   "likes": 1622,
   "downloads": 1960274,
   "trending_score": 160.0,
   "created_at": "2026-09-01T07:01:09.000Z",
   "last_modified": null,
   "age_days": 39.3,
   "like_velocity": 41.3,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NM-DAU",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "unsloth",
    "fine tune",
    "heretic",
    "uncensored",
    "abliterated"
   ],
   "rank_trending": 20,
   "score_breakdown": {
    "momentum": 0.678,
    "velocity": 0.61,
    "recency": 0.06,
    "originality": 0.0,
    "rarity": 0.735
   },
   "score": 47.2,
   "rank_prev": 24,
   "is_new_entry": false,
   "rank_change": 4,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 DavidAU/Qwen3.8-27B-TURBO-Fable-Cold-Fusion-735-882-Heretic-Uncensored-NM-DAU",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "Alissonerdx/BFS-Best-Face-Swap",
   "author": "Alissonerdx",
   "author_fullname": null,
   "author_followers": null,
   "name": "BFS-Best-Face-Swap",
   "url": "https://huggingface.co/Alissonerdx/BFS-Best-Face-Swap",
   "pipeline_tag": "image-to-image",
   "task_zh": "圖生圖 / 影像編輯",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 1349,
   "downloads": 248475,
   "trending_score": 156.0,
   "created_at": "2025-11-07T09:50:28.000Z",
   "last_modified": null,
   "age_days": 337.18,
   "like_velocity": 4.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "lora",
    "qwen-image",
    "qwen-image-2.1",
    "qwen-image-edit",
    "face-swap",
    "head-swap"
   ],
   "rank_trending": 21,
   "score_breakdown": {
    "momentum": 0.661,
    "velocity": 0.0,
    "recency": 0.0,
    "originality": 0.35,
    "rarity": 0.941
   },
   "score": 37.8,
   "rank_prev": 20,
   "is_new_entry": false,
   "rank_change": -1,
   "reasons": [
    "🧭 今日榜單少見的任務：圖生圖 / 影像編輯",
    "✅ 寬鬆授權（mit）",
    "🔗 LoRA 掛載於 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "nerkyor/Qwen3.8-27B-Coder390-EfficientThink-Opus5.5-GPT6Astra-Grok4.7-DSV4Pro-K3-SFT-RLOO-MTP-DFlash2",
   "author": "nerkyor",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-Coder390-EfficientThink-Opus5.5-GPT6Astra-Grok4.7-DSV4Pro-K3-SFT-RLOO-MTP-DFlash2",
   "url": "https://huggingface.co/nerkyor/Qwen3.8-27B-Coder390-EfficientThink-Opus5.5-GPT6Astra-Grok4.7-DSV4Pro-K3-SFT-RLOO-MTP-DFlash2",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": null,
   "likes": 162,
   "downloads": 42336,
   "trending_score": 155.0,
   "created_at": "2026-10-04T10:44:11.000Z",
   "last_modified": null,
   "age_days": 6.15,
   "like_velocity": 26.4,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "nerkyor/Qwen3.8-27B-EfficientThink-Uncensored-K3-Opus5-Grok4.6-GPT5.6Sol-SFT-SimPO-DFlash2",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "qwen3.8",
    "efficient-thinking",
    "reasoning",
    "coding",
    "uncensored"
   ],
   "rank_trending": 22,
   "score_breakdown": {
    "momentum": 0.644,
    "velocity": 0.441,
    "recency": 0.644,
    "originality": 0.0,
    "rarity": 0.735
   },
   "score": 50.6,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 6 天前才發布",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 nerkyor/Qwen3.8-27B-EfficientThink-Uncensored-K3-Opus5-Grok4.6-GPT5.6Sol-SFT-SimPO-DFlash2",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "prism-ml/Ternary-Bonsai-2-27B-gguf",
   "author": "prism-ml",
   "author_fullname": null,
   "author_followers": null,
   "name": "Ternary-Bonsai-2-27B-gguf",
   "url": "https://huggingface.co/prism-ml/Ternary-Bonsai-2-27B-gguf",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "llama.cpp",
   "likes": 2582,
   "downloads": 4457576,
   "trending_score": 154.0,
   "created_at": "2026-09-16T23:40:56.000Z",
   "last_modified": null,
   "age_days": 23.61,
   "like_velocity": 109.4,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "gguf",
    "ternary",
    "2-bit",
    "llama-cpp",
    "cuda",
    "metal"
   ],
   "rank_trending": 23,
   "score_breakdown": {
    "momentum": 0.627,
    "velocity": 0.847,
    "recency": 0.185,
    "originality": 0.0,
    "rarity": 0.912
   },
   "score": 55.0,
   "rank_prev": 23,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🔥 平均每天 +109 讚",
    "📱 強調裝置端推論",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "deepseek-ai/DeepSeek-V4.1-Flash",
   "author": "deepseek-ai",
   "author_fullname": null,
   "author_followers": null,
   "name": "DeepSeek-V4.1-Flash",
   "url": "https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 4310,
   "downloads": 1355278,
   "trending_score": 149.0,
   "created_at": "2026-09-10T02:17:58.000Z",
   "last_modified": null,
   "age_days": 30.5,
   "like_velocity": 141.3,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "deepseek_v41",
    "text-generation",
    "8-bit",
    "fp8"
   ],
   "rank_trending": 24,
   "score_breakdown": {
    "momentum": 0.61,
    "velocity": 0.915,
    "recency": 0.113,
    "originality": 1.0,
    "rarity": 0.735
   },
   "score": 68.3,
   "rank_prev": 22,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "🔥 平均每天 +141 讚",
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": null
  },
  {
   "id": "ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF",
   "author": "ISTA-DASLab",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-GSQ-RCO-GGUF",
   "url": "https://huggingface.co/ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 2105,
   "downloads": 1484655,
   "trending_score": 144.0,
   "created_at": "2026-08-28T18:38:03.000Z",
   "last_modified": null,
   "age_days": 42.82,
   "like_velocity": 49.2,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gsq",
    "rco",
    "quantization",
    "mixed-precision",
    "ist-daslab",
    "multimodal"
   ],
   "rank_trending": 25,
   "score_breakdown": {
    "momentum": 0.585,
    "velocity": 0.678,
    "recency": 0.047,
    "originality": 0.0,
    "rarity": 0.735
   },
   "score": 45.5,
   "rank_prev": 29,
   "is_new_entry": false,
   "rank_change": 4,
   "reasons": [
    "📄 附論文 arXiv:2604.18556",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "SC117/Qwen3.8-Flash-Next-GSQ-RCO-abliterated-GGUF",
   "author": "SC117",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next-GSQ-RCO-abliterated-GGUF",
   "url": "https://huggingface.co/SC117/Qwen3.8-Flash-Next-GSQ-RCO-abliterated-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 182,
   "downloads": 765376,
   "trending_score": 144.0,
   "created_at": "2026-10-02T03:42:33.000Z",
   "last_modified": null,
   "age_days": 8.44,
   "like_velocity": 21.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "llama-cpp",
    "abliterated",
    "uncensored",
    "quantization",
    "tensor-transplant",
    "gsq"
   ],
   "rank_trending": 26,
   "score_breakdown": {
    "momentum": 0.585,
    "velocity": 0.339,
    "recency": 0.547,
    "originality": 0.0,
    "rarity": 0.735
   },
   "score": 44.5,
   "rank_prev": 33,
   "is_new_entry": false,
   "rank_change": 7,
   "reasons": [
    "📈 排名上升 7 名",
    "🧩 MoE 混合專家架構",
    "📄 附論文 arXiv:2604.18556",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF"
   ],
   "pick_rank": null
  },
  {
   "id": "FrancisRing/Prism",
   "author": "FrancisRing",
   "author_fullname": null,
   "author_followers": null,
   "name": "Prism",
   "url": "https://huggingface.co/FrancisRing/Prism",
   "pipeline_tag": "image-to-video",
   "task_zh": "圖生影片",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 142,
   "downloads": 0,
   "trending_score": 140.0,
   "created_at": "2026-09-24T09:58:12.000Z",
   "last_modified": null,
   "age_days": 16.18,
   "like_velocity": 8.8,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [
    "2610.05416"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "video-generation",
    "video diffusion transformer",
    "joint-video-audio-generation",
    "sparse-attention",
    "high-resolution"
   ],
   "rank_trending": 27,
   "score_breakdown": {
    "momentum": 0.559,
    "velocity": 0.085,
    "recency": 0.315,
    "originality": 1.0,
    "rarity": 0.941
   },
   "score": 50.8,
   "rank_prev": 40,
   "is_new_entry": false,
   "rank_change": 13,
   "reasons": [
    "📈 排名上升 13 名",
    "🧭 今日榜單少見的任務：圖生影片",
    "📄 附論文 arXiv:2610.05416",
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": 12
  },
  {
   "id": "orcarouter/Qwen3.8-Flash-Next-Uncensored-GGUF",
   "author": "orcarouter",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next-Uncensored-GGUF",
   "url": "https://huggingface.co/orcarouter/Qwen3.8-Flash-Next-Uncensored-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 716,
   "downloads": 520450,
   "trending_score": 139.0,
   "created_at": "2026-08-26T11:15:13.000Z",
   "last_modified": null,
   "age_days": 45.12,
   "like_velocity": 15.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-Flash-Next",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "abliterated",
    "uncensored",
    "qwen",
    "qwen3.8",
    "qwen4",
    "flash-next"
   ],
   "rank_trending": 28,
   "score_breakdown": {
    "momentum": 0.534,
    "velocity": 0.186,
    "recency": 0.04,
    "originality": 0.0,
    "rarity": 0.735
   },
   "score": 31.3,
   "rank_prev": 30,
   "is_new_entry": false,
   "rank_change": 2,
   "reasons": [
    "🧩 MoE 混合專家架構",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-Flash-Next",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "orcarouter/OrcaSAQ-2-Cyber-27B-Uncensored-GGUF",
   "author": "orcarouter",
   "author_fullname": null,
   "author_followers": null,
   "name": "OrcaSAQ-2-Cyber-27B-Uncensored-GGUF",
   "url": "https://huggingface.co/orcarouter/OrcaSAQ-2-Cyber-27B-Uncensored-GGUF",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "llama.cpp",
   "likes": 494,
   "downloads": 22667,
   "trending_score": 139.0,
   "created_at": "2026-09-26T03:37:50.000Z",
   "last_modified": null,
   "age_days": 14.44,
   "like_velocity": 34.2,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "orcarouter/Qwen3.8-27B-Uncensored",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "qwen",
    "qwen3.8",
    "qwen3_5",
    "orcasaq2",
    "quantization"
   ],
   "rank_trending": 29,
   "score_breakdown": {
    "momentum": 0.534,
    "velocity": 0.559,
    "recency": 0.356,
    "originality": 0.0,
    "rarity": 0.912
   },
   "score": 47.1,
   "rank_prev": 18,
   "is_new_entry": false,
   "rank_change": -11,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 orcarouter/Qwen3.8-27B-Uncensored",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "unsloth/Qwen3.8-27B-GGUF",
   "author": "unsloth",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-GGUF",
   "url": "https://huggingface.co/unsloth/Qwen3.8-27B-GGUF",
   "pipeline_tag": null,
   "task_zh": "未標註任務",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": null,
   "likes": 4994,
   "downloads": 6449020,
   "trending_score": 135.0,
   "created_at": "2026-08-13T08:28:40.000Z",
   "last_modified": null,
   "age_days": 58.24,
   "like_velocity": 85.7,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "qwen3_5",
    "unsloth",
    "imatrix"
   ],
   "rank_trending": 30,
   "score_breakdown": {
    "momentum": 0.508,
    "velocity": 0.78,
    "recency": 0.016,
    "originality": 0.0,
    "rarity": 0.3
   },
   "score": 40.5,
   "rank_prev": 38,
   "is_new_entry": false,
   "rank_change": 8,
   "reasons": [
    "📈 排名上升 8 名",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "facebook/sam3",
   "author": "facebook",
   "author_fullname": null,
   "author_followers": null,
   "name": "sam3",
   "url": "https://huggingface.co/facebook/sam3",
   "pipeline_tag": "mask-generation",
   "task_zh": "遮罩生成",
   "task_group": "vision",
   "task_group_zh": "電腦視覺",
   "library": "transformers",
   "likes": 3980,
   "downloads": 2128836,
   "trending_score": 129.0,
   "created_at": "2025-11-07T05:17:48.000Z",
   "last_modified": null,
   "age_days": 337.37,
   "like_velocity": 11.8,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "sam3_video",
    "feature-extraction",
    "sam3"
   ],
   "rank_trending": 31,
   "score_breakdown": {
    "momentum": 0.492,
    "velocity": 0.119,
    "recency": 0.0,
    "originality": 1.0,
    "rarity": 0.971
   },
   "score": 44.9,
   "rank_prev": 43,
   "is_new_entry": false,
   "rank_change": 12,
   "reasons": [
    "📈 排名上升 12 名",
    "🧭 今日榜單少見的任務：遮罩生成"
   ],
   "pick_rank": null
  },
  {
   "id": "pyannote/speaker-diarization-community-1",
   "author": "pyannote",
   "author_fullname": null,
   "author_followers": null,
   "name": "speaker-diarization-community-1",
   "url": "https://huggingface.co/pyannote/speaker-diarization-community-1",
   "pipeline_tag": "automatic-speech-recognition",
   "task_zh": "語音辨識（ASR）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": "pyannote-audio",
   "likes": 2711,
   "downloads": 5482899,
   "trending_score": 119.0,
   "created_at": "2025-04-15T21:31:35.000Z",
   "last_modified": null,
   "age_days": 542.7,
   "like_velocity": 5.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "cc-by-4.0",
   "permissive_license": true,
   "arxiv": [
    "2104.03603",
    "2111.14448",
    "2012.01477"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "pyannote",
    "pyannote-audio-pipeline",
    "audio",
    "voice",
    "speech",
    "speaker"
   ],
   "rank_trending": 32,
   "score_breakdown": {
    "momentum": 0.475,
    "velocity": 0.034,
    "recency": 0.0,
    "originality": 1.0,
    "rarity": 0.912
   },
   "score": 41.6,
   "rank_prev": 44,
   "is_new_entry": false,
   "rank_change": 12,
   "reasons": [
    "📈 排名上升 12 名",
    "📄 附論文 arXiv:2104.03603",
    "✅ 寬鬆授權（cc-by-4.0）"
   ],
   "pick_rank": null
  },
  {
   "id": "MiniMaxAI/MiniMax-H3",
   "author": "MiniMaxAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiniMax-H3",
   "url": "https://huggingface.co/MiniMaxAI/MiniMax-H3",
   "pipeline_tag": "image-text-to-video",
   "task_zh": "圖文生影片",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "minimax-h3",
   "likes": 6016,
   "downloads": 3596813,
   "trending_score": 114.0,
   "created_at": "2026-07-28T10:45:18.000Z",
   "last_modified": null,
   "age_days": 74.14,
   "like_velocity": 81.1,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "diffusers",
    "text-to-video",
    "image-to-video",
    "video-to-video",
    "text-to-audio-video",
    "image-to-audio-video"
   ],
   "rank_trending": 33,
   "score_breakdown": {
    "momentum": 0.458,
    "velocity": 0.763,
    "recency": 0.005,
    "originality": 1.0,
    "rarity": 0.941
   },
   "score": 59.6,
   "rank_prev": 32,
   "is_new_entry": false,
   "rank_change": -1,
   "reasons": [
    "🧭 今日榜單少見的任務：圖文生影片"
   ],
   "pick_rank": 10
  },
  {
   "id": "Infatoshi/GLM-5.3-UNCENSORED-EXL3-3.0bpw",
   "author": "Infatoshi",
   "author_fullname": null,
   "author_followers": null,
   "name": "GLM-5.3-UNCENSORED-EXL3-3.0bpw",
   "url": "https://huggingface.co/Infatoshi/GLM-5.3-UNCENSORED-EXL3-3.0bpw",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "exllamav3",
   "likes": 318,
   "downloads": 2509,
   "trending_score": 112.0,
   "created_at": "2026-10-01T03:42:00.000Z",
   "last_modified": null,
   "age_days": 9.44,
   "like_velocity": 33.7,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "dealignai/GLM-5.3-UNCENSORED-FP8",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "glm_moe_dsa",
    "exl3",
    "glm",
    "moe",
    "uncensored"
   ],
   "rank_trending": 34,
   "score_breakdown": {
    "momentum": 0.441,
    "velocity": 0.542,
    "recency": 0.51,
    "originality": 0.0,
    "rarity": 0.912
   },
   "score": 45.7,
   "rank_prev": 16,
   "is_new_entry": false,
   "rank_change": -18,
   "reasons": [
    "🧩 MoE 混合專家架構",
    "✅ 寬鬆授權（mit）",
    "🔗 量化轉檔自 dealignai/GLM-5.3-UNCENSORED-FP8",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "ausboss/Qwen-Image-2.1-Outfit-Swap-Consistency-LoRA",
   "author": "ausboss",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1-Outfit-Swap-Consistency-LoRA",
   "url": "https://huggingface.co/ausboss/Qwen-Image-2.1-Outfit-Swap-Consistency-LoRA",
   "pipeline_tag": "image-to-image",
   "task_zh": "圖生圖 / 影像編輯",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": null,
   "likes": 113,
   "downloads": 0,
   "trending_score": 108.0,
   "created_at": "2026-10-04T04:03:30.000Z",
   "last_modified": null,
   "age_days": 6.42,
   "like_velocity": 17.6,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "lora",
    "image-editing",
    "outfit-swap",
    "consistency",
    "virtual-try-on",
    "qwen-image"
   ],
   "rank_trending": 35,
   "score_breakdown": {
    "momentum": 0.424,
    "velocity": 0.22,
    "recency": 0.632,
    "originality": 0.35,
    "rarity": 0.941
   },
   "score": 44.5,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 6 天前才發布",
    "🧭 今日榜單少見的任務：圖生圖 / 影像編輯",
    "🔗 LoRA 掛載於 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "akatz-ai/MiniMax-H3-Character-Swap-LoRA",
   "author": "akatz-ai",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiniMax-H3-Character-Swap-LoRA",
   "url": "https://huggingface.co/akatz-ai/MiniMax-H3-Character-Swap-LoRA",
   "pipeline_tag": "video-to-video",
   "task_zh": "影片轉換",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusion-single-file",
   "likes": 387,
   "downloads": 36235,
   "trending_score": 106.0,
   "created_at": "2026-09-25T08:14:15.000Z",
   "last_modified": null,
   "age_days": 15.25,
   "like_velocity": 25.4,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Comfy-Org/MiniMax-H3",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "minimax-h3",
    "lora",
    "character-swap",
    "video-editing",
    "ref2va",
    "comfyui"
   ],
   "rank_trending": 36,
   "score_breakdown": {
    "momentum": 0.407,
    "velocity": 0.407,
    "recency": 0.336,
    "originality": 0.35,
    "rarity": 0.941
   },
   "score": 44.1,
   "rank_prev": 37,
   "is_new_entry": false,
   "rank_change": 1,
   "reasons": [
    "🧭 今日榜單少見的任務：影片轉換",
    "🔗 LoRA 掛載於 Comfy-Org/MiniMax-H3"
   ],
   "pick_rank": null
  },
  {
   "id": "HauhauCS/Qwen3.8-27B-Uncensored-HauhauCS-Aggressive-MTP-GGUF",
   "author": "HauhauCS",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-Uncensored-HauhauCS-Aggressive-MTP-GGUF",
   "url": "https://huggingface.co/HauhauCS/Qwen3.8-27B-Uncensored-HauhauCS-Aggressive-MTP-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": null,
   "likes": 1729,
   "downloads": 2023752,
   "trending_score": 104.0,
   "created_at": "2026-08-17T15:15:19.000Z",
   "last_modified": null,
   "age_days": 53.96,
   "like_velocity": 32.0,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "uncensored",
    "qwen3.8",
    "multimodal",
    "vision",
    "mtp"
   ],
   "rank_trending": 37,
   "score_breakdown": {
    "momentum": 0.39,
    "velocity": 0.525,
    "recency": 0.021,
    "originality": 0.0,
    "rarity": 0.735
   },
   "score": 34.5,
   "rank_prev": 54,
   "is_new_entry": false,
   "rank_change": 17,
   "reasons": [
    "📈 排名上升 17 名",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-Coder-GGUF",
   "author": "ISTA-DASLab",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next-GSQ-RCO-Coder-GGUF",
   "url": "https://huggingface.co/ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-Coder-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 367,
   "downloads": 650945,
   "trending_score": 102.0,
   "created_at": "2026-09-26T09:42:51.000Z",
   "last_modified": null,
   "age_days": 14.19,
   "like_velocity": 25.9,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-Flash-Next",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gsq",
    "rco",
    "quantization",
    "pruning",
    "expert-pruning",
    "mixed-precision"
   ],
   "rank_trending": 38,
   "score_breakdown": {
    "momentum": 0.373,
    "velocity": 0.424,
    "recency": 0.363,
    "originality": 0.0,
    "rarity": 0.735
   },
   "score": 36.4,
   "rank_prev": 28,
   "is_new_entry": false,
   "rank_change": -10,
   "reasons": [
    "🧩 MoE 混合專家架構",
    "📄 附論文 arXiv:2604.18556",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-Flash-Next"
   ],
   "pick_rank": null
  },
  {
   "id": "LiquidAI/d1-omni-600M",
   "author": "LiquidAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "d1-omni-600M",
   "url": "https://huggingface.co/LiquidAI/d1-omni-600M",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 100,
   "downloads": 10030,
   "trending_score": 99.0,
   "created_at": "2026-10-05T17:18:48.000Z",
   "last_modified": null,
   "age_days": 4.87,
   "like_velocity": 20.5,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2511.23404"
   ],
   "languages": [
    "en",
    "de",
    "es",
    "fr",
    "it",
    "nl",
    "pl",
    "pt"
   ],
   "n_languages": 15,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "LiquidAI/LFM2.5-Encoder-350M",
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "d1_omni",
    "feature-extraction",
    "liquid",
    "lfm2.5",
    "edge",
    "decision"
   ],
   "rank_trending": 39,
   "score_breakdown": {
    "momentum": 0.356,
    "velocity": 0.322,
    "recency": 0.706,
    "originality": 0.45,
    "rarity": 0.735
   },
   "score": 45.2,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 5 天前才發布",
    "📱 強調裝置端推論",
    "📄 附論文 arXiv:2511.23404",
    "🌏 支援 15 種語言"
   ],
   "pick_rank": null
  },
  {
   "id": "ukisai/Swift-1.5-Qwen3.8-27B-GSQ-RCO-GGUF",
   "author": "ukisai",
   "author_fullname": null,
   "author_followers": null,
   "name": "Swift-1.5-Qwen3.8-27B-GSQ-RCO-GGUF",
   "url": "https://huggingface.co/ukisai/Swift-1.5-Qwen3.8-27B-GSQ-RCO-GGUF",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "gguf",
   "likes": 319,
   "downloads": 713744,
   "trending_score": 98.0,
   "created_at": "2026-09-24T13:13:45.000Z",
   "last_modified": null,
   "age_days": 16.04,
   "like_velocity": 19.9,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "ukisai/Swift-1.5-Qwen3.8-27b",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "llama.cpp",
    "qwen3_8",
    "gsq",
    "rco",
    "reasoning",
    "efficient-thinking"
   ],
   "rank_trending": 40,
   "score_breakdown": {
    "momentum": 0.331,
    "velocity": 0.288,
    "recency": 0.318,
    "originality": 0.0,
    "rarity": 0.912
   },
   "score": 32.7,
   "rank_prev": 45,
   "is_new_entry": false,
   "rank_change": 5,
   "reasons": [
    "📈 排名上升 5 名",
    "📄 附論文 arXiv:2604.18556",
    "🔗 量化轉檔自 ukisai/Swift-1.5-Qwen3.8-27b"
   ],
   "pick_rank": null
  },
  {
   "id": "perplexity-ai/pplx-decider-v1.1-27b",
   "author": "perplexity-ai",
   "author_fullname": null,
   "author_followers": null,
   "name": "pplx-decider-v1.1-27b",
   "url": "https://huggingface.co/perplexity-ai/pplx-decider-v1.1-27b",
   "pipeline_tag": "text-classification",
   "task_zh": "文字分類",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "pytorch",
   "likes": 99,
   "downloads": 1807,
   "trending_score": 98.0,
   "created_at": "2026-10-05T12:32:27.000Z",
   "last_modified": null,
   "age_days": 5.07,
   "like_velocity": 19.5,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5",
    "classification",
    "multimodal",
    "custom-code",
    "decider",
    "decision-model"
   ],
   "rank_trending": 41,
   "score_breakdown": {
    "momentum": 0.331,
    "velocity": 0.271,
    "recency": 0.696,
    "originality": 0.45,
    "rarity": 0.941
   },
   "score": 45.0,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 5 天前才發布",
    "🧭 今日榜單少見的任務：文字分類",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 Qwen/Qwen3.8-27B"
   ],
   "pick_rank": null
  },
  {
   "id": "speridlabs/iris-3b",
   "author": "speridlabs",
   "author_fullname": null,
   "author_followers": null,
   "name": "iris-3b",
   "url": "https://huggingface.co/speridlabs/iris-3b",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "pytorch",
   "likes": 96,
   "downloads": 233,
   "trending_score": 96.0,
   "created_at": "2026-10-05T14:51:15.000Z",
   "last_modified": null,
   "age_days": 4.97,
   "like_velocity": 19.3,
   "params_b": 3.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2610.09450"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "diffusion",
    "pixel-space",
    "flow-matching",
    "general-vision-learner",
    "vision-foundation-model",
    "depth-estimation"
   ],
   "rank_trending": 42,
   "score_breakdown": {
    "momentum": 0.297,
    "velocity": 0.254,
    "recency": 0.701,
    "originality": 1.0,
    "rarity": 0.882
   },
   "score": 51.1,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 5 天前才發布",
    "🪶 僅 3B 參數，適合筆電／裝置端",
    "📄 附論文 arXiv:2610.09450",
    "✅ 寬鬆授權（apache-2.0）"
   ],
   "pick_rank": 11
  },
  {
   "id": "AtomicChat/Qwen-Image-2.1-Turbo-Uncensored-GGUF",
   "author": "AtomicChat",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1-Turbo-Uncensored-GGUF",
   "url": "https://huggingface.co/AtomicChat/Qwen-Image-2.1-Turbo-Uncensored-GGUF",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "gguf",
   "likes": 102,
   "downloads": 7314,
   "trending_score": 96.0,
   "created_at": "2026-10-09T16:30:48.000Z",
   "last_modified": null,
   "age_days": 0.9,
   "like_velocity": 112.8,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3-VL-8B-Instruct",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "atomic-chat",
    "qwen",
    "qwen-image",
    "qwen3-vl",
    "text-encoder",
    "stable-diffusion.cpp"
   ],
   "rank_trending": 43,
   "score_breakdown": {
    "momentum": 0.297,
    "velocity": 0.864,
    "recency": 0.938,
    "originality": 0.0,
    "rarity": 0.882
   },
   "score": 54.9,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 22 小時前才發布",
    "🔥 平均每天 +113 讚",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3-VL-8B-Instruct"
   ],
   "pick_rank": null
  },
  {
   "id": "Comfy-Org/Qwen-Image-2.1",
   "author": "Comfy-Org",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1",
   "url": "https://huggingface.co/Comfy-Org/Qwen-Image-2.1",
   "pipeline_tag": null,
   "task_zh": "未標註任務",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": "diffusion-single-file",
   "likes": 1033,
   "downloads": 8224717,
   "trending_score": 95.0,
   "created_at": "2026-09-15T19:41:09.000Z",
   "last_modified": null,
   "age_days": 24.77,
   "like_velocity": 41.7,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "comfyui"
   ],
   "rank_trending": 44,
   "score_breakdown": {
    "momentum": 0.263,
    "velocity": 0.627,
    "recency": 0.17,
    "originality": 0.45,
    "rarity": 0.3
   },
   "score": 37.2,
   "rank_prev": 58,
   "is_new_entry": false,
   "rank_change": 14,
   "reasons": [
    "📈 排名上升 14 名",
    "🔗 微調自 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "Viggle/Qwen-Image-2.1-viggle-turbo",
   "author": "Viggle",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen-Image-2.1-viggle-turbo",
   "url": "https://huggingface.co/Viggle/Qwen-Image-2.1-viggle-turbo",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "diffusers",
   "likes": 702,
   "downloads": 442620,
   "trending_score": 95.0,
   "created_at": "2026-09-22T04:14:56.000Z",
   "last_modified": null,
   "age_days": 18.42,
   "like_velocity": 38.1,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen-Image-2.1",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "lora",
    "image-to-image",
    "image-editing",
    "distillation",
    "turbo"
   ],
   "rank_trending": 45,
   "score_breakdown": {
    "momentum": 0.263,
    "velocity": 0.593,
    "recency": 0.268,
    "originality": 0.0,
    "rarity": 0.882
   },
   "score": 36.9,
   "rank_prev": 27,
   "is_new_entry": false,
   "rank_change": -18,
   "reasons": [
    "🔗 量化轉檔自 Qwen/Qwen-Image-2.1"
   ],
   "pick_rank": null
  },
  {
   "id": "Lightricks/LTX-2.5-22b-IC-LoRA-Alpha-Gen",
   "author": "Lightricks",
   "author_fullname": null,
   "author_followers": null,
   "name": "LTX-2.5-22b-IC-LoRA-Alpha-Gen",
   "url": "https://huggingface.co/Lightricks/LTX-2.5-22b-IC-LoRA-Alpha-Gen",
   "pipeline_tag": "video-to-video",
   "task_zh": "影片轉換",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "ltx",
   "likes": 143,
   "downloads": 7440,
   "trending_score": 93.0,
   "created_at": "2026-09-28T20:01:47.000Z",
   "last_modified": null,
   "age_days": 11.76,
   "like_velocity": 12.2,
   "params_b": 22.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "Lightricks/LTX-2.5",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "alpha-matte",
    "matting",
    "background-removal",
    "ic-lora",
    "ltx-2.5",
    "vfx"
   ],
   "rank_trending": 46,
   "score_breakdown": {
    "momentum": 0.237,
    "velocity": 0.144,
    "recency": 0.432,
    "originality": 0.35,
    "rarity": 0.941
   },
   "score": 33.0,
   "rank_prev": 46,
   "is_new_entry": false,
   "rank_change": 0,
   "reasons": [
    "🧭 今日榜單少見的任務：影片轉換",
    "🔗 LoRA 掛載於 Lightricks/LTX-2.5"
   ],
   "pick_rank": null
  },
  {
   "id": "moondream/parakeet-redux",
   "author": "moondream",
   "author_fullname": null,
   "author_followers": null,
   "name": "parakeet-redux",
   "url": "https://huggingface.co/moondream/parakeet-redux",
   "pipeline_tag": "automatic-speech-recognition",
   "task_zh": "語音辨識（ASR）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": null,
   "likes": 271,
   "downloads": 15594,
   "trending_score": 92.0,
   "created_at": "2026-09-18T11:02:15.000Z",
   "last_modified": null,
   "age_days": 22.13,
   "like_velocity": 12.2,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "cc-by-4.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "de",
    "fr",
    "es",
    "it",
    "pt",
    "ru",
    "uk"
   ],
   "n_languages": 25,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "parakeet_tdt",
    "ternary",
    "parakeet",
    "tdt",
    "speech-recognition",
    "cpu"
   ],
   "rank_trending": 47,
   "score_breakdown": {
    "momentum": 0.22,
    "velocity": 0.144,
    "recency": 0.206,
    "originality": 1.0,
    "rarity": 0.912
   },
   "score": 38.5,
   "rank_prev": 60,
   "is_new_entry": false,
   "rank_change": 13,
   "reasons": [
    "📈 排名上升 13 名",
    "📱 強調裝置端推論",
    "🌏 支援 25 種語言",
    "✅ 寬鬆授權（cc-by-4.0）"
   ],
   "pick_rank": null
  },
  {
   "id": "pablodawson/MiniMax-H3-360-Orbit-LoRA",
   "author": "pablodawson",
   "author_fullname": null,
   "author_followers": null,
   "name": "MiniMax-H3-360-Orbit-LoRA",
   "url": "https://huggingface.co/pablodawson/MiniMax-H3-360-Orbit-LoRA",
   "pipeline_tag": "image-text-to-video",
   "task_zh": "圖文生影片",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": "minimax-h3",
   "likes": 274,
   "downloads": 12957,
   "trending_score": 88.0,
   "created_at": "2026-09-27T04:05:33.000Z",
   "last_modified": null,
   "age_days": 13.42,
   "like_velocity": 20.4,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "adapter",
   "derivative_zh": "LoRA / Adapter",
   "base_model": "MiniMaxAI/MiniMax-H3",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "lora",
    "image-to-video",
    "first-last-frame",
    "flf2v",
    "camera-control",
    "orbit"
   ],
   "rank_trending": 48,
   "score_breakdown": {
    "momentum": 0.203,
    "velocity": 0.305,
    "recency": 0.383,
    "originality": 0.35,
    "rarity": 0.941
   },
   "score": 35.2,
   "rank_prev": 34,
   "is_new_entry": false,
   "rank_change": -14,
   "reasons": [
    "🧭 今日榜單少見的任務：圖文生影片",
    "🔗 LoRA 掛載於 MiniMaxAI/MiniMax-H3"
   ],
   "pick_rank": null
  },
  {
   "id": "zai-org/GLM-5.3-Flash",
   "author": "zai-org",
   "author_fullname": null,
   "author_followers": null,
   "name": "GLM-5.3-Flash",
   "url": "https://huggingface.co/zai-org/GLM-5.3-Flash",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 2781,
   "downloads": 6479110,
   "trending_score": 87.0,
   "created_at": "2026-08-25T06:43:14.000Z",
   "last_modified": null,
   "age_days": 46.31,
   "like_velocity": 60.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [
    "2602.15763"
   ],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "glm5_next",
    "fp8"
   ],
   "rank_trending": 49,
   "score_breakdown": {
    "momentum": 0.186,
    "velocity": 0.729,
    "recency": 0.037,
    "originality": 1.0,
    "rarity": 0.735
   },
   "score": 47.6,
   "rank_prev": 55,
   "is_new_entry": false,
   "rank_change": 6,
   "reasons": [
    "📈 排名上升 6 名",
    "📄 附論文 arXiv:2602.15763",
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": null
  },
  {
   "id": "microsoft/FrogNano-4B-2609",
   "author": "microsoft",
   "author_fullname": null,
   "author_followers": null,
   "name": "FrogNano-4B-2609",
   "url": "https://huggingface.co/microsoft/FrogNano-4B-2609",
   "pipeline_tag": null,
   "task_zh": "未標註任務",
   "task_group": "other",
   "task_group_zh": "其他",
   "library": null,
   "likes": 141,
   "downloads": 1237,
   "trending_score": 86.0,
   "created_at": "2026-09-17T00:13:57.000Z",
   "last_modified": null,
   "age_days": 23.58,
   "like_velocity": 6.0,
   "params_b": 4.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "qwen3_5"
   ],
   "rank_trending": 50,
   "score_breakdown": {
    "momentum": 0.161,
    "velocity": 0.051,
    "recency": 0.186,
    "originality": 1.0,
    "rarity": 0.3
   },
   "score": 27.7,
   "rank_prev": 36,
   "is_new_entry": false,
   "rank_change": -14,
   "reasons": [
    "🪶 僅 4B 參數，適合筆電／裝置端",
    "✅ 寬鬆授權（mit）"
   ],
   "pick_rank": null
  },
  {
   "id": "FermionResearch/Phonon-2",
   "author": "FermionResearch",
   "author_fullname": null,
   "author_followers": null,
   "name": "Phonon-2",
   "url": "https://huggingface.co/FermionResearch/Phonon-2",
   "pipeline_tag": "automatic-speech-recognition",
   "task_zh": "語音辨識（ASR）",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": "mlx",
   "likes": 283,
   "downloads": 4274,
   "trending_score": 86.0,
   "created_at": "2026-09-28T11:48:47.000Z",
   "last_modified": null,
   "age_days": 12.1,
   "like_velocity": 23.4,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "cc-by-4.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "nvidia/parakeet-tdt-0.6b-v3",
   "safety_removed": false,
   "on_device": true,
   "tags": [
    "parakeet_tdt_five_value",
    "apple-silicon",
    "speech-to-text",
    "asr",
    "stt",
    "low-bit"
   ],
   "rank_trending": 51,
   "score_breakdown": {
    "momentum": 0.161,
    "velocity": 0.39,
    "recency": 0.421,
    "originality": 0.0,
    "rarity": 0.912
   },
   "score": 30.8,
   "rank_prev": 31,
   "is_new_entry": false,
   "rank_change": -20,
   "reasons": [
    "📱 強調裝置端推論",
    "✅ 寬鬆授權（cc-by-4.0）",
    "🔗 量化轉檔自 nvidia/parakeet-tdt-0.6b-v3"
   ],
   "pick_rank": null
  },
  {
   "id": "JetBrains/Mellum2.1-12B-A2.5B-Thinking",
   "author": "JetBrains",
   "author_fullname": null,
   "author_followers": null,
   "name": "Mellum2.1-12B-A2.5B-Thinking",
   "url": "https://huggingface.co/JetBrains/Mellum2.1-12B-A2.5B-Thinking",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 86,
   "downloads": 583,
   "trending_score": 85.0,
   "created_at": "2026-09-20T10:52:55.000Z",
   "last_modified": null,
   "age_days": 20.14,
   "like_velocity": 4.3,
   "params_b": 12.0,
   "active_params_b": 2.5,
   "is_moe": true,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [
    "2605.31268"
   ],
   "languages": [
    "en"
   ],
   "n_languages": 1,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "JetBrains/Mellum2-12B-A2.5B-Base",
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "mellum"
   ],
   "rank_trending": 52,
   "score_breakdown": {
    "momentum": 0.136,
    "velocity": 0.017,
    "recency": 0.237,
    "originality": 0.45,
    "rarity": 0.912
   },
   "score": 24.6,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "🧩 MoE 混合專家架構（啟用 2.5B）",
    "📄 附論文 arXiv:2605.31268",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 微調自 JetBrains/Mellum2-12B-A2.5B-Base"
   ],
   "pick_rank": null
  },
  {
   "id": "JonathanColetti/Qwen3.8-27B-Uncensored-GGUF",
   "author": "JonathanColetti",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-27B-Uncensored-GGUF",
   "url": "https://huggingface.co/JonathanColetti/Qwen3.8-27B-Uncensored-GGUF",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "llama.cpp",
   "likes": 1520,
   "downloads": 2363619,
   "trending_score": 84.0,
   "created_at": "2026-08-14T03:43:36.000Z",
   "last_modified": null,
   "age_days": 57.44,
   "like_velocity": 26.5,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gguf",
    "uncensored",
    "qwen3.8",
    "mtp",
    "speculative-decoding",
    "imatrix"
   ],
   "rank_trending": 53,
   "score_breakdown": {
    "momentum": 0.11,
    "velocity": 0.458,
    "recency": 0.017,
    "originality": 0.0,
    "rarity": 0.912
   },
   "score": 24.7,
   "rank_prev": 51,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "alesha-pro/Qwen3.8-Flash-Next-abliterated-GSQ-RCO-Strata-GGUF",
   "author": "alesha-pro",
   "author_fullname": null,
   "author_followers": null,
   "name": "Qwen3.8-Flash-Next-abliterated-GSQ-RCO-Strata-GGUF",
   "url": "https://huggingface.co/alesha-pro/Qwen3.8-Flash-Next-abliterated-GSQ-RCO-Strata-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "gguf",
   "likes": 91,
   "downloads": 61596,
   "trending_score": 84.0,
   "created_at": "2026-10-04T01:47:40.000Z",
   "last_modified": null,
   "age_days": 6.52,
   "like_velocity": 14.0,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2604.18556",
    "2605.00649"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "gsq",
    "rco",
    "strata",
    "abliterated",
    "control-vector"
   ],
   "rank_trending": 54,
   "score_breakdown": {
    "momentum": 0.11,
    "velocity": 0.169,
    "recency": 0.628,
    "originality": 0.0,
    "rarity": 0.735
   },
   "score": 24.9,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 7 天前才發布",
    "📄 附論文 arXiv:2604.18556",
    "🔗 量化轉檔自 ISTA-DASLab/Qwen3.8-Flash-Next-GSQ-RCO-GGUF",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "zai-org/GLM-5.3",
   "author": "zai-org",
   "author_fullname": null,
   "author_followers": null,
   "name": "GLM-5.3",
   "url": "https://huggingface.co/zai-org/GLM-5.3",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 2163,
   "downloads": 1670161,
   "trending_score": 80.0,
   "created_at": "2026-08-25T06:42:50.000Z",
   "last_modified": null,
   "age_days": 46.31,
   "like_velocity": 46.7,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [
    "2602.15763"
   ],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "glm_moe_dsa",
    "fp8"
   ],
   "rank_trending": 55,
   "score_breakdown": {
    "momentum": 0.085,
    "velocity": 0.644,
    "recency": 0.037,
    "originality": 1.0,
    "rarity": 0.912
   },
   "score": 43.7,
   "rank_prev": 53,
   "is_new_entry": false,
   "rank_change": -2,
   "reasons": [
    "📄 附論文 arXiv:2602.15763"
   ],
   "pick_rank": null
  },
  {
   "id": "nvidia/Nemotron-3-Diarization",
   "author": "nvidia",
   "author_fullname": null,
   "author_followers": null,
   "name": "Nemotron-3-Diarization",
   "url": "https://huggingface.co/nvidia/Nemotron-3-Diarization",
   "pipeline_tag": "voice-activity-detection",
   "task_zh": "語音活動偵測",
   "task_group": "audio",
   "task_group_zh": "語音 / 音訊",
   "library": "nemo",
   "likes": 750,
   "downloads": 72286,
   "trending_score": 79.0,
   "created_at": "2026-09-01T13:16:57.000Z",
   "last_modified": null,
   "age_days": 39.04,
   "like_velocity": 19.2,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "openmdw-1.1",
   "permissive_license": false,
   "arxiv": [
    "2409.06656",
    "2507.18446",
    "2605.15442"
   ],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "gguf",
    "nemotron3_diarization",
    "audio-frame-classification",
    "speaker-diarization",
    "streaming-sortformer",
    "speaker-tagging"
   ],
   "rank_trending": 56,
   "score_breakdown": {
    "momentum": 0.068,
    "velocity": 0.237,
    "recency": 0.062,
    "originality": 0.0,
    "rarity": 1.0
   },
   "score": 19.2,
   "rank_prev": 35,
   "is_new_entry": false,
   "rank_change": -21,
   "reasons": [
    "🧭 今日榜單少見的任務：語音活動偵測",
    "📄 附論文 arXiv:2409.06656"
   ],
   "pick_rank": null
  },
  {
   "id": "huihui-ai/Huihui-Qwen3.8-27B-abliterated-GGUF",
   "author": "huihui-ai",
   "author_fullname": null,
   "author_followers": null,
   "name": "Huihui-Qwen3.8-27B-abliterated-GGUF",
   "url": "https://huggingface.co/huihui-ai/Huihui-Qwen3.8-27B-abliterated-GGUF",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": "transformers",
   "likes": 1248,
   "downloads": 2156962,
   "trending_score": 78.0,
   "created_at": "2026-08-16T13:18:55.000Z",
   "last_modified": null,
   "age_days": 55.04,
   "like_velocity": 22.7,
   "params_b": 27.0,
   "active_params_b": null,
   "is_moe": false,
   "license": "apache-2.0",
   "permissive_license": true,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "quantized",
   "derivative_zh": "量化 / 格式轉檔",
   "base_model": "Qwen/Qwen3.8-27B",
   "safety_removed": true,
   "on_device": true,
   "tags": [
    "gguf",
    "abliterated",
    "uncensored",
    "huihui",
    "qwen3",
    "unsloth"
   ],
   "rank_trending": 57,
   "score_breakdown": {
    "momentum": 0.042,
    "velocity": 0.356,
    "recency": 0.02,
    "originality": 0.0,
    "rarity": 0.735
   },
   "score": 18.0,
   "rank_prev": 52,
   "is_new_entry": false,
   "rank_change": -5,
   "reasons": [
    "📱 強調裝置端推論",
    "✅ 寬鬆授權（apache-2.0）",
    "🔗 量化轉檔自 Qwen/Qwen3.8-27B",
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "audnai/penclaw-GLM-5.3-abliterated",
   "author": "audnai",
   "author_fullname": null,
   "author_followers": null,
   "name": "penclaw-GLM-5.3-abliterated",
   "url": "https://huggingface.co/audnai/penclaw-GLM-5.3-abliterated",
   "pipeline_tag": "text-generation",
   "task_zh": "文字生成",
   "task_group": "language",
   "task_group_zh": "語言",
   "library": "transformers",
   "likes": 378,
   "downloads": 1902,
   "trending_score": 78.0,
   "created_at": "2026-09-01T17:52:24.000Z",
   "last_modified": null,
   "age_days": 38.85,
   "like_velocity": 9.7,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": "other",
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "glm_moe_dsa",
    "abliterated",
    "uncensored",
    "warlock",
    "audn",
    "GLM-5.3"
   ],
   "rank_trending": 58,
   "score_breakdown": {
    "momentum": 0.042,
    "velocity": 0.102,
    "recency": 0.062,
    "originality": 1.0,
    "rarity": 0.912
   },
   "score": 29.1,
   "rank_prev": 48,
   "is_new_entry": false,
   "rank_change": -10,
   "reasons": [
    "⚠️ 已移除安全對齊（abliterated / uncensored）"
   ],
   "pick_rank": null
  },
  {
   "id": "RunningHubAI/rh-qwen-image-2.1-lora-2104918997757157378",
   "author": "RunningHubAI",
   "author_fullname": null,
   "author_followers": null,
   "name": "rh-qwen-image-2.1-lora-2104918997757157378",
   "url": "https://huggingface.co/RunningHubAI/rh-qwen-image-2.1-lora-2104918997757157378",
   "pipeline_tag": "text-to-image",
   "task_zh": "文生圖",
   "task_group": "genmedia",
   "task_group_zh": "影像 / 影音生成",
   "library": null,
   "likes": 84,
   "downloads": 0,
   "trending_score": 77.0,
   "created_at": "2026-09-30T09:35:01.000Z",
   "last_modified": null,
   "age_days": 10.19,
   "like_velocity": 8.2,
   "params_b": null,
   "active_params_b": null,
   "is_moe": false,
   "license": null,
   "permissive_license": false,
   "arxiv": [],
   "languages": [],
   "n_languages": 0,
   "inference_providers": 0,
   "gated": false,
   "derivative": "original",
   "derivative_zh": "原創",
   "base_model": null,
   "safety_removed": false,
   "on_device": false,
   "tags": [
    "comfyui",
    "lora"
   ],
   "rank_trending": 59,
   "score_breakdown": {
    "momentum": 0.008,
    "velocity": 0.068,
    "recency": 0.483,
    "originality": 1.0,
    "rarity": 0.882
   },
   "score": 33.1,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜"
   ],
   "pick_rank": null
  },
  {
   "id": "Mia-AiLab/GLM-5.3-Flash-EXL3-4bpw-TensorFold-Ablit",
   "author": "Mia-AiLab",
   "author_fullname": null,
   "author_followers": null,
   "name": "GLM-5.3-Flash-EXL3-4bpw-TensorFold-Ablit",
   "url": "https://huggingface.co/Mia-AiLab/GLM-5.3-Flash-EXL3-4bpw-TensorFold-Ablit",
   "pipeline_tag": "image-text-to-text",
   "task_zh": "圖文理解（VLM）",
   "task_group": "multimodal",
   "task_group_zh": "多模態",
   "library": null,
   "likes": 86,
   "downloads": 3056,
   "trending_score": 77.0,
   "created_at": "2026-10-05T07:33:21.000Z",
   "last_modified": null,
   "age_days": 5.28,
   "like_velocity": 16.3,
   "params_b": null,
   "active_params_b": null,
   "is_moe": true,
   "license": "mit",
   "permissive_license": true,
   "arxiv": [],
   "languages": [
    "en",
    "zh"
   ],
   "n_languages": 2,
   "inference_providers": 0,
   "gated": false,
   "derivative": "finetune",
   "derivative_zh": "微調衍生",
   "base_model": "Mia-AiLab/GLM-5.3-Flash-EXL3-4bpw-TensorFold",
   "safety_removed": true,
   "on_device": false,
   "tags": [
    "glm5_next",
    "glm",
    "glm-5.3",
    "glm-5.3-flash",
    "exl3",
    "tensorfold"
   ],
   "rank_trending": 60,
   "score_breakdown": {
    "momentum": 0.008,
    "velocity": 0.203,
    "recency": 0.686,
    "originality": 0.45,
    "rarity": 0.735
   },
   "score": 29.8,
   "rank_prev": null,
   "is_new_entry": true,
   "rank_change": null,
   "reasons": [
    "🆕 今日新進榜",
    "⏱️ 5 天前才發布",
    "🧩 MoE 混合專家架構",
    "✅ 寬鬆授權（mit）",
    "🔗 微調自 Mia-AiLab/GLM-5.3-Flash-EXL3-4bpw-TensorFold"
   ],
   "pick_rank": null
  }
 ]
};
